#-----------------------------------------------------------------------------------------------------------------
# Hello! Welcome to the Complementary block library. Shaders use these IDs to perform block specific effects.
# If you want to add modded blocks, please feel free to put your block IDs in the following sections:
#
# block.10009: Leaves
# block.10005: Foliage (for Mc 1.13 and above use the first "block.10005". Otherwise use the second "block.10005")
# block.10024: Modded Ores (shader will do its best to detect ore-pixels if "Enable Glowing Ores" setting is on)
# block.10028: Modded Light Sources / Emissives (shader will do its best to give a nice glow to the block)
# block.20000: No Parallax Occlusion Mapping
#
#
#
# ID Info:
# 5XXX - Block Entities
# 1XXXX - Terrain
# * Note that terrain IDs that satisfy "XXXXX % 4 == 1" are treated non-solid for Advanced Colored Lighting
# 3XXXX - Translucent
# * 31XXX - Translucents with advanced colored light tinting
# * 32XXX - Translucents with alternative shadow calculation
# 4XXXX - Items (see item.properties)
# * 44XXX - Items for colored handheld lighting
# * 45XXX - Items for other Iris exclusive features
# 5XXXX - Entities (see entity.properties)
#-----------------------------------------------------------------------------------------------------------------

block.10024=shale_titanium_ore
