dependencies {
    compileOnly("io.github.llamalad7:mixinextras-neoforge:0.5.3")
    annotationProcessor("io.github.llamalad7:mixinextras-neoforge:0.5.3")
}


repositories {
    maven {
        name = "CurseMaven"
        url = "https://cursemaven.com"
    }
}
dependencies {
    implementation "curse.maven:serene-seasons-291874:6182596"
}


repositories {
  maven {
    name = "Progwml6's maven"
    url = "https://dvs1.progwml6.com/files/maven/"
  }
  maven {
    name = "Jared's maven"
    url = "https://maven.blamejared.com/"
  }
  maven {
    name = "ModMaven"
    url = "https://modmaven.dev"
  }
}

dependencies {
    compileOnly("mezz.jei:jei-1.21.1-common-api:19.21.0.247")
    compileOnly("mezz.jei:jei-1.21.1-neoforge-api:19.21.0.247")
    runtimeOnly("mezz.jei:jei-1.21.1-neoforge:19.21.0.247")
}


