package net.mcreator.survivalreimagined.configuration;

import net.neoforged.neoforge.common.ModConfigSpec;

public class SurvivalReimaginedConfigConfiguration {
	public static final ModConfigSpec.Builder BUILDER = new ModConfigSpec.Builder();
	public static final ModConfigSpec SPEC;
	public static final ModConfigSpec.ConfigValue<Boolean> ZOMBIFICATION;
	public static final ModConfigSpec.ConfigValue<Boolean> IMMUNITY_ZOMBIFICATION;
	public static final ModConfigSpec.ConfigValue<Double> TIME_ZOMBIFICATION;
	public static final ModConfigSpec.ConfigValue<Double> CHANCE_ZOMBIFICATION;
	public static final ModConfigSpec.ConfigValue<Boolean> DARKNESS_EFFECTS;
	public static final ModConfigSpec.ConfigValue<Double> DARKNESS_LEVEL;
	public static final ModConfigSpec.ConfigValue<Double> LIGHT_LEVEL;
	public static final ModConfigSpec.ConfigValue<Double> PARANOIA_DELAY;
	public static final ModConfigSpec.ConfigValue<Boolean> BINDING_SCULK;
	public static final ModConfigSpec.ConfigValue<Boolean> BLOOD_MOON;
	public static final ModConfigSpec.ConfigValue<Boolean> BLOODMOON_SLEEP;
	public static final ModConfigSpec.ConfigValue<Boolean> DISABLE_MOBS;
	public static final ModConfigSpec.ConfigValue<Double> FULL_MOON;
	public static final ModConfigSpec.ConfigValue<Double> PHASES_ONE;
	public static final ModConfigSpec.ConfigValue<Double> PHASES_TWO;
	public static final ModConfigSpec.ConfigValue<Double> BREAK_SPEED;
	public static final ModConfigSpec.ConfigValue<Boolean> VANILLA_PORTAL;
	public static final ModConfigSpec.ConfigValue<Boolean> HUNGER_VANILLA;
	public static final ModConfigSpec.ConfigValue<Boolean> DEBUFF_HUNGER;
	public static final ModConfigSpec.ConfigValue<Boolean> HUNGEREFFECT_VANILLA;
	public static final ModConfigSpec.ConfigValue<Boolean> HUNGER_RAWFOOD;
	public static final ModConfigSpec.ConfigValue<Boolean> SPOIL_FOOD;
	public static final ModConfigSpec.ConfigValue<Boolean> WEIGHT;
	public static final ModConfigSpec.ConfigValue<Boolean> BLEEDING_EFFECT;
	public static final ModConfigSpec.ConfigValue<Double> BLEED_CHANCE;
	public static final ModConfigSpec.ConfigValue<Boolean> BROKEN_LEGS;
	public static final ModConfigSpec.ConfigValue<Double> BROKEN_LEG_CHANCE;
	public static final ModConfigSpec.ConfigValue<Boolean> GHOST_SPAWN;
	static {
		BUILDER.push("status_effects");
		BUILDER.push("zombification");
		ZOMBIFICATION = BUILDER.comment("Allow Zombies to inflict Zombfication").define("zombification", true);
		IMMUNITY_ZOMBIFICATION = BUILDER.comment("Allow the Golden Heart to grant the player immunity to Zombification").define("zombification_immunity", true);
		TIME_ZOMBIFICATION = BUILDER.comment("Time it takes for Zombification to progress to next stage. Default is 6000 in ticks (5 Minutes)").define("zombification_time", (double) 6000);
		CHANCE_ZOMBIFICATION = BUILDER.comment("Chance for a Zombie to inflict Zombification. Default is 0.25 (25%)").define("zombification_chance", (double) 0.25);
		BUILDER.pop();
		BUILDER.push("paranoia/_fear");
		DARKNESS_EFFECTS = BUILDER.comment("Allow the player to feel paranoia/fear if in dark areas").define("paranoiaand_fear", true);
		DARKNESS_LEVEL = BUILDER.comment("Minimum Light Level needed for Darkness effects to take effect (Default is 0, Range: 0 - 15)").define("darkness_level", (double) 0);
		LIGHT_LEVEL = BUILDER.comment("Minimum Light Level needed for Darkness effects to stop take effect (Default is 5, Range: 0 - 15)").define("light_level", (double) 5);
		PARANOIA_DELAY = BUILDER.comment("Time in ticks for Paranoia to turn into Fear (Default is 1000 in ticks)").define("paranoia_to_fear_delay", (double) 1000);
		BUILDER.pop();
		BUILDER.push("binding_sculk");
		BINDING_SCULK = BUILDER.comment("Binding Sculk applied when walking over Sculk").define("binding_sculk", true);
		BUILDER.pop();
		BUILDER.pop();
		BUILDER.push("events");
		BUILDER.push("blood_moon");
		BLOOD_MOON = BUILDER.comment("Can Blood Moon happen?").define("blood_moon", true);
		BLOODMOON_SLEEP = BUILDER.comment("Allow Sleeping through Bloodmoon").define("bloodmoon_sleep", false);
		DISABLE_MOBS = BUILDER.comment("Disable Zombies and Skeletons spawns during bloodmoon").define("disable_normal_mob_spawning", true);
		BUILDER.push("blood_moon_spawn_chance");
		FULL_MOON = BUILDER.comment("Full Moon Bloodmoon chance. Defualt is 0.15 (15%)").define("full_moon_chance", (double) 0.15);
		PHASES_ONE = BUILDER.comment("Gibbous and Quarter phases chance. Defualt is 0.1 (10%) ").define("gibbous/_quarter_chance", (double) 0.1);
		PHASES_TWO = BUILDER.comment("New Moon and crescent phases chance. Defualt is 0.075 (7.5%) ").define("new_moon/_crescent_chance", (double) 0.075);
		BUILDER.pop();
		BUILDER.pop();
		BUILDER.pop();
		BUILDER.push("gameplay");
		BUILDER.push("mechanic_overrides");
		BREAK_SPEED = BUILDER.comment("Block Breaking Speed. Default is 0.45 (45%) Vanilla is 1 (100%)").define("block_break_speed", (double) 0.45);
		VANILLA_PORTAL = BUILDER.comment("Disable Nether portal override mechanics (reverts to vanilla nether portal)").define("vanilla_portal", false);
		BUILDER.pop();
		BUILDER.push("hunger");
		HUNGER_VANILLA = BUILDER.comment("Disable hunger bar changes (Reverts to vanilla mechanics)").define("vanilla_hunger", false);
		DEBUFF_HUNGER = BUILDER.comment("Hunger debuffs (Can't jump on 2 drumsticks, slower walk speed on 1 drumstick)").define("hunger_debuffs", true);
		HUNGEREFFECT_VANILLA = BUILDER.comment("Disable Hunger Effect changes (Reverts to Vanilla mechanics)").define("vanilla_hunger_effect", false);
		HUNGER_RAWFOOD = BUILDER.comment("Eating Raw Food gives the player hunger status effect").define("raw_food", true);
		SPOIL_FOOD = BUILDER.comment("Allow meat to spoil").define("food_spoil", true);
		BUILDER.pop();
		BUILDER.pop();
		BUILDER.push("experimental_features");
		BUILDER.push("difficulty");
		BUILDER.push("weight");
		WEIGHT = BUILDER.comment("Enable/Disable Weight System").define("weight_system", true);
		BUILDER.pop();
		BUILDER.push("bleeding");
		BLEEDING_EFFECT = BUILDER.comment("Allow Crimson Arachnid to Inflict Bleeding").define("bleeding", true);
		BLEED_CHANCE = BUILDER.comment("Chance to contract Bleeding Effect. Defualt is 0.1 (10%)").define("bleeding_chance", (double) 0.1);
		BUILDER.pop();
		BUILDER.push("leg_breaking");
		BROKEN_LEGS = BUILDER.comment("Enable/Disable breaking your legs from fall damage").define("broken_legs", true);
		BROKEN_LEG_CHANCE = BUILDER.comment("Chance to break your leg from a fall. Defualt is 0.2 (20%)").define("broken_leg_chance", (double) 0.2);
		BUILDER.pop();
		BUILDER.pop();
		BUILDER.push("lore_content");
		GHOST_SPAWN = BUILDER.comment("Allow Ghosts to spawn").define("enables_ghosts", false);
		BUILDER.pop();
		BUILDER.pop();

		SPEC = BUILDER.build();
	}

}