#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Nov 22 09:48:50 PST 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=photon_v1.2a.zip
