	[status_effects.zombification]
		#Allow Zombies to inflict Zombfication
		zombification = true
		#Allow the Golden Heart to grant the player immunity to Zombification
		zombification_immunity = true
		#Time it takes for Zombification to progress to next stage. Default is 6000 in ticks (5 Minutes)
		zombification_time = 6000.0
		#Chance for a Zombie to inflict Zombification. Default is 0.25 (25%)
		zombification_chance = 0.25

	[status_effects."paranoia/_fear"]
		#Allow the player to feel paranoia/fear if in dark areas
		paranoiaand_fear = false
		#Minimum Light Level needed for Darkness effects to take effect (Default is 0, Range: 0 - 15)
		darkness_level = 0.0
		#Minimum Light Level needed for Darkness effects to stop take effect (Default is 5, Range: 0 - 15)
		light_level = 5.0
		#Time in ticks for Paranoia to turn into Fear (Default is 1000 in ticks)
		paranoia_to_fear_delay = 1000.0

	[status_effects.binding_sculk]
		#Binding Sculk applied when walking over Sculk
		binding_sculk = true

	[events.blood_moon]
		#Can Blood Moon happen?
		blood_moon = true
		#Allow Sleeping through Bloodmoon
		bloodmoon_sleep = false
		#Disable Zombies and Skeletons spawns during bloodmoon
		disable_normal_mob_spawning = true

		[events.blood_moon.blood_moon_spawn_chance]
			#Full Moon Bloodmoon chance. Defualt is 0.15 (15%)
			full_moon_chance = 0.15
			#Gibbous and Quarter phases chance. Defualt is 0.1 (10%) 
			"gibbous/_quarter_chance" = 0.1
			#New Moon and crescent phases chance. Defualt is 0.075 (7.5%) 
			"new_moon/_crescent_chance" = 0.075

	[gameplay.mechanic_overrides]
		#Block Breaking Speed. Default is 0.45 (45%) Vanilla is 1 (100%)
		block_break_speed = 0.45
		#Disable Nether portal override mechanics (reverts to vanilla nether portal)
		vanilla_portal = false

	[gameplay.hunger]
		#Disable hunger bar changes (Reverts to vanilla mechanics)
		vanilla_hunger = false
		#Hunger debuffs (Can't jump on 2 drumsticks, slower walk speed on 1 drumstick)
		hunger_debuffs = true
		#Disable Hunger Effect changes (Reverts to Vanilla mechanics)
		vanilla_hunger_effect = false
		#Eating Raw Food gives the player hunger status effect
		raw_food = true
		#Allow meat to spoil
		food_spoil = true

	[experimental_features.bleeding]
		#Allow Crimson Arachnid to Inflict Bleeding
		bleeding = false
		#Chance to contract Bleeding Effect. Defualt is 0.1 (10%)
		bleeding_chance = 0.1

	[experimental_features.difficulty]
		#Enable/Disable Weight System
		weight_system = false
		#Enable/Disable breaking your legs from fall damage
		broken_legs = false
		#Chance to break your leg from a fall. Defualt is 0.2 (20%)
		broken_leg_chance = 0.2
