/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.survivalreimagined.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.client.event.RegisterColorHandlersEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import net.mcreator.survivalreimagined.block.*;
import net.mcreator.survivalreimagined.SurvivalReimaginedMod;

public class SurvivalReimaginedModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(SurvivalReimaginedMod.MODID);
	public static final DeferredBlock<Block> FLINTBLOCK;
	public static final DeferredBlock<Block> STONE_ROCK_BLOC;
	public static final DeferredBlock<Block> TIN_ORE;
	public static final DeferredBlock<Block> FORGE;
	public static final DeferredBlock<Block> METAL_REFINING_TABLE;
	public static final DeferredBlock<Block> CLAY_CRUCIBLE;
	public static final DeferredBlock<Block> CRUCIBLE;
	public static final DeferredBlock<Block> AXE_HEAD_MOLD;
	public static final DeferredBlock<Block> PICKAXE_HEAD_MOLD;
	public static final DeferredBlock<Block> SWORD_BLADE_MOLD;
	public static final DeferredBlock<Block> HOE_HEAD_MOLD;
	public static final DeferredBlock<Block> SHOVEL_HEAD_MOLD;
	public static final DeferredBlock<Block> SAW_BLADE_MOLD;
	public static final DeferredBlock<Block> HAMMER_HEAD_MOLD;
	public static final DeferredBlock<Block> HELMET_MOLD;
	public static final DeferredBlock<Block> CHESTPLATE_MOLD;
	public static final DeferredBlock<Block> LEGGING_MOLD;
	public static final DeferredBlock<Block> BOOTS_MOLD;
	public static final DeferredBlock<Block> CLAY_SWORD_BLADE_MOLD;
	public static final DeferredBlock<Block> CLAY_PICKAXE_HEAD_MOLD;
	public static final DeferredBlock<Block> CLAY_AXE_HEAD_MOLD;
	public static final DeferredBlock<Block> CLAY_SHOVEL_HEAD_MOLD;
	public static final DeferredBlock<Block> CLAY_HOE_BLADE_MOLD;
	public static final DeferredBlock<Block> CLAY_HAMMER_HEAD_MOLD;
	public static final DeferredBlock<Block> CLAY_SAW_BLADE_MOLD;
	public static final DeferredBlock<Block> CLAY_HELMET_MOLD;
	public static final DeferredBlock<Block> CLAY_CHESTPLATE_MOLD;
	public static final DeferredBlock<Block> CLAY_LEGGINGS_MOLD;
	public static final DeferredBlock<Block> CLAY_BOOTS_MOLD;
	public static final DeferredBlock<Block> BLOCK_OF_BRONZE;
	public static final DeferredBlock<Block> ANDESITE_ROCK_BLOCK;
	public static final DeferredBlock<Block> GRANITE_ROCK_BLOCK;
	public static final DeferredBlock<Block> DIORITE_ROCK_B_LOCK;
	public static final DeferredBlock<Block> DRIPSTONE_ROCK_BLOCK;
	public static final DeferredBlock<Block> CALCITE_ROCK_BLOCK;
	public static final DeferredBlock<Block> TUFF_ROCK_BLOCK;
	public static final DeferredBlock<Block> MOSSY_STONE_ROCK_BLOCK;
	public static final DeferredBlock<Block> NETHERRACK_ROCK_BLOCK;
	public static final DeferredBlock<Block> END_STONE_ROCK_BLOCK;
	public static final DeferredBlock<Block> BLACKSTONE_ROCK_BLOCK;
	public static final DeferredBlock<Block> BASALT_ROCK_BLOCK;
	public static final DeferredBlock<Block> DEEPSLATE_ROCK_BLOCK;
	public static final DeferredBlock<Block> BLOCK_OF_RAW_TIN;
	public static final DeferredBlock<Block> BLOCK_OF_TIN;
	public static final DeferredBlock<Block> COW_CARCASS;
	public static final DeferredBlock<Block> COW_LEG;
	public static final DeferredBlock<Block> COW_HEAD;
	public static final DeferredBlock<Block> SAND_SALT_DEPOSIT;
	public static final DeferredBlock<Block> SHEEP_CARCASS;
	public static final DeferredBlock<Block> SHEEP_LEG;
	public static final DeferredBlock<Block> SHEEP_HEAD;
	public static final DeferredBlock<Block> CHICKEN_CARCASS;
	public static final DeferredBlock<Block> PIG_CARCASS;
	public static final DeferredBlock<Block> PIG_HEAD;
	public static final DeferredBlock<Block> PIG_LEG;
	public static final DeferredBlock<Block> KNIFE_BLADE_MOLD;
	public static final DeferredBlock<Block> CLAY_KNIFE_MOLD;
	public static final DeferredBlock<Block> MANGANESE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_MANGANESE_ORE;
	public static final DeferredBlock<Block> BLOCK_OF_STEEL;
	public static final DeferredBlock<Block> BLOCK_OF_MANGANESE;
	public static final DeferredBlock<Block> BLOCK_OF_RAW_MANGANESE;
	public static final DeferredBlock<Block> BLOCK_OF_RAW_REDSTONE;
	public static final DeferredBlock<Block> MINERAL_PROCESSING_TABLE;
	public static final DeferredBlock<Block> EMBEDDED_OBSIDIAN;
	public static final DeferredBlock<Block> COPPER_ROCK_BLOCK;
	public static final DeferredBlock<Block> APPLE_OAK_LEAVES;
	public static final DeferredBlock<Block> APPLE_TREE_SAPLING;
	public static final DeferredBlock<Block> APPLE;
	public static final DeferredBlock<Block> INGOT_MOLD;
	public static final DeferredBlock<Block> INGOT_CLAY_MOLD;
	public static final DeferredBlock<Block> HEMP;
	public static final DeferredBlock<Block> LIMESTONE_ROCK;
	public static final DeferredBlock<Block> VERIDIUM_ROCK;
	public static final DeferredBlock<Block> OCHRUM_ROCK;
	public static final DeferredBlock<Block> CRIMSITE_ROCK;
	public static final DeferredBlock<Block> SCORCHIA_ROCK;
	public static final DeferredBlock<Block> ASURINE_CRYSTAL;
	public static final DeferredBlock<Block> SCORIA_ROCK;
	public static final DeferredBlock<Block> SHALE;
	public static final DeferredBlock<Block> SHALE_ROCK;
	public static final DeferredBlock<Block> TITANIUM_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_TITANIUM_ORE;
	public static final DeferredBlock<Block> SHALE_TITANIUM_ORE;
	public static final DeferredBlock<Block> BLOCK_OF_TITANIUM;
	public static final DeferredBlock<Block> BLOCK_OF_RAW_TITANIUM;
	public static final DeferredBlock<Block> RADIANT_LOG;
	public static final DeferredBlock<Block> STRIPPED_RADIANT_LOG;
	public static final DeferredBlock<Block> RADIANT_PLANKS;
	public static final DeferredBlock<Block> RADIATED_LEAVES;
	public static final DeferredBlock<Block> RADIATED_SAPLING;
	public static final DeferredBlock<Block> RADIATED_STAIRS;
	public static final DeferredBlock<Block> RADIATED_SLAB;
	public static final DeferredBlock<Block> RADIATED_FENCE;
	public static final DeferredBlock<Block> RADIATED_FENCE_GATE;
	public static final DeferredBlock<Block> RADIATED_PRESSURE_PLATE;
	public static final DeferredBlock<Block> RADIATED_BUTTON;
	public static final DeferredBlock<Block> RADIATED_SHALE;
	public static final DeferredBlock<Block> THIN_RADIATED_VINES;
	public static final DeferredBlock<Block> THIN_RADIATED_VINE_BASE;
	public static final DeferredBlock<Block> RADIATED_MOSS;
	public static final DeferredBlock<Block> RADIATED_TALL_GRASS;
	public static final DeferredBlock<Block> THICK_RADIATED_VINES;
	public static final DeferredBlock<Block> THICK_RADIATED_VINES_BASE;
	public static final DeferredBlock<Block> RADIATED_ORCHID;
	public static final DeferredBlock<Block> SHALE_URANINITE_ORE;
	public static final DeferredBlock<Block> URANINITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_URANINITE_ORE;
	public static final DeferredBlock<Block> BLOCK_OF_RAW_URANINITE;
	public static final DeferredBlock<Block> POLISHED_SHALE;
	public static final DeferredBlock<Block> POLISHED_SHALE_BRICKS;
	public static final DeferredBlock<Block> POLISHED_CHISELED_SHALE;
	public static final DeferredBlock<Block> POLISHED_SHALE_STAIRS;
	public static final DeferredBlock<Block> POLISHED_SHALE_BRICK_STAIRS;
	public static final DeferredBlock<Block> POLISHED_SHALE_SLAB;
	public static final DeferredBlock<Block> POLISHED_SHALE_BRICK_SLAB;
	public static final DeferredBlock<Block> POLISHED_SHALE_WALL;
	public static final DeferredBlock<Block> POLOSHED_SHALE_BRICK_WALL;
	public static final DeferredBlock<Block> SHALE_STAIRS;
	public static final DeferredBlock<Block> SHALE_SLAB;
	public static final DeferredBlock<Block> SHALE_WALL;
	public static final DeferredBlock<Block> BLOCK_OF_URANIUM;
	public static final DeferredBlock<Block> URANIUM_ROD;
	public static final DeferredBlock<Block> RADIANT_TRAPDOOR;
	public static final DeferredBlock<Block> RADIANT_DOOR;
	public static final DeferredBlock<Block> STEEL_DOOR;
	public static final DeferredBlock<Block> STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> TURANITE_BLOCK;
	public static final DeferredBlock<Block> ADVANCED_ALLOY_FORGE;
	public static final DeferredBlock<Block> PLATED_DIAMOND_BLOCK;
	public static final DeferredBlock<Block> NETHERITE_SCRAP_BLOCK;
	public static final DeferredBlock<Block> SILVER_ORE;
	public static final DeferredBlock<Block> RAW_SILVER_BLOCK;
	public static final DeferredBlock<Block> SILVER_BLOCK;
	public static final DeferredBlock<Block> SAPPHIRE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_SAPPHIRE_ORE;
	public static final DeferredBlock<Block> SAPPHIRE_BLOCK;
	public static final DeferredBlock<Block> NITRE_BLOCK;
	public static final DeferredBlock<Block> RUNE_CLAY_MOLD;
	public static final DeferredBlock<Block> RUNE_MOLD;
	public static final DeferredBlock<Block> RUNE_MAGIC_INFUSER;
	public static final DeferredBlock<Block> RUBY_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_RUBY_ORE;
	public static final DeferredBlock<Block> BLOCK_OF_RUBY;
	public static final DeferredBlock<Block> AMBER_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_AMBER_ORE;
	public static final DeferredBlock<Block> BLOCK_OF_AMBER;
	public static final DeferredBlock<Block> WISTERIA_LOG;
	public static final DeferredBlock<Block> WISTERIA_LEAVES;
	public static final DeferredBlock<Block> FLOWING_WISTERIA_LEAVES;
	public static final DeferredBlock<Block> WISTERIA_SPIDER_LILY;
	public static final DeferredBlock<Block> WISTERIA_SAPLING;
	public static final DeferredBlock<Block> WISTERIA_LEAF_LITTER;
	public static final DeferredBlock<Block> WISTERIA_FLOWER_UPPER;
	public static final DeferredBlock<Block> WISTERIA_FLOWER_LOWER;
	public static final DeferredBlock<Block> DEEPSLATE_TIN_ORE;
	public static final DeferredBlock<Block> OBSIDIAN_ROCK;
	public static final DeferredBlock<Block> HEMATITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_HEMATITE_ORE;
	public static final DeferredBlock<Block> BASALT_HEMATITE_ORE;
	public static final DeferredBlock<Block> HEMATITE_BLOCK;
	public static final DeferredBlock<Block> MAGNETITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_MAGNETITE_ORE;
	public static final DeferredBlock<Block> BASALT_MAGNETITE_ORE;
	public static final DeferredBlock<Block> MAGNETITE_BLOCK;
	public static final DeferredBlock<Block> MALACHITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_MALACHITE_ORE;
	public static final DeferredBlock<Block> RAW_MALACHITE_BLOCK;
	public static final DeferredBlock<Block> AZURITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_AZURITE_ORE;
	public static final DeferredBlock<Block> RAW_AZURITE_BLOCK;
	public static final DeferredBlock<Block> CASSITERITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_CASSITERITE_ORE;
	public static final DeferredBlock<Block> RAW_CASSITERITE_BLOCK;
	public static final DeferredBlock<Block> DEEPSLATE_SILVER_ORE;
	public static final DeferredBlock<Block> ARGENTITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_ARGENTITE_ORE;
	public static final DeferredBlock<Block> BASALT_ARGENTITE_ORE;
	public static final DeferredBlock<Block> ARGENTITE_BLOCK;
	public static final DeferredBlock<Block> BASALT_URANINITE_ORE;
	public static final DeferredBlock<Block> CALAVERITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_CALAVERITE_ORE;
	public static final DeferredBlock<Block> BASALT_CALAVERITE_ORE;
	public static final DeferredBlock<Block> CALAVERITE_BLOCK;
	public static final DeferredBlock<Block> MANGANITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_MANGANITE_ORE;
	public static final DeferredBlock<Block> BASALT_MANGANITE_ORE;
	public static final DeferredBlock<Block> MANGANITE_BLOCK;
	public static final DeferredBlock<Block> PYROLUSITE_ORE;
	public static final DeferredBlock<Block> PYROLUSITE_BLOCK;
	public static final DeferredBlock<Block> DEEPSLATE_PYROLUSITE_ORE;
	public static final DeferredBlock<Block> URANOPHANE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_URANOPHANE_ORE;
	public static final DeferredBlock<Block> BASALT_URANOPHANE_ORE;
	public static final DeferredBlock<Block> SHALE_URANOPHANE_ORE;
	public static final DeferredBlock<Block> URANOPHANE_BLOCK;
	public static final DeferredBlock<Block> ILMENITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_ILMENITE_ORE;
	public static final DeferredBlock<Block> BASALT_ILMENITE_ORE;
	public static final DeferredBlock<Block> ILMENITE_BLOCK;
	public static final DeferredBlock<Block> KIMBERLITE_ROCK;
	public static final DeferredBlock<Block> KIMBERLITE;
	public static final DeferredBlock<Block> KIMBERLITE_STALAGMITE_TOP;
	public static final DeferredBlock<Block> KIMBERLITE_STALAGMITE_MIDDLE;
	public static final DeferredBlock<Block> KIMBERLITE_STALAGMITE_BASE;
	public static final DeferredBlock<Block> KIMBERLITE_STALAGTITE_TIP;
	public static final DeferredBlock<Block> KIMBERLITE_STALAGTITE_MIDDLE;
	public static final DeferredBlock<Block> KIMBERLITE_STALAGTITE_BASE;
	public static final DeferredBlock<Block> DEEPSLATE_STALAGMITE_TOP;
	public static final DeferredBlock<Block> DEEPSLATE_STALAGMITE_MIDDLE;
	public static final DeferredBlock<Block> DEEPSLATE_STALAGMITE_BASE;
	public static final DeferredBlock<Block> DEEPSLATE_STALAGTITE_TIP;
	public static final DeferredBlock<Block> DEEPSLATE_STALAGTITE_MIDDLE;
	public static final DeferredBlock<Block> DEEPSLATE_STALAGTITE_BASE;
	public static final DeferredBlock<Block> STONE_STALAGMITE_TOP;
	public static final DeferredBlock<Block> STONE_STALAGMITE_MIDDLE;
	public static final DeferredBlock<Block> STONE_STALAGMITE_BASE;
	public static final DeferredBlock<Block> STONE_STALAGTITE_TIP;
	public static final DeferredBlock<Block> STONE_STALAGTITE_MIDDLE;
	public static final DeferredBlock<Block> STONE_STALAGTITE_BASE;
	public static final DeferredBlock<Block> BASALT_STALAGMITE_TOP;
	public static final DeferredBlock<Block> BASALT_STALAGMITE_MIDDLE;
	public static final DeferredBlock<Block> BASALT_STALAGMITE_BASE;
	public static final DeferredBlock<Block> BASALT_STALAGTITE_TIP;
	public static final DeferredBlock<Block> BASALT_STALAGTITE_MIDDLE;
	public static final DeferredBlock<Block> BASALT_STALAGTITE_BASE;
	public static final DeferredBlock<Block> BASALT_SAPPHIRE_ORE;
	public static final DeferredBlock<Block> KIMBERLITE_SAPPHIRE_ORE;
	public static final DeferredBlock<Block> BASALT_DIAMOND_ORE;
	public static final DeferredBlock<Block> KIMBERLITE_DIAMOND_ORE;
	public static final DeferredBlock<Block> BASALT_EMERALD_ORE;
	public static final DeferredBlock<Block> KIMBERLITE_EMERALD_ORE;
	public static final DeferredBlock<Block> BASALT_RUBY_ORE;
	public static final DeferredBlock<Block> KIMBERLITE_RUBY_ORE;
	public static final DeferredBlock<Block> BASALT_LAPIS_ORE;
	public static final DeferredBlock<Block> KIMBERLITE_LAPIS_ORE;
	public static final DeferredBlock<Block> BASALT_AMBER_ORE;
	public static final DeferredBlock<Block> KIMBERLITE_AMBER_ORE;
	public static final DeferredBlock<Block> SULFUR_ORE;
	public static final DeferredBlock<Block> NITRE_POWDER;
	public static final DeferredBlock<Block> STRIPPED_WISTERIA_LOG;
	public static final DeferredBlock<Block> WISTERIA_WOOD;
	public static final DeferredBlock<Block> WISTERIA_PLANKS;
	public static final DeferredBlock<Block> WISTERIA_STAIRS;
	public static final DeferredBlock<Block> WISTERIA_SLAB;
	public static final DeferredBlock<Block> WISTERIA_FENCE;
	public static final DeferredBlock<Block> WISTERIA_FENCE_GATE;
	public static final DeferredBlock<Block> WISTERIA_DOOR;
	public static final DeferredBlock<Block> WISTERIA_TRAPDOOR;
	public static final DeferredBlock<Block> WISTERIA_BUTTON;
	public static final DeferredBlock<Block> WISTERIA_PRESSURE_PLATE;
	public static final DeferredBlock<Block> PURE_SALT_BLOCK;
	public static final DeferredBlock<Block> SALT_DEPOSIT;
	static {
		FLINTBLOCK = REGISTRY.register("flintblock", FlintblockBlock::new);
		STONE_ROCK_BLOC = REGISTRY.register("stone_rock_bloc", StoneRockBlocBlock::new);
		TIN_ORE = REGISTRY.register("tin_ore", TinOreBlock::new);
		FORGE = REGISTRY.register("forge", ForgeBlock::new);
		METAL_REFINING_TABLE = REGISTRY.register("metal_refining_table", MetalRefiningTableBlock::new);
		CLAY_CRUCIBLE = REGISTRY.register("clay_crucible", ClayCrucibleBlock::new);
		CRUCIBLE = REGISTRY.register("crucible", CrucibleBlock::new);
		AXE_HEAD_MOLD = REGISTRY.register("axe_head_mold", AxeHeadMoldBlock::new);
		PICKAXE_HEAD_MOLD = REGISTRY.register("pickaxe_head_mold", PickaxeHeadMoldBlock::new);
		SWORD_BLADE_MOLD = REGISTRY.register("sword_blade_mold", SwordBladeMoldBlock::new);
		HOE_HEAD_MOLD = REGISTRY.register("hoe_head_mold", HoeHeadMoldBlock::new);
		SHOVEL_HEAD_MOLD = REGISTRY.register("shovel_head_mold", ShovelHeadMoldBlock::new);
		SAW_BLADE_MOLD = REGISTRY.register("saw_blade_mold", SawBladeMoldBlock::new);
		HAMMER_HEAD_MOLD = REGISTRY.register("hammer_head_mold", HammerHeadMoldBlock::new);
		HELMET_MOLD = REGISTRY.register("helmet_mold", HelmetMoldBlock::new);
		CHESTPLATE_MOLD = REGISTRY.register("chestplate_mold", ChestplateMoldBlock::new);
		LEGGING_MOLD = REGISTRY.register("legging_mold", LeggingMoldBlock::new);
		BOOTS_MOLD = REGISTRY.register("boots_mold", BootsMoldBlock::new);
		CLAY_SWORD_BLADE_MOLD = REGISTRY.register("clay_sword_blade_mold", ClaySwordBladeMoldBlock::new);
		CLAY_PICKAXE_HEAD_MOLD = REGISTRY.register("clay_pickaxe_head_mold", ClayPickaxeHeadMoldBlock::new);
		CLAY_AXE_HEAD_MOLD = REGISTRY.register("clay_axe_head_mold", ClayAxeHeadMoldBlock::new);
		CLAY_SHOVEL_HEAD_MOLD = REGISTRY.register("clay_shovel_head_mold", ClayShovelHeadMoldBlock::new);
		CLAY_HOE_BLADE_MOLD = REGISTRY.register("clay_hoe_blade_mold", ClayHoeBladeMoldBlock::new);
		CLAY_HAMMER_HEAD_MOLD = REGISTRY.register("clay_hammer_head_mold", ClayHammerHeadMoldBlock::new);
		CLAY_SAW_BLADE_MOLD = REGISTRY.register("clay_saw_blade_mold", ClaySawBladeMoldBlock::new);
		CLAY_HELMET_MOLD = REGISTRY.register("clay_helmet_mold", ClayHelmetMoldBlock::new);
		CLAY_CHESTPLATE_MOLD = REGISTRY.register("clay_chestplate_mold", ClayChestplateMoldBlock::new);
		CLAY_LEGGINGS_MOLD = REGISTRY.register("clay_leggings_mold", ClayLeggingsMoldBlock::new);
		CLAY_BOOTS_MOLD = REGISTRY.register("clay_boots_mold", ClayBootsMoldBlock::new);
		BLOCK_OF_BRONZE = REGISTRY.register("block_of_bronze", BlockOfBronzeBlock::new);
		ANDESITE_ROCK_BLOCK = REGISTRY.register("andesite_rock_block", AndesiteRockBlockBlock::new);
		GRANITE_ROCK_BLOCK = REGISTRY.register("granite_rock_block", GraniteRockBlockBlock::new);
		DIORITE_ROCK_B_LOCK = REGISTRY.register("diorite_rock_b_lock", DioriteRockBLockBlock::new);
		DRIPSTONE_ROCK_BLOCK = REGISTRY.register("dripstone_rock_block", DripstoneRockBlockBlock::new);
		CALCITE_ROCK_BLOCK = REGISTRY.register("calcite_rock_block", CalciteRockBlockBlock::new);
		TUFF_ROCK_BLOCK = REGISTRY.register("tuff_rock_block", TuffRockBlockBlock::new);
		MOSSY_STONE_ROCK_BLOCK = REGISTRY.register("mossy_stone_rock_block", MossyStoneRockBlockBlock::new);
		NETHERRACK_ROCK_BLOCK = REGISTRY.register("netherrack_rock_block", NetherrackRockBlockBlock::new);
		END_STONE_ROCK_BLOCK = REGISTRY.register("end_stone_rock_block", EndStoneRockBlockBlock::new);
		BLACKSTONE_ROCK_BLOCK = REGISTRY.register("blackstone_rock_block", BlackstoneRockBlockBlock::new);
		BASALT_ROCK_BLOCK = REGISTRY.register("basalt_rock_block", BasaltRockBlockBlock::new);
		DEEPSLATE_ROCK_BLOCK = REGISTRY.register("deepslate_rock_block", DeepslateRockBlockBlock::new);
		BLOCK_OF_RAW_TIN = REGISTRY.register("block_of_raw_tin", BlockOfRawTinBlock::new);
		BLOCK_OF_TIN = REGISTRY.register("block_of_tin", BlockOfTinBlock::new);
		COW_CARCASS = REGISTRY.register("cow_carcass", CowCarcassBlock::new);
		COW_LEG = REGISTRY.register("cow_leg", CowLegBlock::new);
		COW_HEAD = REGISTRY.register("cow_head", CowHeadBlock::new);
		SAND_SALT_DEPOSIT = REGISTRY.register("sand_salt_deposit", SandSaltDepositBlock::new);
		SHEEP_CARCASS = REGISTRY.register("sheep_carcass", SheepCarcassBlock::new);
		SHEEP_LEG = REGISTRY.register("sheep_leg", SheepLegBlock::new);
		SHEEP_HEAD = REGISTRY.register("sheep_head", SheepHeadBlock::new);
		CHICKEN_CARCASS = REGISTRY.register("chicken_carcass", ChickenCarcassBlock::new);
		PIG_CARCASS = REGISTRY.register("pig_carcass", PigCarcassBlock::new);
		PIG_HEAD = REGISTRY.register("pig_head", PigHeadBlock::new);
		PIG_LEG = REGISTRY.register("pig_leg", PigLegBlock::new);
		KNIFE_BLADE_MOLD = REGISTRY.register("knife_blade_mold", KnifeBladeMoldBlock::new);
		CLAY_KNIFE_MOLD = REGISTRY.register("clay_knife_mold", ClayKnifeMoldBlock::new);
		MANGANESE_ORE = REGISTRY.register("manganese_ore", ManganeseOreBlock::new);
		DEEPSLATE_MANGANESE_ORE = REGISTRY.register("deepslate_manganese_ore", DeepslateManganeseOreBlock::new);
		BLOCK_OF_STEEL = REGISTRY.register("block_of_steel", BlockOfSteelBlock::new);
		BLOCK_OF_MANGANESE = REGISTRY.register("block_of_manganese", BlockOfManganeseBlock::new);
		BLOCK_OF_RAW_MANGANESE = REGISTRY.register("block_of_raw_manganese", BlockOfRawManganeseBlock::new);
		BLOCK_OF_RAW_REDSTONE = REGISTRY.register("block_of_raw_redstone", BlockOfRawRedstoneBlock::new);
		MINERAL_PROCESSING_TABLE = REGISTRY.register("mineral_processing_table", MineralProcessingTableBlock::new);
		EMBEDDED_OBSIDIAN = REGISTRY.register("embedded_obsidian", EmbeddedObsidianBlock::new);
		COPPER_ROCK_BLOCK = REGISTRY.register("copper_rock_block", CopperRockBlockBlock::new);
		APPLE_OAK_LEAVES = REGISTRY.register("apple_oak_leaves", AppleOakLeavesBlock::new);
		APPLE_TREE_SAPLING = REGISTRY.register("apple_tree_sapling", AppleTreeSaplingBlock::new);
		APPLE = REGISTRY.register("apple", AppleBlock::new);
		INGOT_MOLD = REGISTRY.register("ingot_mold", IngotMoldBlock::new);
		INGOT_CLAY_MOLD = REGISTRY.register("ingot_clay_mold", IngotClayMoldBlock::new);
		HEMP = REGISTRY.register("hemp", HempBlock::new);
		LIMESTONE_ROCK = REGISTRY.register("limestone_rock", LimestoneRockBlock::new);
		VERIDIUM_ROCK = REGISTRY.register("veridium_rock", VeridiumRockBlock::new);
		OCHRUM_ROCK = REGISTRY.register("ochrum_rock", OchrumRockBlock::new);
		CRIMSITE_ROCK = REGISTRY.register("crimsite_rock", CrimsiteBlockBlock::new);
		SCORCHIA_ROCK = REGISTRY.register("scorchia_rock", ScorchiaRockBlock::new);
		ASURINE_CRYSTAL = REGISTRY.register("asurine_crystal", AsurineCrystalBlock::new);
		SCORIA_ROCK = REGISTRY.register("scoria_rock", ScoriaRockBlock::new);
		SHALE = REGISTRY.register("shale", ShaleBlock::new);
		SHALE_ROCK = REGISTRY.register("shale_rock", ShaleRockBlock::new);
		TITANIUM_ORE = REGISTRY.register("titanium_ore", TitaniumOreBlock::new);
		DEEPSLATE_TITANIUM_ORE = REGISTRY.register("deepslate_titanium_ore", DeepslateTitaniumOreBlock::new);
		SHALE_TITANIUM_ORE = REGISTRY.register("shale_titanium_ore", ShaleTitaniumOreBlock::new);
		BLOCK_OF_TITANIUM = REGISTRY.register("block_of_titanium", BlockOfTitaniumBlock::new);
		BLOCK_OF_RAW_TITANIUM = REGISTRY.register("block_of_raw_titanium", BlockOfRawTitaniumBlock::new);
		RADIANT_LOG = REGISTRY.register("radiant_log", RadiantLogBlock::new);
		STRIPPED_RADIANT_LOG = REGISTRY.register("stripped_radiant_log", StrippedRadiantLogBlock::new);
		RADIANT_PLANKS = REGISTRY.register("radiant_planks", RadiantPlanksBlock::new);
		RADIATED_LEAVES = REGISTRY.register("radiated_leaves", RadiatedLeavesBlock::new);
		RADIATED_SAPLING = REGISTRY.register("radiated_sapling", RadiatedSaplingBlock::new);
		RADIATED_STAIRS = REGISTRY.register("radiated_stairs", RadiatedStairsBlock::new);
		RADIATED_SLAB = REGISTRY.register("radiated_slab", RadiatedSlabBlock::new);
		RADIATED_FENCE = REGISTRY.register("radiated_fence", RadiatedFenceBlock::new);
		RADIATED_FENCE_GATE = REGISTRY.register("radiated_fence_gate", RadiatedFenceGateBlock::new);
		RADIATED_PRESSURE_PLATE = REGISTRY.register("radiated_pressure_plate", RadiatedPressurePlateBlock::new);
		RADIATED_BUTTON = REGISTRY.register("radiated_button", RadiatedButtonBlock::new);
		RADIATED_SHALE = REGISTRY.register("radiated_shale", RadiatedGrassBlock::new);
		THIN_RADIATED_VINES = REGISTRY.register("thin_radiated_vines", ThinRadiatedVinesBlock::new);
		THIN_RADIATED_VINE_BASE = REGISTRY.register("thin_radiated_vine_base", ThinRadiatedVineBaseBlock::new);
		RADIATED_MOSS = REGISTRY.register("radiated_moss", RadiatedMossBlock::new);
		RADIATED_TALL_GRASS = REGISTRY.register("radiated_tall_grass", RadiatedTallGrassBlock::new);
		THICK_RADIATED_VINES = REGISTRY.register("thick_radiated_vines", ThickRadiatedVinesBlock::new);
		THICK_RADIATED_VINES_BASE = REGISTRY.register("thick_radiated_vines_base", ThickRadiatedVinesBaseBlock::new);
		RADIATED_ORCHID = REGISTRY.register("radiated_orchid", RadiatedOrchidBlock::new);
		SHALE_URANINITE_ORE = REGISTRY.register("shale_uraninite_ore", ShaleUraniumOreBlock::new);
		URANINITE_ORE = REGISTRY.register("uraninite_ore", UraniumOreBlock::new);
		DEEPSLATE_URANINITE_ORE = REGISTRY.register("deepslate_uraninite_ore", DeepslateUraniumOreBlock::new);
		BLOCK_OF_RAW_URANINITE = REGISTRY.register("block_of_raw_uraninite", BlockOfRawUraniniteBlock::new);
		POLISHED_SHALE = REGISTRY.register("polished_shale", PolishedShaleBlock::new);
		POLISHED_SHALE_BRICKS = REGISTRY.register("polished_shale_bricks", PolishedShaleBricksBlock::new);
		POLISHED_CHISELED_SHALE = REGISTRY.register("polished_chiseled_shale", PolishedChiseledShaleBlock::new);
		POLISHED_SHALE_STAIRS = REGISTRY.register("polished_shale_stairs", PolishedShaleStairsBlock::new);
		POLISHED_SHALE_BRICK_STAIRS = REGISTRY.register("polished_shale_brick_stairs", PolishedShaleBrickStairsBlock::new);
		POLISHED_SHALE_SLAB = REGISTRY.register("polished_shale_slab", PolishedShaleSlabBlock::new);
		POLISHED_SHALE_BRICK_SLAB = REGISTRY.register("polished_shale_brick_slab", PolishedShaleBrickSlabBlock::new);
		POLISHED_SHALE_WALL = REGISTRY.register("polished_shale_wall", PolishedShaleWallBlock::new);
		POLOSHED_SHALE_BRICK_WALL = REGISTRY.register("poloshed_shale_brick_wall", PoloshedShaleBrickWallBlock::new);
		SHALE_STAIRS = REGISTRY.register("shale_stairs", ShaleStairsBlock::new);
		SHALE_SLAB = REGISTRY.register("shale_slab", ShaleSlabBlock::new);
		SHALE_WALL = REGISTRY.register("shale_wall", ShaleWallBlock::new);
		BLOCK_OF_URANIUM = REGISTRY.register("block_of_uranium", BlockOfUraniumBlock::new);
		URANIUM_ROD = REGISTRY.register("uranium_rod", UraniumRodBlock::new);
		RADIANT_TRAPDOOR = REGISTRY.register("radiant_trapdoor", RadiantTrapdoorBlock::new);
		RADIANT_DOOR = REGISTRY.register("radiant_door", RadiantDoorBlock::new);
		STEEL_DOOR = REGISTRY.register("steel_door", SteelDoorBlock::new);
		STEEL_TRAPDOOR = REGISTRY.register("steel_trapdoor", SteelTrapdoorBlock::new);
		TURANITE_BLOCK = REGISTRY.register("turanite_block", TuraniteBlockBlock::new);
		ADVANCED_ALLOY_FORGE = REGISTRY.register("advanced_alloy_forge", AdvancedAlloyForgeBlock::new);
		PLATED_DIAMOND_BLOCK = REGISTRY.register("plated_diamond_block", PlatedDiamondBlockBlock::new);
		NETHERITE_SCRAP_BLOCK = REGISTRY.register("netherite_scrap_block", NetheriteScrapBlockBlock::new);
		SILVER_ORE = REGISTRY.register("silver_ore", SilverOreBlock::new);
		RAW_SILVER_BLOCK = REGISTRY.register("raw_silver_block", RawSilverBlockBlock::new);
		SILVER_BLOCK = REGISTRY.register("silver_block", SilverBlockBlock::new);
		SAPPHIRE_ORE = REGISTRY.register("sapphire_ore", SapphireOreBlock::new);
		DEEPSLATE_SAPPHIRE_ORE = REGISTRY.register("deepslate_sapphire_ore", DeepslateSapphireOreBlock::new);
		SAPPHIRE_BLOCK = REGISTRY.register("sapphire_block", SapphireBlockBlock::new);
		NITRE_BLOCK = REGISTRY.register("nitre_block", NitreBlockBlock::new);
		RUNE_CLAY_MOLD = REGISTRY.register("rune_clay_mold", RuneClayMoldBlock::new);
		RUNE_MOLD = REGISTRY.register("rune_mold", RuneMoldBlock::new);
		RUNE_MAGIC_INFUSER = REGISTRY.register("rune_magic_infuser", RuneMagicInfuserBlock::new);
		RUBY_ORE = REGISTRY.register("ruby_ore", RubyOreBlock::new);
		DEEPSLATE_RUBY_ORE = REGISTRY.register("deepslate_ruby_ore", DeepslateRubyOreBlock::new);
		BLOCK_OF_RUBY = REGISTRY.register("block_of_ruby", BlockOfRubyBlock::new);
		AMBER_ORE = REGISTRY.register("amber_ore", AmberOreBlock::new);
		DEEPSLATE_AMBER_ORE = REGISTRY.register("deepslate_amber_ore", DeepslateAmberOreBlock::new);
		BLOCK_OF_AMBER = REGISTRY.register("block_of_amber", BlockOfAmberBlock::new);
		WISTERIA_LOG = REGISTRY.register("wisteria_log", WisteriaLogBlock::new);
		WISTERIA_LEAVES = REGISTRY.register("wisteria_leaves", WisteriaLeavesBlock::new);
		FLOWING_WISTERIA_LEAVES = REGISTRY.register("flowing_wisteria_leaves", FlowingWisteriaLeavesBlock::new);
		WISTERIA_SPIDER_LILY = REGISTRY.register("wisteria_spider_lily", WisteriaSpiderLilyBlock::new);
		WISTERIA_SAPLING = REGISTRY.register("wisteria_sapling", WisteriaSaplingBlock::new);
		WISTERIA_LEAF_LITTER = REGISTRY.register("wisteria_leaf_litter", WisteriaLeafLitterBlock::new);
		WISTERIA_FLOWER_UPPER = REGISTRY.register("wisteria_flower_upper", WisteriaFlowerUpperBlock::new);
		WISTERIA_FLOWER_LOWER = REGISTRY.register("wisteria_flower_lower", WisteriaFlowerLowerBlock::new);
		DEEPSLATE_TIN_ORE = REGISTRY.register("deepslate_tin_ore", DeepslateTinOreBlock::new);
		OBSIDIAN_ROCK = REGISTRY.register("obsidian_rock", ObsidianRockBlockBlock::new);
		HEMATITE_ORE = REGISTRY.register("hematite_ore", HematiteOreBlock::new);
		DEEPSLATE_HEMATITE_ORE = REGISTRY.register("deepslate_hematite_ore", DeepslateHematiteOreBlock::new);
		BASALT_HEMATITE_ORE = REGISTRY.register("basalt_hematite_ore", BasaltHematiteOreBlock::new);
		HEMATITE_BLOCK = REGISTRY.register("hematite_block", HematiteBlockBlock::new);
		MAGNETITE_ORE = REGISTRY.register("magnetite_ore", MagnetiteOreBlock::new);
		DEEPSLATE_MAGNETITE_ORE = REGISTRY.register("deepslate_magnetite_ore", DeepslateMagnetiteOreBlock::new);
		BASALT_MAGNETITE_ORE = REGISTRY.register("basalt_magnetite_ore", BasaltMagenetiteOreBlock::new);
		MAGNETITE_BLOCK = REGISTRY.register("magnetite_block", MagnetiteBlockBlock::new);
		MALACHITE_ORE = REGISTRY.register("malachite_ore", MalachiteOreBlock::new);
		DEEPSLATE_MALACHITE_ORE = REGISTRY.register("deepslate_malachite_ore", DeepslateMalachiteOreBlock::new);
		RAW_MALACHITE_BLOCK = REGISTRY.register("raw_malachite_block", RawMalachiteBlockBlock::new);
		AZURITE_ORE = REGISTRY.register("azurite_ore", AzuriteOreBlock::new);
		DEEPSLATE_AZURITE_ORE = REGISTRY.register("deepslate_azurite_ore", DeepslateAzuriteOreBlock::new);
		RAW_AZURITE_BLOCK = REGISTRY.register("raw_azurite_block", RawAzuriteBlockBlock::new);
		CASSITERITE_ORE = REGISTRY.register("cassiterite_ore", CassiteriteOreBlock::new);
		DEEPSLATE_CASSITERITE_ORE = REGISTRY.register("deepslate_cassiterite_ore", DeepslateCassiteriteOreBlock::new);
		RAW_CASSITERITE_BLOCK = REGISTRY.register("raw_cassiterite_block", RawCassiteriteBlockBlock::new);
		DEEPSLATE_SILVER_ORE = REGISTRY.register("deepslate_silver_ore", DeepslateNativeSilverOreBlock::new);
		ARGENTITE_ORE = REGISTRY.register("argentite_ore", ArgentiteOreBlock::new);
		DEEPSLATE_ARGENTITE_ORE = REGISTRY.register("deepslate_argentite_ore", DeepslateArgentiteOreBlock::new);
		BASALT_ARGENTITE_ORE = REGISTRY.register("basalt_argentite_ore", BasaltArgentiteOreBlock::new);
		ARGENTITE_BLOCK = REGISTRY.register("argentite_block", ArgentiteBlockBlock::new);
		BASALT_URANINITE_ORE = REGISTRY.register("basalt_uraninite_ore", BasaltUraniniteOreBlock::new);
		CALAVERITE_ORE = REGISTRY.register("calaverite_ore", CalaveriteOreBlock::new);
		DEEPSLATE_CALAVERITE_ORE = REGISTRY.register("deepslate_calaverite_ore", DeepslateCalaveriteOreBlock::new);
		BASALT_CALAVERITE_ORE = REGISTRY.register("basalt_calaverite_ore", BasaltCalaveriteOreBlock::new);
		CALAVERITE_BLOCK = REGISTRY.register("calaverite_block", CalaveriteBlockBlock::new);
		MANGANITE_ORE = REGISTRY.register("manganite_ore", ManganiteOreBlock::new);
		DEEPSLATE_MANGANITE_ORE = REGISTRY.register("deepslate_manganite_ore", DeepslateManganiteOreBlock::new);
		BASALT_MANGANITE_ORE = REGISTRY.register("basalt_manganite_ore", BasaltManganiteOreBlock::new);
		MANGANITE_BLOCK = REGISTRY.register("manganite_block", ManganiteBlockBlock::new);
		PYROLUSITE_ORE = REGISTRY.register("pyrolusite_ore", PyrolusiteOreBlock::new);
		PYROLUSITE_BLOCK = REGISTRY.register("pyrolusite_block", PyrolusiteBlockBlock::new);
		DEEPSLATE_PYROLUSITE_ORE = REGISTRY.register("deepslate_pyrolusite_ore", DeepslatePyrolusiteOreBlock::new);
		URANOPHANE_ORE = REGISTRY.register("uranophane_ore", UranophaneOreBlock::new);
		DEEPSLATE_URANOPHANE_ORE = REGISTRY.register("deepslate_uranophane_ore", DeepslateUranophaneOreBlock::new);
		BASALT_URANOPHANE_ORE = REGISTRY.register("basalt_uranophane_ore", BasaltUranophaneOreBlock::new);
		SHALE_URANOPHANE_ORE = REGISTRY.register("shale_uranophane_ore", ShaleUranophaneOreBlock::new);
		URANOPHANE_BLOCK = REGISTRY.register("uranophane_block", UranophaneBlockBlock::new);
		ILMENITE_ORE = REGISTRY.register("ilmenite_ore", IlmeniteOreBlock::new);
		DEEPSLATE_ILMENITE_ORE = REGISTRY.register("deepslate_ilmenite_ore", DeepslateIlmeniteOreBlock::new);
		BASALT_ILMENITE_ORE = REGISTRY.register("basalt_ilmenite_ore", BasaltIlmeniteOreBlock::new);
		ILMENITE_BLOCK = REGISTRY.register("ilmenite_block", IlmeniteBlockBlock::new);
		KIMBERLITE_ROCK = REGISTRY.register("kimberlite_rock", KimberliteRockBlock::new);
		KIMBERLITE = REGISTRY.register("kimberlite", KimberliteBlock::new);
		KIMBERLITE_STALAGMITE_TOP = REGISTRY.register("kimberlite_stalagmite_top", KimberliteStalagmiteTopBlock::new);
		KIMBERLITE_STALAGMITE_MIDDLE = REGISTRY.register("kimberlite_stalagmite_middle", KimberliteStalagmiteMiddleBlock::new);
		KIMBERLITE_STALAGMITE_BASE = REGISTRY.register("kimberlite_stalagmite_base", KimberliteStalagmiteBaseBlock::new);
		KIMBERLITE_STALAGTITE_TIP = REGISTRY.register("kimberlite_stalagtite_tip", KimberliteStalagtiteTipBlock::new);
		KIMBERLITE_STALAGTITE_MIDDLE = REGISTRY.register("kimberlite_stalagtite_middle", KimberliteStalagtiteMiddleBlock::new);
		KIMBERLITE_STALAGTITE_BASE = REGISTRY.register("kimberlite_stalagtite_base", KimberliteStalagtiteBaseBlock::new);
		DEEPSLATE_STALAGMITE_TOP = REGISTRY.register("deepslate_stalagmite_top", DeepslateStalagmiteTopBlock::new);
		DEEPSLATE_STALAGMITE_MIDDLE = REGISTRY.register("deepslate_stalagmite_middle", DeepslateStalagmiteMiddleBlock::new);
		DEEPSLATE_STALAGMITE_BASE = REGISTRY.register("deepslate_stalagmite_base", DeepslateStalagmiteBaseBlock::new);
		DEEPSLATE_STALAGTITE_TIP = REGISTRY.register("deepslate_stalagtite_tip", DeepslateStalagtiteTipBlock::new);
		DEEPSLATE_STALAGTITE_MIDDLE = REGISTRY.register("deepslate_stalagtite_middle", DeepslateStalagtiteMiddleBlock::new);
		DEEPSLATE_STALAGTITE_BASE = REGISTRY.register("deepslate_stalagtite_base", DeepslateStalagtiteBaseBlock::new);
		STONE_STALAGMITE_TOP = REGISTRY.register("stone_stalagmite_top", StoneStalagmiteTopBlock::new);
		STONE_STALAGMITE_MIDDLE = REGISTRY.register("stone_stalagmite_middle", StoneStalagmiteMiddleBlock::new);
		STONE_STALAGMITE_BASE = REGISTRY.register("stone_stalagmite_base", StoneStalagmiteBaseBlock::new);
		STONE_STALAGTITE_TIP = REGISTRY.register("stone_stalagtite_tip", StoneStalagtiteTipBlock::new);
		STONE_STALAGTITE_MIDDLE = REGISTRY.register("stone_stalagtite_middle", StoneStalagtiteMiddleBlock::new);
		STONE_STALAGTITE_BASE = REGISTRY.register("stone_stalagtite_base", StoneStalagtiteBaseBlock::new);
		BASALT_STALAGMITE_TOP = REGISTRY.register("basalt_stalagmite_top", BasaltStalagmiteTopBlock::new);
		BASALT_STALAGMITE_MIDDLE = REGISTRY.register("basalt_stalagmite_middle", BasaltStalagmiteMiddleBlock::new);
		BASALT_STALAGMITE_BASE = REGISTRY.register("basalt_stalagmite_base", BasaltStalagmiteBaseBlock::new);
		BASALT_STALAGTITE_TIP = REGISTRY.register("basalt_stalagtite_tip", BasaltStalagtiteTipBlock::new);
		BASALT_STALAGTITE_MIDDLE = REGISTRY.register("basalt_stalagtite_middle", BasaltStalagtiteMiddleBlock::new);
		BASALT_STALAGTITE_BASE = REGISTRY.register("basalt_stalagtite_base", BasaltStalagtiteBaseBlock::new);
		BASALT_SAPPHIRE_ORE = REGISTRY.register("basalt_sapphire_ore", BasaltSapphireOreBlock::new);
		KIMBERLITE_SAPPHIRE_ORE = REGISTRY.register("kimberlite_sapphire_ore", KimberliteSapphireOreBlock::new);
		BASALT_DIAMOND_ORE = REGISTRY.register("basalt_diamond_ore", BasaltDiamondOreBlock::new);
		KIMBERLITE_DIAMOND_ORE = REGISTRY.register("kimberlite_diamond_ore", KimberliteDiamondOreBlock::new);
		BASALT_EMERALD_ORE = REGISTRY.register("basalt_emerald_ore", BasaltEmeraldOreBlock::new);
		KIMBERLITE_EMERALD_ORE = REGISTRY.register("kimberlite_emerald_ore", KimberliteEmeraldOreBlock::new);
		BASALT_RUBY_ORE = REGISTRY.register("basalt_ruby_ore", BasaltRubyOreBlock::new);
		KIMBERLITE_RUBY_ORE = REGISTRY.register("kimberlite_ruby_ore", KimberliteRubyOreBlock::new);
		BASALT_LAPIS_ORE = REGISTRY.register("basalt_lapis_ore", BasaltLazuriteOreBlock::new);
		KIMBERLITE_LAPIS_ORE = REGISTRY.register("kimberlite_lapis_ore", KimberliteLapisOreBlock::new);
		BASALT_AMBER_ORE = REGISTRY.register("basalt_amber_ore", BasaltAmberOreBlock::new);
		KIMBERLITE_AMBER_ORE = REGISTRY.register("kimberlite_amber_ore", KimberliteAmberOreBlock::new);
		SULFUR_ORE = REGISTRY.register("sulfur_ore", SulfurOreBlock::new);
		NITRE_POWDER = REGISTRY.register("nitre_powder", NitrePowderBlock::new);
		STRIPPED_WISTERIA_LOG = REGISTRY.register("stripped_wisteria_log", StrippedWisteriaLogBlock::new);
		WISTERIA_WOOD = REGISTRY.register("wisteria_wood", WisteriaWoodBlock::new);
		WISTERIA_PLANKS = REGISTRY.register("wisteria_planks", WisteriaPlanksBlock::new);
		WISTERIA_STAIRS = REGISTRY.register("wisteria_stairs", WisteriaStairsBlock::new);
		WISTERIA_SLAB = REGISTRY.register("wisteria_slab", WisteriaSlabBlock::new);
		WISTERIA_FENCE = REGISTRY.register("wisteria_fence", WisteriaFenceBlock::new);
		WISTERIA_FENCE_GATE = REGISTRY.register("wisteria_fence_gate", WisteriaFenceGateBlock::new);
		WISTERIA_DOOR = REGISTRY.register("wisteria_door", WisteriaDoorBlock::new);
		WISTERIA_TRAPDOOR = REGISTRY.register("wisteria_trapdoor", WisteriaTrapdoorBlock::new);
		WISTERIA_BUTTON = REGISTRY.register("wisteria_button", WisteriaButtonBlock::new);
		WISTERIA_PRESSURE_PLATE = REGISTRY.register("wisteria_pressure_plate", WisteriaPressurePlateBlock::new);
		PURE_SALT_BLOCK = REGISTRY.register("pure_salt_block", PureSaltBlockBlock::new);
		SALT_DEPOSIT = REGISTRY.register("salt_deposit", SaltDepositBlock::new);
	}

	// Start of user code block custom blocks
	// End of user code block custom blocks
	@EventBusSubscriber(Dist.CLIENT)
	public static class BlocksClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			AppleOakLeavesBlock.blockColorLoad(event);
		}

		@SubscribeEvent
		public static void itemColorLoad(RegisterColorHandlersEvent.Item event) {
			AppleOakLeavesBlock.itemColorLoad(event);
		}
	}
}