/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.survivalreimagined.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.survivalreimagined.item.inventory.BackpackInventoryCapability;
import net.mcreator.survivalreimagined.item.inventory.AAFScriptureInventoryCapability;
import net.mcreator.survivalreimagined.item.*;
import net.mcreator.survivalreimagined.SurvivalReimaginedMod;

@EventBusSubscriber
public class SurvivalReimaginedModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(SurvivalReimaginedMod.MODID);
	public static final DeferredItem<Item> FLINTBLOCK;
	public static final DeferredItem<Item> FLINT_TOOL;
	public static final DeferredItem<Item> LARGE_OAK_BARK;
	public static final DeferredItem<Item> LARGE_DARK_OAK_BARK;
	public static final DeferredItem<Item> LARGE_SPRUCE_BARK;
	public static final DeferredItem<Item> LARGE_BIRCH_BARK;
	public static final DeferredItem<Item> LARGE_MANGROVE_BARK;
	public static final DeferredItem<Item> LARGE_CHERRY_BARK;
	public static final DeferredItem<Item> LARGE_ACACIA_BARK;
	public static final DeferredItem<Item> LARGE_JUNGLE_BARK;
	public static final DeferredItem<Item> LARGE_CRIMSON_BARK;
	public static final DeferredItem<Item> LARGE_WARPED_BARK;
	public static final DeferredItem<Item> STONE_ROCK;
	public static final DeferredItem<Item> STONE_ROCK_BLOC;
	public static final DeferredItem<Item> HEMP_FIBER;
	public static final DeferredItem<Item> COPPER_CHUNK;
	public static final DeferredItem<Item> COPPER_NUGGET;
	public static final DeferredItem<Item> COPPER_CHISEL;
	public static final DeferredItem<Item> SMALL_COAL_CHUNK;
	public static final DeferredItem<Item> TIN_ORE;
	public static final DeferredItem<Item> RAW_TIN;
	public static final DeferredItem<Item> TIN_INGOT;
	public static final DeferredItem<Item> TIN_NUGGET;
	public static final DeferredItem<Item> DEEPSLATE_ROCK;
	public static final DeferredItem<Item> FORGE;
	public static final DeferredItem<Item> BRONZE_INGOT;
	public static final DeferredItem<Item> ROUGH_BRONZE;
	public static final DeferredItem<Item> ROUGH_IRON;
	public static final DeferredItem<Item> ROUGH_GOLD;
	public static final DeferredItem<Item> ROUGH_COPPER;
	public static final DeferredItem<Item> ROUGH_TIN;
	public static final DeferredItem<Item> STONE_HAMMER;
	public static final DeferredItem<Item> METAL_REFINING_TABLE;
	public static final DeferredItem<Item> OAK_PLANK;
	public static final DeferredItem<Item> DARK_OAK_PLANK;
	public static final DeferredItem<Item> SPRUCE_PLANK;
	public static final DeferredItem<Item> BIRCH_PLANK;
	public static final DeferredItem<Item> ACACIA_PLANK;
	public static final DeferredItem<Item> JUNGLE_PLANK;
	public static final DeferredItem<Item> CHERRY_PLANK;
	public static final DeferredItem<Item> MANGROVE_PLANK;
	public static final DeferredItem<Item> CRIMSON_PLANK;
	public static final DeferredItem<Item> WARPED_PLANK;
	public static final DeferredItem<Item> STONE_SAW;
	public static final DeferredItem<Item> CLAY_BRICK;
	public static final DeferredItem<Item> CLAY_CRUCIBLE;
	public static final DeferredItem<Item> CRUCIBLE;
	public static final DeferredItem<Item> BRONZE_PICKAXE;
	public static final DeferredItem<Item> BRONZE_AXE;
	public static final DeferredItem<Item> BRONZE_SWORD;
	public static final DeferredItem<Item> BRONZE_SHOVEL;
	public static final DeferredItem<Item> BRONZE_HOE;
	public static final DeferredItem<Item> COPPER_HANDLE;
	public static final DeferredItem<Item> AXE_HEAD_MOLD;
	public static final DeferredItem<Item> PICKAXE_HEAD_MOLD;
	public static final DeferredItem<Item> SWORD_BLADE_MOLD;
	public static final DeferredItem<Item> HOE_HEAD_MOLD;
	public static final DeferredItem<Item> SHOVEL_HEAD_MOLD;
	public static final DeferredItem<Item> SAW_BLADE_MOLD;
	public static final DeferredItem<Item> HAMMER_HEAD_MOLD;
	public static final DeferredItem<Item> HELMET_MOLD;
	public static final DeferredItem<Item> CHESTPLATE_MOLD;
	public static final DeferredItem<Item> LEGGING_MOLD;
	public static final DeferredItem<Item> BOOTS_MOLD;
	public static final DeferredItem<Item> CLAY_SWORD_BLADE_MOLD;
	public static final DeferredItem<Item> CLAY_PICKAXE_HEAD_MOLD;
	public static final DeferredItem<Item> CLAY_AXE_HEAD_MOLD;
	public static final DeferredItem<Item> CLAY_SHOVEL_HEAD_MOLD;
	public static final DeferredItem<Item> CLAY_HOE_BLADE_MOLD;
	public static final DeferredItem<Item> CLAY_HAMMER_HEAD_MOLD;
	public static final DeferredItem<Item> CLAY_SAW_BLADE_MOLD;
	public static final DeferredItem<Item> CLAY_HELMET_MOLD;
	public static final DeferredItem<Item> CLAY_CHESTPLATE_MOLD;
	public static final DeferredItem<Item> CLAY_LEGGINGS_MOLD;
	public static final DeferredItem<Item> CLAY_BOOTS_MOLD;
	public static final DeferredItem<Item> BRONZE_ARMOR_HELMET;
	public static final DeferredItem<Item> BRONZE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> BRONZE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> BRONZE_ARMOR_BOOTS;
	public static final DeferredItem<Item> BRONZE_SAW;
	public static final DeferredItem<Item> BRONZE_HAMMER;
	public static final DeferredItem<Item> BRONZE_PICKAXE_HEAD;
	public static final DeferredItem<Item> BRONZE_AXE_HEAD;
	public static final DeferredItem<Item> BRONZE_SWORD_BLADE;
	public static final DeferredItem<Item> BRONZE_HOE_BLADE;
	public static final DeferredItem<Item> BRONZE_SHOVEL_HEAD;
	public static final DeferredItem<Item> BRONZE_HAMMER_HEAD;
	public static final DeferredItem<Item> BRONZE_SAW_BLADE;
	public static final DeferredItem<Item> WOODEN_SAW;
	public static final DeferredItem<Item> WOODEN_HAMMER;
	public static final DeferredItem<Item> WOODEN_HELMET;
	public static final DeferredItem<Item> WOODEN_CHESTPLATE;
	public static final DeferredItem<Item> WOODEN_LEGGINGS;
	public static final DeferredItem<Item> WOODEN_BOOTS;
	public static final DeferredItem<Item> IRON_CHUNK;
	public static final DeferredItem<Item> BLOCK_OF_BRONZE;
	public static final DeferredItem<Item> TIN_CHUNK;
	public static final DeferredItem<Item> HEART;
	public static final DeferredItem<Item> ANDESITE_ROCK;
	public static final DeferredItem<Item> ANDESITE_ROCK_BLOCK;
	public static final DeferredItem<Item> GRANITE_ROCK;
	public static final DeferredItem<Item> GRANITE_ROCK_BLOCK;
	public static final DeferredItem<Item> DIORITE_ROCK_B_LOCK;
	public static final DeferredItem<Item> DIORITE_ROCK;
	public static final DeferredItem<Item> DRIPSTONE_ROCK;
	public static final DeferredItem<Item> DRIPSTONE_ROCK_BLOCK;
	public static final DeferredItem<Item> CALCITE_ROCK;
	public static final DeferredItem<Item> CALCITE_ROCK_BLOCK;
	public static final DeferredItem<Item> TUFF_ROCK;
	public static final DeferredItem<Item> TUFF_ROCK_BLOCK;
	public static final DeferredItem<Item> MOSSY_STONE_ROCK;
	public static final DeferredItem<Item> MOSSY_STONE_ROCK_BLOCK;
	public static final DeferredItem<Item> NETHERRACK_ROCK;
	public static final DeferredItem<Item> NETHERRACK_ROCK_BLOCK;
	public static final DeferredItem<Item> END_STONE_ROCK;
	public static final DeferredItem<Item> END_STONE_ROCK_BLOCK;
	public static final DeferredItem<Item> BLACKSTONE_ROCK;
	public static final DeferredItem<Item> BLACKSTONE_ROCK_BLOCK;
	public static final DeferredItem<Item> BASALT_ROCK;
	public static final DeferredItem<Item> BASALT_ROCK_BLOCK;
	public static final DeferredItem<Item> DEEPSLATE_ROCK_BLOCK;
	public static final DeferredItem<Item> BOAT_PADDLES;
	public static final DeferredItem<Item> BLOCK_OF_RAW_TIN;
	public static final DeferredItem<Item> BLOCK_OF_TIN;
	public static final DeferredItem<Item> COW_CARCASS;
	public static final DeferredItem<Item> STONE_KNIFE;
	public static final DeferredItem<Item> COW_HIDE;
	public static final DeferredItem<Item> COW_LEG;
	public static final DeferredItem<Item> COW_HEAD;
	public static final DeferredItem<Item> BRAIN;
	public static final DeferredItem<Item> HEART_ITEM;
	public static final DeferredItem<Item> INTESTINES;
	public static final DeferredItem<Item> STOMACH;
	public static final DeferredItem<Item> LIVER;
	public static final DeferredItem<Item> LUNGS;
	public static final DeferredItem<Item> COOKED_BRAIN;
	public static final DeferredItem<Item> COOKED_HEART;
	public static final DeferredItem<Item> COOKED_INTESTINES;
	public static final DeferredItem<Item> COOKED_LIVER;
	public static final DeferredItem<Item> COOKED_STOMACH;
	public static final DeferredItem<Item> COOKED_LUNGS;
	public static final DeferredItem<Item> SPOILED_BRAIN;
	public static final DeferredItem<Item> SPOILED_HEART;
	public static final DeferredItem<Item> SPOILED_INTESTINES;
	public static final DeferredItem<Item> SPOILED_LIVER;
	public static final DeferredItem<Item> SPOILED_LUNGS;
	public static final DeferredItem<Item> SPOILED_STOMACH;
	public static final DeferredItem<Item> SPOILED_COD;
	public static final DeferredItem<Item> SPOILED_SALMAN;
	public static final DeferredItem<Item> SPOILED_CHICKEN;
	public static final DeferredItem<Item> SPOILED_RABBIT;
	public static final DeferredItem<Item> SPOILED_MUTTON;
	public static final DeferredItem<Item> SPOILED_PORKCHOP;
	public static final DeferredItem<Item> SPOILED_BEEF;
	public static final DeferredItem<Item> SALT;
	public static final DeferredItem<Item> CURED_STEAK;
	public static final DeferredItem<Item> CURED_PORKCHOP;
	public static final DeferredItem<Item> CURED_CHICKEN;
	public static final DeferredItem<Item> CURED_RABBIT;
	public static final DeferredItem<Item> CURED_MUTTON;
	public static final DeferredItem<Item> CURED_HEART;
	public static final DeferredItem<Item> CURED_INTESTINES;
	public static final DeferredItem<Item> CURED_BRAIN;
	public static final DeferredItem<Item> CURED_LIVER;
	public static final DeferredItem<Item> CURED_STOMACH;
	public static final DeferredItem<Item> CURED_LUNGS;
	public static final DeferredItem<Item> SAND_SALT_DEPOSIT;
	public static final DeferredItem<Item> SHEEP_CARCASS;
	public static final DeferredItem<Item> SHEEP_HIDE;
	public static final DeferredItem<Item> SHEEP_LEG;
	public static final DeferredItem<Item> SHEEP_HEAD;
	public static final DeferredItem<Item> CHICKEN_CARCASS;
	public static final DeferredItem<Item> PIG_CARCASS;
	public static final DeferredItem<Item> PIG_HEAD;
	public static final DeferredItem<Item> PIG_LEG;
	public static final DeferredItem<Item> BRONZE_KNIFE;
	public static final DeferredItem<Item> BRONZE_KNIFE_BLADE;
	public static final DeferredItem<Item> WOODEN_KNIFE;
	public static final DeferredItem<Item> SMALL_STICK;
	public static final DeferredItem<Item> KNIFE_BLADE_MOLD;
	public static final DeferredItem<Item> CLAY_KNIFE_MOLD;
	public static final DeferredItem<Item> SMALL_COPPER_HANDLE;
	public static final DeferredItem<Item> ROUGH_MANGANESE;
	public static final DeferredItem<Item> MANGANESE_INGOT;
	public static final DeferredItem<Item> RAW_MANGANESE;
	public static final DeferredItem<Item> MANGANESE_CHUNK;
	public static final DeferredItem<Item> MANGANESE_NUGGET;
	public static final DeferredItem<Item> ROUGH_STEEL;
	public static final DeferredItem<Item> STEEL_INGOT;
	public static final DeferredItem<Item> MANGANESE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_MANGANESE_ORE;
	public static final DeferredItem<Item> BLOCK_OF_STEEL;
	public static final DeferredItem<Item> BLOCK_OF_MANGANESE;
	public static final DeferredItem<Item> BLOCK_OF_RAW_MANGANESE;
	public static final DeferredItem<Item> STEEL_SWORD;
	public static final DeferredItem<Item> STEEL_PICKAXE;
	public static final DeferredItem<Item> STEEL_AXE;
	public static final DeferredItem<Item> STEEL_SHOVEL;
	public static final DeferredItem<Item> STEEL_HOE;
	public static final DeferredItem<Item> STEEL_ARMOR_HELMET;
	public static final DeferredItem<Item> STEEL_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> STEEL_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> STEEL_ARMOR_BOOTS;
	public static final DeferredItem<Item> STEEL_KNIFE;
	public static final DeferredItem<Item> STEEL_HAMMER;
	public static final DeferredItem<Item> STEEL_SAW;
	public static final DeferredItem<Item> STEEL_SWORD_BLADE;
	public static final DeferredItem<Item> STEEL_PICKAXE_HEAD;
	public static final DeferredItem<Item> STEEL_AXE_HEAD;
	public static final DeferredItem<Item> STEEL_SHOVEL_HEAD;
	public static final DeferredItem<Item> STEEL_HOE_BLADE;
	public static final DeferredItem<Item> STEEL_KNIFE_BLADE;
	public static final DeferredItem<Item> STEEL_HAMMER_HEAD;
	public static final DeferredItem<Item> STEEL_SAW_BLADE;
	public static final DeferredItem<Item> BRONZE_HANDLE;
	public static final DeferredItem<Item> SMALL_BRONZE_HANDLE;
	public static final DeferredItem<Item> BRONZE_NUGGET;
	public static final DeferredItem<Item> GOLD_CHUNK;
	public static final DeferredItem<Item> SANDSTONE_CHUNK;
	public static final DeferredItem<Item> RED_SANDSTONE_CHUNK;
	public static final DeferredItem<Item> GLASS_SHARD;
	public static final DeferredItem<Item> DIRT_PILE;
	public static final DeferredItem<Item> SAND_PILE;
	public static final DeferredItem<Item> RED_SAND_PILE;
	public static final DeferredItem<Item> COARSE_DIRT_PILE;
	public static final DeferredItem<Item> ROOTED_DIRT_PILE;
	public static final DeferredItem<Item> GRAVEL_PILE;
	public static final DeferredItem<Item> SOUL_SAND_PILE;
	public static final DeferredItem<Item> MUD_PILE;
	public static final DeferredItem<Item> RAW_REDSTONE;
	public static final DeferredItem<Item> REDSTONE_CHUNK;
	public static final DeferredItem<Item> ROUGH_REDSTONE;
	public static final DeferredItem<Item> REDSTONE_INGOT;
	public static final DeferredItem<Item> REDSTONE_NUGGET;
	public static final DeferredItem<Item> BLOCK_OF_RAW_REDSTONE;
	public static final DeferredItem<Item> BRONZE_CHISEL;
	public static final DeferredItem<Item> STEEL_CHISEL;
	public static final DeferredItem<Item> STEEL_NUGGET;
	public static final DeferredItem<Item> MUD_ROCK;
	public static final DeferredItem<Item> CRYING_OBSIDIAN_ROCK;
	public static final DeferredItem<Item> ANCIENT_DEBRIS_CHUNK;
	public static final DeferredItem<Item> MINERAL_PROCESSING_TABLE;
	public static final DeferredItem<Item> REDSTONE_CHARGED_URANIUM_DUST;
	public static final DeferredItem<Item> REACTOR_ROD;
	public static final DeferredItem<Item> DEPLETED_REACTOR_ROD;
	public static final DeferredItem<Item> DIAMOND_PLATED_INGOT;
	public static final DeferredItem<Item> DIAMOND_SWORD_BLADE;
	public static final DeferredItem<Item> DIAMOND_AXE_HEAD;
	public static final DeferredItem<Item> DIAMOND_HOE_BLADE;
	public static final DeferredItem<Item> DIAMOND_PICKAXE_HEAD;
	public static final DeferredItem<Item> DIAMOND_SHOVEL_HEAD;
	public static final DeferredItem<Item> DIAMOND_KNIFE_BLADE;
	public static final DeferredItem<Item> DIAMOND_HAMMER_HEAD;
	public static final DeferredItem<Item> DIAMOND_SAW_BLADE;
	public static final DeferredItem<Item> DIAMOND_HAMMER;
	public static final DeferredItem<Item> DIAMOND_KNIFE;
	public static final DeferredItem<Item> DIAMOND_SAW;
	public static final DeferredItem<Item> DIAMOND_CHISEL;
	public static final DeferredItem<Item> OBSIDIAN_HANDLE;
	public static final DeferredItem<Item> SMALL_OBSIDIAN_HANDLE;
	public static final DeferredItem<Item> ROUGH_PLATED_DIAMOND;
	public static final DeferredItem<Item> EMBEDDED_OBSIDIAN;
	public static final DeferredItem<Item> BACKPACK;
	public static final DeferredItem<Item> GOLD_ROD;
	public static final DeferredItem<Item> BLOOD_MOON_ZOMBIE_SPAWN_EGG;
	public static final DeferredItem<Item> FLESH;
	public static final DeferredItem<Item> HEART_OF_THE_BLOOD_MOON;
	public static final DeferredItem<Item> HEART_OF_THE_NETHER;
	public static final DeferredItem<Item> BLOOD_MOONS_MUSIC_DISC;
	public static final DeferredItem<Item> BLOOD_MOON_DISC_FRAGMENT;
	public static final DeferredItem<Item> COPPER_ROCK_BLOCK;
	public static final DeferredItem<Item> APPLE_OAK_LEAVES;
	public static final DeferredItem<Item> APPLE_TREE_SAPLING;
	public static final DeferredItem<Item> APPLE;
	public static final DeferredItem<Item> EYE_OF_ENDER_FUSION_DUST;
	public static final DeferredItem<Item> WHITE_GLASS_SHARD;
	public static final DeferredItem<Item> ORANGE_GLASS_SHARD;
	public static final DeferredItem<Item> MAGENTA_GLASS_SHARD;
	public static final DeferredItem<Item> LIGHT_BLUE_GLASS_SHARD;
	public static final DeferredItem<Item> YELLOW_GLASS_SHARD;
	public static final DeferredItem<Item> LIME_GREEN_GLASS_SHARD;
	public static final DeferredItem<Item> PINK_GLASS_SHARD;
	public static final DeferredItem<Item> BLACK_GLASS_SHARD;
	public static final DeferredItem<Item> LIGHT_GREY_GLASS_SHARD;
	public static final DeferredItem<Item> CYAN_GLASS_SHARD;
	public static final DeferredItem<Item> PURPLE_GLASS_SHARD;
	public static final DeferredItem<Item> BLUE_GLASS_SHARD;
	public static final DeferredItem<Item> GREEN_GLASS_SHARD;
	public static final DeferredItem<Item> BROWN_GLASS_SHARD;
	public static final DeferredItem<Item> RED_GLASS_SHARD;
	public static final DeferredItem<Item> GREY_GLASS_SHARD;
	public static final DeferredItem<Item> INGOT_MOLD;
	public static final DeferredItem<Item> INGOT_CLAY_MOLD;
	public static final DeferredItem<Item> HEMP_SEEDS;
	public static final DeferredItem<Item> HEMP;
	public static final DeferredItem<Item> HEMP_LEAF;
	public static final DeferredItem<Item> HEMP_PAPER;
	public static final DeferredItem<Item> ROUGH_NETHERITE;
	public static final DeferredItem<Item> NETHERITE_HAMMER;
	public static final DeferredItem<Item> NETHERITE_KNIFE;
	public static final DeferredItem<Item> NETHERITE_SAW;
	public static final DeferredItem<Item> WOOD_INGOT;
	public static final DeferredItem<Item> ROUGH_ZINC;
	public static final DeferredItem<Item> ROUGH_BRASS;
	public static final DeferredItem<Item> RAW_ZINC_NUGGET;
	public static final DeferredItem<Item> LIMESTONE_ROCK;
	public static final DeferredItem<Item> VERIDIUM_ROCK;
	public static final DeferredItem<Item> OCHRUM_ROCK;
	public static final DeferredItem<Item> CRIMSITE_ROCK;
	public static final DeferredItem<Item> SCORCHIA_ROCK;
	public static final DeferredItem<Item> ASURINE_CRYSTAL;
	public static final DeferredItem<Item> SCORIA_ROCK;
	public static final DeferredItem<Item> SHALE;
	public static final DeferredItem<Item> SHALE_ROCK;
	public static final DeferredItem<Item> TITANIUM_ORE;
	public static final DeferredItem<Item> DEEPSLATE_TITANIUM_ORE;
	public static final DeferredItem<Item> SHALE_TITANIUM_ORE;
	public static final DeferredItem<Item> RAW_TITANIUM;
	public static final DeferredItem<Item> ROUGH_TITANIUM;
	public static final DeferredItem<Item> TITANIUM_INGOT;
	public static final DeferredItem<Item> RAW_TITANIUM_NUGGET;
	public static final DeferredItem<Item> TITANIUM_NUGGET;
	public static final DeferredItem<Item> BLOCK_OF_TITANIUM;
	public static final DeferredItem<Item> BLOCK_OF_RAW_TITANIUM;
	public static final DeferredItem<Item> RADIANT_LOG;
	public static final DeferredItem<Item> RADIATED_BARK;
	public static final DeferredItem<Item> RADIATED_PLANK;
	public static final DeferredItem<Item> STRIPPED_RADIANT_LOG;
	public static final DeferredItem<Item> RADIANT_PLANKS;
	public static final DeferredItem<Item> RADIATED_LEAVES;
	public static final DeferredItem<Item> RADIATED_SAPLING;
	public static final DeferredItem<Item> RADIATED_STAIRS;
	public static final DeferredItem<Item> RADIATED_SLAB;
	public static final DeferredItem<Item> RADIATED_FENCE;
	public static final DeferredItem<Item> RADIATED_FENCE_GATE;
	public static final DeferredItem<Item> RADIATED_PRESSURE_PLATE;
	public static final DeferredItem<Item> RADIATED_BUTTON;
	public static final DeferredItem<Item> RADIATED_SHALE;
	public static final DeferredItem<Item> THIN_RADIATED_VINES;
	public static final DeferredItem<Item> THIN_RADIATED_VINE_BASE;
	public static final DeferredItem<Item> RADIATED_MOSS;
	public static final DeferredItem<Item> RADIATED_TALL_GRASS;
	public static final DeferredItem<Item> THICK_RADIATED_VINES;
	public static final DeferredItem<Item> THICK_RADIATED_VINES_BASE;
	public static final DeferredItem<Item> RADIATED_ORCHID;
	public static final DeferredItem<Item> SHALE_URANINITE_ORE;
	public static final DeferredItem<Item> URANINITE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_URANINITE_ORE;
	public static final DeferredItem<Item> URANIUM_DUST;
	public static final DeferredItem<Item> RAW_URANINITE;
	public static final DeferredItem<Item> RAW_URANINITE_NUGGET;
	public static final DeferredItem<Item> BLOCK_OF_RAW_URANINITE;
	public static final DeferredItem<Item> POLISHED_SHALE;
	public static final DeferredItem<Item> POLISHED_SHALE_BRICKS;
	public static final DeferredItem<Item> POLISHED_CHISELED_SHALE;
	public static final DeferredItem<Item> POLISHED_SHALE_STAIRS;
	public static final DeferredItem<Item> POLISHED_SHALE_BRICK_STAIRS;
	public static final DeferredItem<Item> POLISHED_SHALE_SLAB;
	public static final DeferredItem<Item> POLISHED_SHALE_BRICK_SLAB;
	public static final DeferredItem<Item> POLISHED_SHALE_WALL;
	public static final DeferredItem<Item> POLOSHED_SHALE_BRICK_WALL;
	public static final DeferredItem<Item> SHALE_STAIRS;
	public static final DeferredItem<Item> SHALE_SLAB;
	public static final DeferredItem<Item> SHALE_WALL;
	public static final DeferredItem<Item> ROUGH_URANIUM;
	public static final DeferredItem<Item> URANIUM_INGOT;
	public static final DeferredItem<Item> URANIUM_NUGGET;
	public static final DeferredItem<Item> BLOCK_OF_URANIUM;
	public static final DeferredItem<Item> GAS_MASK_FILTER;
	public static final DeferredItem<Item> HEMP_MESH;
	public static final DeferredItem<Item> USED_FILTER;
	public static final DeferredItem<Item> URANIUM_ROD;
	public static final DeferredItem<Item> RADIANT_TRAPDOOR;
	public static final DeferredItem<Item> RADIANT_DOOR;
	public static final DeferredItem<Item> STEEL_DOOR;
	public static final DeferredItem<Item> STEEL_TRAPDOOR;
	public static final DeferredItem<Item> ROUGH_TURANITE;
	public static final DeferredItem<Item> TURANITE_INGOT;
	public static final DeferredItem<Item> TURANITE_NUGGET;
	public static final DeferredItem<Item> TURANITE_BLOCK;
	public static final DeferredItem<Item> ADVANCED_REACTOR_ROD;
	public static final DeferredItem<Item> ADVANCED_ALLOY_FORGE;
	public static final DeferredItem<Item> DRAINED_ADVANCED_REACTOR_ROD;
	public static final DeferredItem<Item> FUEL_UPGRADE;
	public static final DeferredItem<Item> FUEL_UPGRADE_MKII;
	public static final DeferredItem<Item> YIELD_UPGRADE;
	public static final DeferredItem<Item> YIELD_UPGRADE_MKII;
	public static final DeferredItem<Item> YIELD_UPGRADE_MKIII;
	public static final DeferredItem<Item> EFFICIENCY_UPGRADE;
	public static final DeferredItem<Item> BLOCK_PACKAGING_UPGRADE;
	public static final DeferredItem<Item> PLATED_DIAMOND_BLOCK;
	public static final DeferredItem<Item> NETHERITE_SCRAP_BLOCK;
	public static final DeferredItem<Item> BLACK_SAND_PILE;
	public static final DeferredItem<Item> ORANGE_SAND_PILE;
	public static final DeferredItem<Item> WHITE_SAND_PILE;
	public static final DeferredItem<Item> BLACK_SANDSTONE_CHUNK;
	public static final DeferredItem<Item> ORANGE_SANDSTONE_CHUNK;
	public static final DeferredItem<Item> WHITE_SANDSTONE_CHUNK;
	public static final DeferredItem<Item> THERMAL_CALCITE_ROCK;
	public static final DeferredItem<Item> BRIMSTONE_ROCK;
	public static final DeferredItem<Item> FIR_BARK;
	public static final DeferredItem<Item> PINE_BARK;
	public static final DeferredItem<Item> MAPLE_BARK;
	public static final DeferredItem<Item> REDWOOD_BARK;
	public static final DeferredItem<Item> MAHOGANY_BARK;
	public static final DeferredItem<Item> JACARANDA_BARK;
	public static final DeferredItem<Item> PALM_BARK;
	public static final DeferredItem<Item> WILLOW_BARK;
	public static final DeferredItem<Item> DEAD_BARK;
	public static final DeferredItem<Item> MAGIC_BARK;
	public static final DeferredItem<Item> UMBRAN_B_ARK;
	public static final DeferredItem<Item> EMPYREAL_BARK;
	public static final DeferredItem<Item> HELL_BARK;
	public static final DeferredItem<Item> SILVER_ORE;
	public static final DeferredItem<Item> RAW_SILVER;
	public static final DeferredItem<Item> ROUGH_SILVER;
	public static final DeferredItem<Item> SILVER_INGOT;
	public static final DeferredItem<Item> RAW_SILVER_BLOCK;
	public static final DeferredItem<Item> SILVER_BLOCK;
	public static final DeferredItem<Item> SILVER_NUGGET;
	public static final DeferredItem<Item> RAW_SILVER_NUGGET;
	public static final DeferredItem<Item> SAPPHIRE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_SAPPHIRE_ORE;
	public static final DeferredItem<Item> SAPPHIRE;
	public static final DeferredItem<Item> SAPPHIRE_BLOCK;
	public static final DeferredItem<Item> SAPPHIRE_SILVER_RUNE;
	public static final DeferredItem<Item> SAPPHIRE_GOLD_RUNE;
	public static final DeferredItem<Item> AAF_SCRIPTURE;
	public static final DeferredItem<Item> BLOOD_MOON_ITEM;
	public static final DeferredItem<Item> SOLAR_ECLIPSE_ITEM;
	public static final DeferredItem<Item> RADIATION_ITEM;
	public static final DeferredItem<Item> GAS_MASK_HELMET;
	public static final DeferredItem<Item> CRIMSON_ARACHNID_SPAWN_EGG;
	public static final DeferredItem<Item> ALPHA_CRIMSON_ARACHNID_SPAWN_EGG;
	public static final DeferredItem<Item> CRIMSON_THREAD;
	public static final DeferredItem<Item> SULFUR_BLOCK;
	public static final DeferredItem<Item> NITRE_BLOCK;
	public static final DeferredItem<Item> SULFUR;
	public static final DeferredItem<Item> NITRE;
	public static final DeferredItem<Item> MORTAR_PESTAL;
	public static final DeferredItem<Item> CHARCOAL_POWDER;
	public static final DeferredItem<Item> SULFUR_POWDER;
	public static final DeferredItem<Item> SALTPETER;
	public static final DeferredItem<Item> RUNE_CLAY_MOLD;
	public static final DeferredItem<Item> RUNE_MOLD;
	public static final DeferredItem<Item> WOODEN_RUNE;
	public static final DeferredItem<Item> EMPTY_SILVER_RUNE;
	public static final DeferredItem<Item> EMPTY_GOLD_RUNE;
	public static final DeferredItem<Item> RUNE_MAGIC_INFUSER;
	public static final DeferredItem<Item> RUBY_ORE;
	public static final DeferredItem<Item> DEEPSLATE_RUBY_ORE;
	public static final DeferredItem<Item> RUBY;
	public static final DeferredItem<Item> BLOCK_OF_RUBY;
	public static final DeferredItem<Item> AMBER_ORE;
	public static final DeferredItem<Item> DEEPSLATE_AMBER_ORE;
	public static final DeferredItem<Item> BLOCK_OF_AMBER;
	public static final DeferredItem<Item> AMBER;
	public static final DeferredItem<Item> WISTERIA_LOG;
	public static final DeferredItem<Item> WISTERIA_LEAVES;
	public static final DeferredItem<Item> FLOWING_WISTERIA_LEAVES;
	public static final DeferredItem<Item> WISTERIA_SPIDER_LILY;
	public static final DeferredItem<Item> WISTERIA_SAPLING;
	public static final DeferredItem<Item> WISTERIA_LEAF_LITTER;
	public static final DeferredItem<Item> WISTERIA_FLOWER_UPPER;
	public static final DeferredItem<Item> WISTERIA_FLOWER_LOWER;
	public static final DeferredItem<Item> DEEPSLATE_TIN_ORE;
	public static final DeferredItem<Item> SILVER_AMBER_RUNE;
	public static final DeferredItem<Item> GOLD_AMBER_RUNE;
	public static final DeferredItem<Item> GOLD_DIAMOND_RUNE;
	public static final DeferredItem<Item> SILVER_DIAMOND_RUNE;
	public static final DeferredItem<Item> SILVER_EMERALD_RUNE;
	public static final DeferredItem<Item> GOLD_EMERALD_RUNE;
	public static final DeferredItem<Item> SILVER_RUBY_RUNE;
	public static final DeferredItem<Item> GOLD_RUBY_RUNE;
	public static final DeferredItem<Item> GOLD_LAPIS_RUNE;
	public static final DeferredItem<Item> SILVER_LAPIS_RUNE;
	public static final DeferredItem<Item> OBSIDIAN_ROCK;
	public static final DeferredItem<Item> HEMATITE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_HEMATITE_ORE;
	public static final DeferredItem<Item> BASALT_HEMATITE_ORE;
	public static final DeferredItem<Item> HEMATITE_BLOCK;
	public static final DeferredItem<Item> MAGNETITE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_MAGNETITE_ORE;
	public static final DeferredItem<Item> BASALT_MAGNETITE_ORE;
	public static final DeferredItem<Item> MAGNETITE_BLOCK;
	public static final DeferredItem<Item> MAGNETITE_CHUNK;
	public static final DeferredItem<Item> HEMATITE_CHUNK;
	public static final DeferredItem<Item> MAGNETITE_NUGGET;
	public static final DeferredItem<Item> HEMATITE_NUGGET;
	public static final DeferredItem<Item> MALACHITE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_MALACHITE_ORE;
	public static final DeferredItem<Item> MALACHITE;
	public static final DeferredItem<Item> MALACHITE_NUGGET;
	public static final DeferredItem<Item> RAW_MALACHITE_BLOCK;
	public static final DeferredItem<Item> AZURITE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_AZURITE_ORE;
	public static final DeferredItem<Item> AZURITE;
	public static final DeferredItem<Item> AZURITE_NUGGET;
	public static final DeferredItem<Item> RAW_AZURITE_BLOCK;
	public static final DeferredItem<Item> CASSITERITE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_CASSITERITE_ORE;
	public static final DeferredItem<Item> RAW_CASSITERITE_BLOCK;
	public static final DeferredItem<Item> CASSITERITE;
	public static final DeferredItem<Item> CASSITERITE_NUGGET;
	public static final DeferredItem<Item> DEEPSLATE_SILVER_ORE;
	public static final DeferredItem<Item> ARGENTITE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_ARGENTITE_ORE;
	public static final DeferredItem<Item> BASALT_ARGENTITE_ORE;
	public static final DeferredItem<Item> ARGENTITE;
	public static final DeferredItem<Item> ARGENTITE_NUGGET;
	public static final DeferredItem<Item> ARGENTITE_BLOCK;
	public static final DeferredItem<Item> BASALT_URANINITE_ORE;
	public static final DeferredItem<Item> CALAVERITE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_CALAVERITE_ORE;
	public static final DeferredItem<Item> BASALT_CALAVERITE_ORE;
	public static final DeferredItem<Item> CALAVERITE;
	public static final DeferredItem<Item> CALAVERITE_NUGGET;
	public static final DeferredItem<Item> CALAVERITE_BLOCK;
	public static final DeferredItem<Item> MANGANITE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_MANGANITE_ORE;
	public static final DeferredItem<Item> BASALT_MANGANITE_ORE;
	public static final DeferredItem<Item> MANGANITE_BLOCK;
	public static final DeferredItem<Item> MANGANITE;
	public static final DeferredItem<Item> MANGANITE_NUGGET;
	public static final DeferredItem<Item> PYROLUSITE_ORE;
	public static final DeferredItem<Item> PYROLUSITE_BLOCK;
	public static final DeferredItem<Item> PYROLUSITE;
	public static final DeferredItem<Item> PYROLUSITE_NUGGET;
	public static final DeferredItem<Item> DEEPSLATE_PYROLUSITE_ORE;
	public static final DeferredItem<Item> URANOPHANE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_URANOPHANE_ORE;
	public static final DeferredItem<Item> BASALT_URANOPHANE_ORE;
	public static final DeferredItem<Item> SHALE_URANOPHANE_ORE;
	public static final DeferredItem<Item> URANOPHANE_BLOCK;
	public static final DeferredItem<Item> URANOPHANE;
	public static final DeferredItem<Item> URANOPHANE_NUGGET;
	public static final DeferredItem<Item> ILMENITE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_ILMENITE_ORE;
	public static final DeferredItem<Item> BASALT_ILMENITE_ORE;
	public static final DeferredItem<Item> ILMENITE;
	public static final DeferredItem<Item> ILMENITE_NUGGET;
	public static final DeferredItem<Item> ILMENITE_BLOCK;
	public static final DeferredItem<Item> KIMBERLITE_ROCK;
	public static final DeferredItem<Item> KIMBERLITE;
	public static final DeferredItem<Item> KIMBERLITE_STALAGMITE_TOP;
	public static final DeferredItem<Item> KIMBERLITE_STALAGMITE_MIDDLE;
	public static final DeferredItem<Item> KIMBERLITE_STALAGMITE_BASE;
	public static final DeferredItem<Item> KIMBERLITE_STALAGTITE_TIP;
	public static final DeferredItem<Item> KIMBERLITE_STALAGTITE_MIDDLE;
	public static final DeferredItem<Item> KIMBERLITE_STALAGTITE_BASE;
	public static final DeferredItem<Item> DEEPSLATE_STALAGMITE_TOP;
	public static final DeferredItem<Item> DEEPSLATE_STALAGMITE_MIDDLE;
	public static final DeferredItem<Item> DEEPSLATE_STALAGMITE_BASE;
	public static final DeferredItem<Item> DEEPSLATE_STALAGTITE_TIP;
	public static final DeferredItem<Item> DEEPSLATE_STALAGTITE_MIDDLE;
	public static final DeferredItem<Item> DEEPSLATE_STALAGTITE_BASE;
	public static final DeferredItem<Item> STONE_STALAGMITE_TOP;
	public static final DeferredItem<Item> STONE_STALAGMITE_MIDDLE;
	public static final DeferredItem<Item> STONE_STALAGMITE_BASE;
	public static final DeferredItem<Item> STONE_STALAGTITE_TIP;
	public static final DeferredItem<Item> STONE_STALAGTITE_MIDDLE;
	public static final DeferredItem<Item> STONE_STALAGTITE_BASE;
	public static final DeferredItem<Item> BASALT_STALAGMITE_TOP;
	public static final DeferredItem<Item> BASALT_STALAGMITE_MIDDLE;
	public static final DeferredItem<Item> BASALT_STALAGMITE_BASE;
	public static final DeferredItem<Item> BASALT_STALAGTITE_TIP;
	public static final DeferredItem<Item> BASALT_STALAGTITE_MIDDLE;
	public static final DeferredItem<Item> BASALT_STALAGTITE_BASE;
	public static final DeferredItem<Item> ROUGH_SAPPHIRE;
	public static final DeferredItem<Item> BASALT_SAPPHIRE_ORE;
	public static final DeferredItem<Item> KIMBERLITE_SAPPHIRE_ORE;
	public static final DeferredItem<Item> BASALT_DIAMOND_ORE;
	public static final DeferredItem<Item> KIMBERLITE_DIAMOND_ORE;
	public static final DeferredItem<Item> ROUGH_DIAMOND;
	public static final DeferredItem<Item> BASALT_EMERALD_ORE;
	public static final DeferredItem<Item> KIMBERLITE_EMERALD_ORE;
	public static final DeferredItem<Item> ROUGH_EMERALD;
	public static final DeferredItem<Item> BASALT_RUBY_ORE;
	public static final DeferredItem<Item> KIMBERLITE_RUBY_ORE;
	public static final DeferredItem<Item> ROUGH_RUBY;
	public static final DeferredItem<Item> BASALT_LAPIS_ORE;
	public static final DeferredItem<Item> KIMBERLITE_LAPIS_ORE;
	public static final DeferredItem<Item> BASALT_AMBER_ORE;
	public static final DeferredItem<Item> KIMBERLITE_AMBER_ORE;
	public static final DeferredItem<Item> ROUGH_AMBER;
	public static final DeferredItem<Item> SULFUR_ORE;
	public static final DeferredItem<Item> NITRE_POWDER;
	public static final DeferredItem<Item> RUBY_HEART_SHARD;
	public static final DeferredItem<Item> RUBY_HEART;
	public static final DeferredItem<Item> GOLD_HEART;
	public static final DeferredItem<Item> STRIPPED_WISTERIA_LOG;
	public static final DeferredItem<Item> WISTERIA_WOOD;
	public static final DeferredItem<Item> WISTERIA_PLANKS;
	public static final DeferredItem<Item> WISTERIA_STAIRS;
	public static final DeferredItem<Item> WISTERIA_SLAB;
	public static final DeferredItem<Item> WISTERIA_FENCE;
	public static final DeferredItem<Item> WISTERIA_FENCE_GATE;
	public static final DeferredItem<Item> WISTERIA_DOOR;
	public static final DeferredItem<Item> WISTERIA_TRAPDOOR;
	public static final DeferredItem<Item> WISTERIA_PLANK;
	public static final DeferredItem<Item> WISTERIA_BUTTON;
	public static final DeferredItem<Item> WISTERIA_PRESSURE_PLATE;
	public static final DeferredItem<Item> WISTERIA_BARK;
	public static final DeferredItem<Item> ZOMBIE_FACE;
	public static final DeferredItem<Item> PARANOIA_EYE;
	public static final DeferredItem<Item> FEAR_EYE;
	public static final DeferredItem<Item> EYE_CLOSED;
	public static final DeferredItem<Item> PINE_BARK_RU;
	public static final DeferredItem<Item> WILLOW_BARK_RU;
	public static final DeferredItem<Item> REDWOOD_BARK_RU;
	public static final DeferredItem<Item> MAGNOILA_BARK;
	public static final DeferredItem<Item> KAPOK_BARK;
	public static final DeferredItem<Item> LARCH_BARK;
	public static final DeferredItem<Item> EUCALYPTUS_BARK;
	public static final DeferredItem<Item> CYPRESS_BARK;
	public static final DeferredItem<Item> SOCOTRA_BARK;
	public static final DeferredItem<Item> MAUVE_BARK;
	public static final DeferredItem<Item> MAPLE_BARK_RU;
	public static final DeferredItem<Item> DEAD_BARK_RU;
	public static final DeferredItem<Item> COBALT_BARK;
	public static final DeferredItem<Item> BRIMWOOD_BARK;
	public static final DeferredItem<Item> BAOBAB_BARK;
	public static final DeferredItem<Item> SILVER_BIRCH_BARK;
	public static final DeferredItem<Item> ASHEN_BARK;
	public static final DeferredItem<Item> JOSHUA_BARK;
	public static final DeferredItem<Item> ALPHA_OAK_BARK;
	public static final DeferredItem<Item> BLACKWOOD_BARK;
	public static final DeferredItem<Item> PALM_BARK_RU;
	public static final DeferredItem<Item> ARGILLITE_ROCK;
	public static final DeferredItem<Item> VOLCANIC_ASH_PILE;
	public static final DeferredItem<Item> ASH_PILE;
	public static final DeferredItem<Item> SILT_MUD_PILE;
	public static final DeferredItem<Item> SILT_COARSE_DIRT_PILE;
	public static final DeferredItem<Item> SILT_DIRT_PILE;
	public static final DeferredItem<Item> PEAT_PILE;
	public static final DeferredItem<Item> PEAT_COARSE_DIRT_PILE;
	public static final DeferredItem<Item> PEAT_MUD_PILE;
	public static final DeferredItem<Item> ASHEN_DIRT_PILE;
	public static final DeferredItem<Item> CHALK_ROCK;
	public static final DeferredItem<Item> ALPHA_OAK_PLANK;
	public static final DeferredItem<Item> BAOBAB_PLANK;
	public static final DeferredItem<Item> BLACKWOOD_PLANK;
	public static final DeferredItem<Item> BRIMWOOD_PLANK;
	public static final DeferredItem<Item> COBALT_PLANK;
	public static final DeferredItem<Item> CYPRESS_PLANK;
	public static final DeferredItem<Item> DEAD_PLANK;
	public static final DeferredItem<Item> EUCALYPTUS_PLANK;
	public static final DeferredItem<Item> JOSHUA_PLANK;
	public static final DeferredItem<Item> KAPOK_PLANK;
	public static final DeferredItem<Item> LARCH_PLANK;
	public static final DeferredItem<Item> MAGNOLIA_PLANK;
	public static final DeferredItem<Item> MAPLE_PLANK;
	public static final DeferredItem<Item> MAUVE_PLANK;
	public static final DeferredItem<Item> PALM_PLANK;
	public static final DeferredItem<Item> PINE_PLANK;
	public static final DeferredItem<Item> REDWOOD_PLANK;
	public static final DeferredItem<Item> SOCOTRA_PLANK;
	public static final DeferredItem<Item> WILLOW_PLANK;
	static {
		FLINTBLOCK = block(SurvivalReimaginedModBlocks.FLINTBLOCK);
		FLINT_TOOL = REGISTRY.register("flint_tool", FlintToolItem::new);
		LARGE_OAK_BARK = REGISTRY.register("large_oak_bark", LargeOakBarkItem::new);
		LARGE_DARK_OAK_BARK = REGISTRY.register("large_dark_oak_bark", LargeDarkOakBarkItem::new);
		LARGE_SPRUCE_BARK = REGISTRY.register("large_spruce_bark", LargeSpruceBarkItem::new);
		LARGE_BIRCH_BARK = REGISTRY.register("large_birch_bark", LargeBirchBarkItem::new);
		LARGE_MANGROVE_BARK = REGISTRY.register("large_mangrove_bark", LargeMangroveBarkItem::new);
		LARGE_CHERRY_BARK = REGISTRY.register("large_cherry_bark", LargeCherryBarkItem::new);
		LARGE_ACACIA_BARK = REGISTRY.register("large_acacia_bark", LargeAcaciaBarkItem::new);
		LARGE_JUNGLE_BARK = REGISTRY.register("large_jungle_bark", LargeJungleBarkItem::new);
		LARGE_CRIMSON_BARK = REGISTRY.register("large_crimson_bark", LargeCrimsonBarkItem::new);
		LARGE_WARPED_BARK = REGISTRY.register("large_warped_bark", LargeWarpedBarkItem::new);
		STONE_ROCK = REGISTRY.register("stone_rock", StoneRockItem::new);
		STONE_ROCK_BLOC = block(SurvivalReimaginedModBlocks.STONE_ROCK_BLOC);
		HEMP_FIBER = REGISTRY.register("hemp_fiber", PlantFiberItem::new);
		COPPER_CHUNK = REGISTRY.register("copper_chunk", CopperChunkItem::new);
		COPPER_NUGGET = REGISTRY.register("copper_nugget", CopperNuggetItem::new);
		COPPER_CHISEL = REGISTRY.register("copper_chisel", CopperChiselItem::new);
		SMALL_COAL_CHUNK = REGISTRY.register("small_coal_chunk", SmallCoalChunkItem::new);
		TIN_ORE = block(SurvivalReimaginedModBlocks.TIN_ORE);
		RAW_TIN = REGISTRY.register("raw_tin", RawTinItem::new);
		TIN_INGOT = REGISTRY.register("tin_ingot", TinIngotItem::new);
		TIN_NUGGET = REGISTRY.register("tin_nugget", TinNuggetItem::new);
		DEEPSLATE_ROCK = REGISTRY.register("deepslate_rock", DeepslateRockItem::new);
		FORGE = block(SurvivalReimaginedModBlocks.FORGE);
		BRONZE_INGOT = REGISTRY.register("bronze_ingot", BronzeIngotItem::new);
		ROUGH_BRONZE = REGISTRY.register("rough_bronze", RoughBronzeItem::new);
		ROUGH_IRON = REGISTRY.register("rough_iron", RoughIronItem::new);
		ROUGH_GOLD = REGISTRY.register("rough_gold", RoughGoldItem::new);
		ROUGH_COPPER = REGISTRY.register("rough_copper", RoughCopperItem::new);
		ROUGH_TIN = REGISTRY.register("rough_tin", RoughTinItem::new);
		STONE_HAMMER = REGISTRY.register("stone_hammer", StoneHammerItem::new);
		METAL_REFINING_TABLE = block(SurvivalReimaginedModBlocks.METAL_REFINING_TABLE);
		OAK_PLANK = REGISTRY.register("oak_plank", OakPlankItem::new);
		DARK_OAK_PLANK = REGISTRY.register("dark_oak_plank", DarkOakPlankItem::new);
		SPRUCE_PLANK = REGISTRY.register("spruce_plank", SprucePlankItem::new);
		BIRCH_PLANK = REGISTRY.register("birch_plank", BirchPlankItem::new);
		ACACIA_PLANK = REGISTRY.register("acacia_plank", AcaciaPlankItem::new);
		JUNGLE_PLANK = REGISTRY.register("jungle_plank", JunglePlankItem::new);
		CHERRY_PLANK = REGISTRY.register("cherry_plank", CherryPlankItem::new);
		MANGROVE_PLANK = REGISTRY.register("mangrove_plank", MangrovePlankItem::new);
		CRIMSON_PLANK = REGISTRY.register("crimson_plank", CrimsonPlankItem::new);
		WARPED_PLANK = REGISTRY.register("warped_plank", WarpedPlankItem::new);
		STONE_SAW = REGISTRY.register("stone_saw", StoneSawItem::new);
		CLAY_BRICK = REGISTRY.register("clay_brick", ClayBrickItem::new);
		CLAY_CRUCIBLE = block(SurvivalReimaginedModBlocks.CLAY_CRUCIBLE);
		CRUCIBLE = block(SurvivalReimaginedModBlocks.CRUCIBLE);
		BRONZE_PICKAXE = REGISTRY.register("bronze_pickaxe", BronzePickaxeItem::new);
		BRONZE_AXE = REGISTRY.register("bronze_axe", BronzeAxeItem::new);
		BRONZE_SWORD = REGISTRY.register("bronze_sword", BronzeSwordItem::new);
		BRONZE_SHOVEL = REGISTRY.register("bronze_shovel", BronzeShovelItem::new);
		BRONZE_HOE = REGISTRY.register("bronze_hoe", BronzeHoeItem::new);
		COPPER_HANDLE = REGISTRY.register("copper_handle", CopperHandleItem::new);
		AXE_HEAD_MOLD = block(SurvivalReimaginedModBlocks.AXE_HEAD_MOLD);
		PICKAXE_HEAD_MOLD = block(SurvivalReimaginedModBlocks.PICKAXE_HEAD_MOLD);
		SWORD_BLADE_MOLD = block(SurvivalReimaginedModBlocks.SWORD_BLADE_MOLD);
		HOE_HEAD_MOLD = block(SurvivalReimaginedModBlocks.HOE_HEAD_MOLD);
		SHOVEL_HEAD_MOLD = block(SurvivalReimaginedModBlocks.SHOVEL_HEAD_MOLD);
		SAW_BLADE_MOLD = block(SurvivalReimaginedModBlocks.SAW_BLADE_MOLD);
		HAMMER_HEAD_MOLD = block(SurvivalReimaginedModBlocks.HAMMER_HEAD_MOLD);
		HELMET_MOLD = block(SurvivalReimaginedModBlocks.HELMET_MOLD);
		CHESTPLATE_MOLD = block(SurvivalReimaginedModBlocks.CHESTPLATE_MOLD);
		LEGGING_MOLD = block(SurvivalReimaginedModBlocks.LEGGING_MOLD);
		BOOTS_MOLD = block(SurvivalReimaginedModBlocks.BOOTS_MOLD);
		CLAY_SWORD_BLADE_MOLD = block(SurvivalReimaginedModBlocks.CLAY_SWORD_BLADE_MOLD);
		CLAY_PICKAXE_HEAD_MOLD = block(SurvivalReimaginedModBlocks.CLAY_PICKAXE_HEAD_MOLD);
		CLAY_AXE_HEAD_MOLD = block(SurvivalReimaginedModBlocks.CLAY_AXE_HEAD_MOLD);
		CLAY_SHOVEL_HEAD_MOLD = block(SurvivalReimaginedModBlocks.CLAY_SHOVEL_HEAD_MOLD);
		CLAY_HOE_BLADE_MOLD = block(SurvivalReimaginedModBlocks.CLAY_HOE_BLADE_MOLD);
		CLAY_HAMMER_HEAD_MOLD = block(SurvivalReimaginedModBlocks.CLAY_HAMMER_HEAD_MOLD);
		CLAY_SAW_BLADE_MOLD = block(SurvivalReimaginedModBlocks.CLAY_SAW_BLADE_MOLD);
		CLAY_HELMET_MOLD = block(SurvivalReimaginedModBlocks.CLAY_HELMET_MOLD);
		CLAY_CHESTPLATE_MOLD = block(SurvivalReimaginedModBlocks.CLAY_CHESTPLATE_MOLD);
		CLAY_LEGGINGS_MOLD = block(SurvivalReimaginedModBlocks.CLAY_LEGGINGS_MOLD);
		CLAY_BOOTS_MOLD = block(SurvivalReimaginedModBlocks.CLAY_BOOTS_MOLD);
		BRONZE_ARMOR_HELMET = REGISTRY.register("bronze_armor_helmet", BronzeArmorItem.Helmet::new);
		BRONZE_ARMOR_CHESTPLATE = REGISTRY.register("bronze_armor_chestplate", BronzeArmorItem.Chestplate::new);
		BRONZE_ARMOR_LEGGINGS = REGISTRY.register("bronze_armor_leggings", BronzeArmorItem.Leggings::new);
		BRONZE_ARMOR_BOOTS = REGISTRY.register("bronze_armor_boots", BronzeArmorItem.Boots::new);
		BRONZE_SAW = REGISTRY.register("bronze_saw", BronzeSawItem::new);
		BRONZE_HAMMER = REGISTRY.register("bronze_hammer", BronzeHammerItem::new);
		BRONZE_PICKAXE_HEAD = REGISTRY.register("bronze_pickaxe_head", BronzePickaxeHeadItem::new);
		BRONZE_AXE_HEAD = REGISTRY.register("bronze_axe_head", BronzeAxeHeadItem::new);
		BRONZE_SWORD_BLADE = REGISTRY.register("bronze_sword_blade", BronzeSwordBladeItem::new);
		BRONZE_HOE_BLADE = REGISTRY.register("bronze_hoe_blade", BronzeHoeBladeItem::new);
		BRONZE_SHOVEL_HEAD = REGISTRY.register("bronze_shovel_head", BronzeShovelHeadItem::new);
		BRONZE_HAMMER_HEAD = REGISTRY.register("bronze_hammer_head", BronzeHammerHeadItem::new);
		BRONZE_SAW_BLADE = REGISTRY.register("bronze_saw_blade", BronzeSawBladeItem::new);
		WOODEN_SAW = REGISTRY.register("wooden_saw", WoodenSawItem::new);
		WOODEN_HAMMER = REGISTRY.register("wooden_hammer", WoodenHammerItem::new);
		WOODEN_HELMET = REGISTRY.register("wooden_helmet", WoodenItem.Helmet::new);
		WOODEN_CHESTPLATE = REGISTRY.register("wooden_chestplate", WoodenItem.Chestplate::new);
		WOODEN_LEGGINGS = REGISTRY.register("wooden_leggings", WoodenItem.Leggings::new);
		WOODEN_BOOTS = REGISTRY.register("wooden_boots", WoodenItem.Boots::new);
		IRON_CHUNK = REGISTRY.register("iron_chunk", IronChunkItem::new);
		BLOCK_OF_BRONZE = block(SurvivalReimaginedModBlocks.BLOCK_OF_BRONZE);
		TIN_CHUNK = REGISTRY.register("tin_chunk", TinChunkItem::new);
		HEART = REGISTRY.register("heart", HeartItem::new);
		ANDESITE_ROCK = REGISTRY.register("andesite_rock", AndesiteRockItem::new);
		ANDESITE_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.ANDESITE_ROCK_BLOCK);
		GRANITE_ROCK = REGISTRY.register("granite_rock", GraniteRockItem::new);
		GRANITE_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.GRANITE_ROCK_BLOCK);
		DIORITE_ROCK_B_LOCK = block(SurvivalReimaginedModBlocks.DIORITE_ROCK_B_LOCK);
		DIORITE_ROCK = REGISTRY.register("diorite_rock", DioriteRockItem::new);
		DRIPSTONE_ROCK = REGISTRY.register("dripstone_rock", DripstoneRockItem::new);
		DRIPSTONE_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.DRIPSTONE_ROCK_BLOCK);
		CALCITE_ROCK = REGISTRY.register("calcite_rock", CalciteRockItem::new);
		CALCITE_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.CALCITE_ROCK_BLOCK);
		TUFF_ROCK = REGISTRY.register("tuff_rock", TuffRockItem::new);
		TUFF_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.TUFF_ROCK_BLOCK);
		MOSSY_STONE_ROCK = REGISTRY.register("mossy_stone_rock", MossyStoneRockItem::new);
		MOSSY_STONE_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.MOSSY_STONE_ROCK_BLOCK);
		NETHERRACK_ROCK = REGISTRY.register("netherrack_rock", NetherrackRockItem::new);
		NETHERRACK_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.NETHERRACK_ROCK_BLOCK);
		END_STONE_ROCK = REGISTRY.register("end_stone_rock", EndStoneRockItem::new);
		END_STONE_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.END_STONE_ROCK_BLOCK);
		BLACKSTONE_ROCK = REGISTRY.register("blackstone_rock", BlackstoneRockItem::new);
		BLACKSTONE_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.BLACKSTONE_ROCK_BLOCK);
		BASALT_ROCK = REGISTRY.register("basalt_rock", BasaltRockItem::new);
		BASALT_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.BASALT_ROCK_BLOCK);
		DEEPSLATE_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.DEEPSLATE_ROCK_BLOCK);
		BOAT_PADDLES = REGISTRY.register("boat_paddles", BoatPaddlesItem::new);
		BLOCK_OF_RAW_TIN = block(SurvivalReimaginedModBlocks.BLOCK_OF_RAW_TIN);
		BLOCK_OF_TIN = block(SurvivalReimaginedModBlocks.BLOCK_OF_TIN);
		COW_CARCASS = block(SurvivalReimaginedModBlocks.COW_CARCASS);
		STONE_KNIFE = REGISTRY.register("stone_knife", StoneKnifeItem::new);
		COW_HIDE = REGISTRY.register("cow_hide", CowHideItem::new);
		COW_LEG = block(SurvivalReimaginedModBlocks.COW_LEG);
		COW_HEAD = block(SurvivalReimaginedModBlocks.COW_HEAD);
		BRAIN = REGISTRY.register("brain", BrainItem::new);
		HEART_ITEM = REGISTRY.register("heart_item", HeartItemItem::new);
		INTESTINES = REGISTRY.register("intestines", IntestinesItem::new);
		STOMACH = REGISTRY.register("stomach", StomachItem::new);
		LIVER = REGISTRY.register("liver", LiverItem::new);
		LUNGS = REGISTRY.register("lungs", LungsItem::new);
		COOKED_BRAIN = REGISTRY.register("cooked_brain", CookedBrainItem::new);
		COOKED_HEART = REGISTRY.register("cooked_heart", CookedHeartItem::new);
		COOKED_INTESTINES = REGISTRY.register("cooked_intestines", CookedIntestinesItem::new);
		COOKED_LIVER = REGISTRY.register("cooked_liver", CookedLiverItem::new);
		COOKED_STOMACH = REGISTRY.register("cooked_stomach", CookedStomachItem::new);
		COOKED_LUNGS = REGISTRY.register("cooked_lungs", CookedLungsItem::new);
		SPOILED_BRAIN = REGISTRY.register("spoiled_brain", SpoiledBrainItem::new);
		SPOILED_HEART = REGISTRY.register("spoiled_heart", SpoiledHeartItem::new);
		SPOILED_INTESTINES = REGISTRY.register("spoiled_intestines", SpoiledIntestinesItem::new);
		SPOILED_LIVER = REGISTRY.register("spoiled_liver", SpoiledLiverItem::new);
		SPOILED_LUNGS = REGISTRY.register("spoiled_lungs", SpoiledLungsItem::new);
		SPOILED_STOMACH = REGISTRY.register("spoiled_stomach", SpoiledStomachItem::new);
		SPOILED_COD = REGISTRY.register("spoiled_cod", SpoiledCodItem::new);
		SPOILED_SALMAN = REGISTRY.register("spoiled_salman", SpoiledSalmanItem::new);
		SPOILED_CHICKEN = REGISTRY.register("spoiled_chicken", SpoiledChickenItem::new);
		SPOILED_RABBIT = REGISTRY.register("spoiled_rabbit", SpoiledRabbitItem::new);
		SPOILED_MUTTON = REGISTRY.register("spoiled_mutton", SpoiledMuttonItem::new);
		SPOILED_PORKCHOP = REGISTRY.register("spoiled_porkchop", SpoiledPorkchopItem::new);
		SPOILED_BEEF = REGISTRY.register("spoiled_beef", SpoiledBeefItem::new);
		SALT = REGISTRY.register("salt", SaltItem::new);
		CURED_STEAK = REGISTRY.register("cured_steak", CuredSteakItem::new);
		CURED_PORKCHOP = REGISTRY.register("cured_porkchop", CuredPorkchopItem::new);
		CURED_CHICKEN = REGISTRY.register("cured_chicken", CuredChickenItem::new);
		CURED_RABBIT = REGISTRY.register("cured_rabbit", CuredRabbitItem::new);
		CURED_MUTTON = REGISTRY.register("cured_mutton", CuredMuttonItem::new);
		CURED_HEART = REGISTRY.register("cured_heart", CuredHeartItem::new);
		CURED_INTESTINES = REGISTRY.register("cured_intestines", CuredIntestinesItem::new);
		CURED_BRAIN = REGISTRY.register("cured_brain", CuredBrainItem::new);
		CURED_LIVER = REGISTRY.register("cured_liver", CuredLiverItem::new);
		CURED_STOMACH = REGISTRY.register("cured_stomach", CuredStomachItem::new);
		CURED_LUNGS = REGISTRY.register("cured_lungs", CuredLungsItem::new);
		SAND_SALT_DEPOSIT = block(SurvivalReimaginedModBlocks.SAND_SALT_DEPOSIT);
		SHEEP_CARCASS = block(SurvivalReimaginedModBlocks.SHEEP_CARCASS);
		SHEEP_HIDE = REGISTRY.register("sheep_hide", SheepHideItem::new);
		SHEEP_LEG = block(SurvivalReimaginedModBlocks.SHEEP_LEG);
		SHEEP_HEAD = block(SurvivalReimaginedModBlocks.SHEEP_HEAD);
		CHICKEN_CARCASS = block(SurvivalReimaginedModBlocks.CHICKEN_CARCASS);
		PIG_CARCASS = block(SurvivalReimaginedModBlocks.PIG_CARCASS);
		PIG_HEAD = block(SurvivalReimaginedModBlocks.PIG_HEAD);
		PIG_LEG = block(SurvivalReimaginedModBlocks.PIG_LEG);
		BRONZE_KNIFE = REGISTRY.register("bronze_knife", BronzeKnifeItem::new);
		BRONZE_KNIFE_BLADE = REGISTRY.register("bronze_knife_blade", BronzeKnifeBladeItem::new);
		WOODEN_KNIFE = REGISTRY.register("wooden_knife", WoodenKnifeItem::new);
		SMALL_STICK = REGISTRY.register("small_stick", SmallStickItem::new);
		KNIFE_BLADE_MOLD = block(SurvivalReimaginedModBlocks.KNIFE_BLADE_MOLD);
		CLAY_KNIFE_MOLD = block(SurvivalReimaginedModBlocks.CLAY_KNIFE_MOLD);
		SMALL_COPPER_HANDLE = REGISTRY.register("small_copper_handle", SmallCopperHandleItem::new);
		ROUGH_MANGANESE = REGISTRY.register("rough_manganese", RoughManganeseItem::new);
		MANGANESE_INGOT = REGISTRY.register("manganese_ingot", ManganeseIngotItem::new);
		RAW_MANGANESE = REGISTRY.register("raw_manganese", RawManganeseItem::new);
		MANGANESE_CHUNK = REGISTRY.register("manganese_chunk", ManganeseChunkItem::new);
		MANGANESE_NUGGET = REGISTRY.register("manganese_nugget", ManganeseNuggetItem::new);
		ROUGH_STEEL = REGISTRY.register("rough_steel", RoughSteelItem::new);
		STEEL_INGOT = REGISTRY.register("steel_ingot", SteelIngotItem::new);
		MANGANESE_ORE = block(SurvivalReimaginedModBlocks.MANGANESE_ORE);
		DEEPSLATE_MANGANESE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_MANGANESE_ORE);
		BLOCK_OF_STEEL = block(SurvivalReimaginedModBlocks.BLOCK_OF_STEEL);
		BLOCK_OF_MANGANESE = block(SurvivalReimaginedModBlocks.BLOCK_OF_MANGANESE);
		BLOCK_OF_RAW_MANGANESE = block(SurvivalReimaginedModBlocks.BLOCK_OF_RAW_MANGANESE);
		STEEL_SWORD = REGISTRY.register("steel_sword", SteelSwordItem::new);
		STEEL_PICKAXE = REGISTRY.register("steel_pickaxe", SteelPickaxeItem::new);
		STEEL_AXE = REGISTRY.register("steel_axe", SteelAxeItem::new);
		STEEL_SHOVEL = REGISTRY.register("steel_shovel", SteelShovelItem::new);
		STEEL_HOE = REGISTRY.register("steel_hoe", SteelHoeItem::new);
		STEEL_ARMOR_HELMET = REGISTRY.register("steel_armor_helmet", SteelArmorItem.Helmet::new);
		STEEL_ARMOR_CHESTPLATE = REGISTRY.register("steel_armor_chestplate", SteelArmorItem.Chestplate::new);
		STEEL_ARMOR_LEGGINGS = REGISTRY.register("steel_armor_leggings", SteelArmorItem.Leggings::new);
		STEEL_ARMOR_BOOTS = REGISTRY.register("steel_armor_boots", SteelArmorItem.Boots::new);
		STEEL_KNIFE = REGISTRY.register("steel_knife", SteelKnifeItem::new);
		STEEL_HAMMER = REGISTRY.register("steel_hammer", SteelHammerItem::new);
		STEEL_SAW = REGISTRY.register("steel_saw", SteelSawItem::new);
		STEEL_SWORD_BLADE = REGISTRY.register("steel_sword_blade", SteelSwordBladeItem::new);
		STEEL_PICKAXE_HEAD = REGISTRY.register("steel_pickaxe_head", SteelPickaxeHeadItem::new);
		STEEL_AXE_HEAD = REGISTRY.register("steel_axe_head", SteelAxeHeadItem::new);
		STEEL_SHOVEL_HEAD = REGISTRY.register("steel_shovel_head", SteelShovelHeadItem::new);
		STEEL_HOE_BLADE = REGISTRY.register("steel_hoe_blade", SteelHoeBladeItem::new);
		STEEL_KNIFE_BLADE = REGISTRY.register("steel_knife_blade", SteelKnifeBladeItem::new);
		STEEL_HAMMER_HEAD = REGISTRY.register("steel_hammer_head", SteelHammerHeadItem::new);
		STEEL_SAW_BLADE = REGISTRY.register("steel_saw_blade", SteelSawBladeItem::new);
		BRONZE_HANDLE = REGISTRY.register("bronze_handle", BronzeHandleItem::new);
		SMALL_BRONZE_HANDLE = REGISTRY.register("small_bronze_handle", SmallBronzeHandleItem::new);
		BRONZE_NUGGET = REGISTRY.register("bronze_nugget", BronzeNuggetItem::new);
		GOLD_CHUNK = REGISTRY.register("gold_chunk", GoldChunkItem::new);
		SANDSTONE_CHUNK = REGISTRY.register("sandstone_chunk", SandstoneChunkItem::new);
		RED_SANDSTONE_CHUNK = REGISTRY.register("red_sandstone_chunk", RedSandstoneChunkItem::new);
		GLASS_SHARD = REGISTRY.register("glass_shard", GlassShardItem::new);
		DIRT_PILE = REGISTRY.register("dirt_pile", DirtPileItem::new);
		SAND_PILE = REGISTRY.register("sand_pile", SandPileItem::new);
		RED_SAND_PILE = REGISTRY.register("red_sand_pile", RedSandPileItem::new);
		COARSE_DIRT_PILE = REGISTRY.register("coarse_dirt_pile", CoarseDirtPileItem::new);
		ROOTED_DIRT_PILE = REGISTRY.register("rooted_dirt_pile", RootedDirtPileItem::new);
		GRAVEL_PILE = REGISTRY.register("gravel_pile", GravelPileItem::new);
		SOUL_SAND_PILE = REGISTRY.register("soul_sand_pile", SoulSandPileItem::new);
		MUD_PILE = REGISTRY.register("mud_pile", MudPileItem::new);
		RAW_REDSTONE = REGISTRY.register("raw_redstone", RawRedstoneItem::new);
		REDSTONE_CHUNK = REGISTRY.register("redstone_chunk", RedstoneChunkItem::new);
		ROUGH_REDSTONE = REGISTRY.register("rough_redstone", RoughRedstoneItem::new);
		REDSTONE_INGOT = REGISTRY.register("redstone_ingot", RedstoneIngotItem::new);
		REDSTONE_NUGGET = REGISTRY.register("redstone_nugget", RedstoneNuggetItem::new);
		BLOCK_OF_RAW_REDSTONE = block(SurvivalReimaginedModBlocks.BLOCK_OF_RAW_REDSTONE);
		BRONZE_CHISEL = REGISTRY.register("bronze_chisel", BronzeChiselItem::new);
		STEEL_CHISEL = REGISTRY.register("steel_chisel", SteelChiselItem::new);
		STEEL_NUGGET = REGISTRY.register("steel_nugget", SteelNuggetItem::new);
		MUD_ROCK = REGISTRY.register("mud_rock", MudRockItem::new);
		CRYING_OBSIDIAN_ROCK = REGISTRY.register("crying_obsidian_rock", CryingObsidianRockItem::new);
		ANCIENT_DEBRIS_CHUNK = REGISTRY.register("ancient_debris_chunk", AncientDebrisChunkItem::new);
		MINERAL_PROCESSING_TABLE = block(SurvivalReimaginedModBlocks.MINERAL_PROCESSING_TABLE);
		REDSTONE_CHARGED_URANIUM_DUST = REGISTRY.register("redstone_charged_uranium_dust", RedstoneChargedUraniumDustItem::new);
		REACTOR_ROD = REGISTRY.register("reactor_rod", ReactorRodItem::new);
		DEPLETED_REACTOR_ROD = REGISTRY.register("depleted_reactor_rod", DepletedReactorRodItem::new);
		DIAMOND_PLATED_INGOT = REGISTRY.register("diamond_plated_ingot", DiamondPlatedIngotItem::new);
		DIAMOND_SWORD_BLADE = REGISTRY.register("diamond_sword_blade", DiamondSwordBladeItem::new);
		DIAMOND_AXE_HEAD = REGISTRY.register("diamond_axe_head", DiamondAxeHeadItem::new);
		DIAMOND_HOE_BLADE = REGISTRY.register("diamond_hoe_blade", DiamondHoeBladeItem::new);
		DIAMOND_PICKAXE_HEAD = REGISTRY.register("diamond_pickaxe_head", DiamondPickaxeHeadItem::new);
		DIAMOND_SHOVEL_HEAD = REGISTRY.register("diamond_shovel_head", DiamondShovelHeadItem::new);
		DIAMOND_KNIFE_BLADE = REGISTRY.register("diamond_knife_blade", DiamondKnifeBladeItem::new);
		DIAMOND_HAMMER_HEAD = REGISTRY.register("diamond_hammer_head", DiamondHammerHeadItem::new);
		DIAMOND_SAW_BLADE = REGISTRY.register("diamond_saw_blade", DiamondSawBladeItem::new);
		DIAMOND_HAMMER = REGISTRY.register("diamond_hammer", DiamondHammerItem::new);
		DIAMOND_KNIFE = REGISTRY.register("diamond_knife", DiamondKnifeItem::new);
		DIAMOND_SAW = REGISTRY.register("diamond_saw", DiamondSawItem::new);
		DIAMOND_CHISEL = REGISTRY.register("diamond_chisel", DiamondChiselItem::new);
		OBSIDIAN_HANDLE = REGISTRY.register("obsidian_handle", ObsidianHandleItem::new);
		SMALL_OBSIDIAN_HANDLE = REGISTRY.register("small_obsidian_handle", SmallObsidianHandleItem::new);
		ROUGH_PLATED_DIAMOND = REGISTRY.register("rough_plated_diamond", RoughPlatedDiamondItem::new);
		EMBEDDED_OBSIDIAN = block(SurvivalReimaginedModBlocks.EMBEDDED_OBSIDIAN);
		BACKPACK = REGISTRY.register("backpack", BackpackItem::new);
		GOLD_ROD = REGISTRY.register("gold_rod", GoldRodItem::new);
		BLOOD_MOON_ZOMBIE_SPAWN_EGG = REGISTRY.register("blood_moon_zombie_spawn_egg", () -> new DeferredSpawnEggItem(SurvivalReimaginedModEntities.BLOOD_MOON_ZOMBIE, -8966363, -12046045, new Item.Properties()));
		FLESH = REGISTRY.register("flesh", FleshItem::new);
		HEART_OF_THE_BLOOD_MOON = REGISTRY.register("heart_of_the_blood_moon", HeartOfTheBloodMoonItem::new);
		HEART_OF_THE_NETHER = REGISTRY.register("heart_of_the_nether", HeartOfTheNetherItem::new);
		BLOOD_MOONS_MUSIC_DISC = REGISTRY.register("blood_moons_music_disc", BloodMoonsMusicDiscItem::new);
		BLOOD_MOON_DISC_FRAGMENT = REGISTRY.register("blood_moon_disc_fragment", BloodMoonDiscFragmentItem::new);
		COPPER_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.COPPER_ROCK_BLOCK);
		APPLE_OAK_LEAVES = block(SurvivalReimaginedModBlocks.APPLE_OAK_LEAVES);
		APPLE_TREE_SAPLING = block(SurvivalReimaginedModBlocks.APPLE_TREE_SAPLING);
		APPLE = block(SurvivalReimaginedModBlocks.APPLE);
		EYE_OF_ENDER_FUSION_DUST = REGISTRY.register("eye_of_ender_fusion_dust", EyeOfEnderFusionDustItem::new);
		WHITE_GLASS_SHARD = REGISTRY.register("white_glass_shard", WhiteGlassShardItem::new);
		ORANGE_GLASS_SHARD = REGISTRY.register("orange_glass_shard", OrangeGlassShardItem::new);
		MAGENTA_GLASS_SHARD = REGISTRY.register("magenta_glass_shard", MagentaGlassShardItem::new);
		LIGHT_BLUE_GLASS_SHARD = REGISTRY.register("light_blue_glass_shard", LightBlueGlassShardItem::new);
		YELLOW_GLASS_SHARD = REGISTRY.register("yellow_glass_shard", YellowGlassShardItem::new);
		LIME_GREEN_GLASS_SHARD = REGISTRY.register("lime_green_glass_shard", LimeGreenGlassShardItem::new);
		PINK_GLASS_SHARD = REGISTRY.register("pink_glass_shard", PinkGlassShardItem::new);
		BLACK_GLASS_SHARD = REGISTRY.register("black_glass_shard", BlackGlassShardItem::new);
		LIGHT_GREY_GLASS_SHARD = REGISTRY.register("light_grey_glass_shard", LightGreyGlassShardItem::new);
		CYAN_GLASS_SHARD = REGISTRY.register("cyan_glass_shard", CyanGlassShardItem::new);
		PURPLE_GLASS_SHARD = REGISTRY.register("purple_glass_shard", PurpleGlassShardItem::new);
		BLUE_GLASS_SHARD = REGISTRY.register("blue_glass_shard", BlueGlassShardItem::new);
		GREEN_GLASS_SHARD = REGISTRY.register("green_glass_shard", GreenGlassShardItem::new);
		BROWN_GLASS_SHARD = REGISTRY.register("brown_glass_shard", BrownGlassShardItem::new);
		RED_GLASS_SHARD = REGISTRY.register("red_glass_shard", RedGlassShardItem::new);
		GREY_GLASS_SHARD = REGISTRY.register("grey_glass_shard", GreyGlassShardItem::new);
		INGOT_MOLD = block(SurvivalReimaginedModBlocks.INGOT_MOLD);
		INGOT_CLAY_MOLD = block(SurvivalReimaginedModBlocks.INGOT_CLAY_MOLD);
		HEMP_SEEDS = REGISTRY.register("hemp_seeds", HempSeedsItem::new);
		HEMP = block(SurvivalReimaginedModBlocks.HEMP);
		HEMP_LEAF = REGISTRY.register("hemp_leaf", HempLeafItem::new);
		HEMP_PAPER = REGISTRY.register("hemp_paper", HempPaperItem::new);
		ROUGH_NETHERITE = REGISTRY.register("rough_netherite", RoughNetheriteItem::new);
		NETHERITE_HAMMER = REGISTRY.register("netherite_hammer", NetheriteHammerItem::new);
		NETHERITE_KNIFE = REGISTRY.register("netherite_knife", NetheriteKnifeItem::new);
		NETHERITE_SAW = REGISTRY.register("netherite_saw", NetheriteSawItem::new);
		WOOD_INGOT = REGISTRY.register("wood_ingot", WoodIngotItem::new);
		ROUGH_ZINC = REGISTRY.register("rough_zinc", RoughZincItem::new);
		ROUGH_BRASS = REGISTRY.register("rough_brass", RoughBrassItem::new);
		RAW_ZINC_NUGGET = REGISTRY.register("raw_zinc_nugget", RawZincNuggetItem::new);
		LIMESTONE_ROCK = block(SurvivalReimaginedModBlocks.LIMESTONE_ROCK);
		VERIDIUM_ROCK = block(SurvivalReimaginedModBlocks.VERIDIUM_ROCK);
		OCHRUM_ROCK = block(SurvivalReimaginedModBlocks.OCHRUM_ROCK);
		CRIMSITE_ROCK = block(SurvivalReimaginedModBlocks.CRIMSITE_ROCK);
		SCORCHIA_ROCK = block(SurvivalReimaginedModBlocks.SCORCHIA_ROCK);
		ASURINE_CRYSTAL = block(SurvivalReimaginedModBlocks.ASURINE_CRYSTAL);
		SCORIA_ROCK = block(SurvivalReimaginedModBlocks.SCORIA_ROCK);
		SHALE = block(SurvivalReimaginedModBlocks.SHALE);
		SHALE_ROCK = block(SurvivalReimaginedModBlocks.SHALE_ROCK);
		TITANIUM_ORE = block(SurvivalReimaginedModBlocks.TITANIUM_ORE);
		DEEPSLATE_TITANIUM_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_TITANIUM_ORE);
		SHALE_TITANIUM_ORE = block(SurvivalReimaginedModBlocks.SHALE_TITANIUM_ORE);
		RAW_TITANIUM = REGISTRY.register("raw_titanium", RawTitaniumItem::new);
		ROUGH_TITANIUM = REGISTRY.register("rough_titanium", RoughTitaniumItem::new);
		TITANIUM_INGOT = REGISTRY.register("titanium_ingot", TitaniumIngotItem::new);
		RAW_TITANIUM_NUGGET = REGISTRY.register("raw_titanium_nugget", RawTitaniumNuggetItem::new);
		TITANIUM_NUGGET = REGISTRY.register("titanium_nugget", TitaniumNuggetItem::new);
		BLOCK_OF_TITANIUM = block(SurvivalReimaginedModBlocks.BLOCK_OF_TITANIUM);
		BLOCK_OF_RAW_TITANIUM = block(SurvivalReimaginedModBlocks.BLOCK_OF_RAW_TITANIUM);
		RADIANT_LOG = block(SurvivalReimaginedModBlocks.RADIANT_LOG);
		RADIATED_BARK = REGISTRY.register("radiated_bark", RadiatedBarkItem::new);
		RADIATED_PLANK = REGISTRY.register("radiated_plank", RadiatedPlankItem::new);
		STRIPPED_RADIANT_LOG = block(SurvivalReimaginedModBlocks.STRIPPED_RADIANT_LOG);
		RADIANT_PLANKS = block(SurvivalReimaginedModBlocks.RADIANT_PLANKS);
		RADIATED_LEAVES = block(SurvivalReimaginedModBlocks.RADIATED_LEAVES);
		RADIATED_SAPLING = block(SurvivalReimaginedModBlocks.RADIATED_SAPLING);
		RADIATED_STAIRS = block(SurvivalReimaginedModBlocks.RADIATED_STAIRS);
		RADIATED_SLAB = block(SurvivalReimaginedModBlocks.RADIATED_SLAB);
		RADIATED_FENCE = block(SurvivalReimaginedModBlocks.RADIATED_FENCE);
		RADIATED_FENCE_GATE = block(SurvivalReimaginedModBlocks.RADIATED_FENCE_GATE);
		RADIATED_PRESSURE_PLATE = block(SurvivalReimaginedModBlocks.RADIATED_PRESSURE_PLATE);
		RADIATED_BUTTON = block(SurvivalReimaginedModBlocks.RADIATED_BUTTON);
		RADIATED_SHALE = block(SurvivalReimaginedModBlocks.RADIATED_SHALE);
		THIN_RADIATED_VINES = block(SurvivalReimaginedModBlocks.THIN_RADIATED_VINES);
		THIN_RADIATED_VINE_BASE = block(SurvivalReimaginedModBlocks.THIN_RADIATED_VINE_BASE);
		RADIATED_MOSS = block(SurvivalReimaginedModBlocks.RADIATED_MOSS);
		RADIATED_TALL_GRASS = block(SurvivalReimaginedModBlocks.RADIATED_TALL_GRASS);
		THICK_RADIATED_VINES = block(SurvivalReimaginedModBlocks.THICK_RADIATED_VINES);
		THICK_RADIATED_VINES_BASE = block(SurvivalReimaginedModBlocks.THICK_RADIATED_VINES_BASE);
		RADIATED_ORCHID = block(SurvivalReimaginedModBlocks.RADIATED_ORCHID);
		SHALE_URANINITE_ORE = block(SurvivalReimaginedModBlocks.SHALE_URANINITE_ORE);
		URANINITE_ORE = block(SurvivalReimaginedModBlocks.URANINITE_ORE);
		DEEPSLATE_URANINITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_URANINITE_ORE);
		URANIUM_DUST = REGISTRY.register("uranium_dust", UraniumDustItem::new);
		RAW_URANINITE = REGISTRY.register("raw_uraninite", RawUraniniteItem::new);
		RAW_URANINITE_NUGGET = REGISTRY.register("raw_uraninite_nugget", RawUraniniteNuggetItem::new);
		BLOCK_OF_RAW_URANINITE = block(SurvivalReimaginedModBlocks.BLOCK_OF_RAW_URANINITE);
		POLISHED_SHALE = block(SurvivalReimaginedModBlocks.POLISHED_SHALE);
		POLISHED_SHALE_BRICKS = block(SurvivalReimaginedModBlocks.POLISHED_SHALE_BRICKS);
		POLISHED_CHISELED_SHALE = block(SurvivalReimaginedModBlocks.POLISHED_CHISELED_SHALE);
		POLISHED_SHALE_STAIRS = block(SurvivalReimaginedModBlocks.POLISHED_SHALE_STAIRS);
		POLISHED_SHALE_BRICK_STAIRS = block(SurvivalReimaginedModBlocks.POLISHED_SHALE_BRICK_STAIRS);
		POLISHED_SHALE_SLAB = block(SurvivalReimaginedModBlocks.POLISHED_SHALE_SLAB);
		POLISHED_SHALE_BRICK_SLAB = block(SurvivalReimaginedModBlocks.POLISHED_SHALE_BRICK_SLAB);
		POLISHED_SHALE_WALL = block(SurvivalReimaginedModBlocks.POLISHED_SHALE_WALL);
		POLOSHED_SHALE_BRICK_WALL = block(SurvivalReimaginedModBlocks.POLOSHED_SHALE_BRICK_WALL);
		SHALE_STAIRS = block(SurvivalReimaginedModBlocks.SHALE_STAIRS);
		SHALE_SLAB = block(SurvivalReimaginedModBlocks.SHALE_SLAB);
		SHALE_WALL = block(SurvivalReimaginedModBlocks.SHALE_WALL);
		ROUGH_URANIUM = REGISTRY.register("rough_uranium", RoughUraniumItem::new);
		URANIUM_INGOT = REGISTRY.register("uranium_ingot", UraniumIngotItem::new);
		URANIUM_NUGGET = REGISTRY.register("uranium_nugget", UraniumNuggetItem::new);
		BLOCK_OF_URANIUM = block(SurvivalReimaginedModBlocks.BLOCK_OF_URANIUM);
		GAS_MASK_FILTER = REGISTRY.register("gas_mask_filter", GasMaskFilterItem::new);
		HEMP_MESH = REGISTRY.register("hemp_mesh", HempMeshItem::new);
		USED_FILTER = REGISTRY.register("used_filter", UsedFilterItem::new);
		URANIUM_ROD = block(SurvivalReimaginedModBlocks.URANIUM_ROD);
		RADIANT_TRAPDOOR = block(SurvivalReimaginedModBlocks.RADIANT_TRAPDOOR);
		RADIANT_DOOR = doubleBlock(SurvivalReimaginedModBlocks.RADIANT_DOOR);
		STEEL_DOOR = doubleBlock(SurvivalReimaginedModBlocks.STEEL_DOOR);
		STEEL_TRAPDOOR = block(SurvivalReimaginedModBlocks.STEEL_TRAPDOOR);
		ROUGH_TURANITE = REGISTRY.register("rough_turanite", RoughTuraniteItem::new);
		TURANITE_INGOT = REGISTRY.register("turanite_ingot", TuraniteIngotItem::new);
		TURANITE_NUGGET = REGISTRY.register("turanite_nugget", TuraniteNuggetItem::new);
		TURANITE_BLOCK = block(SurvivalReimaginedModBlocks.TURANITE_BLOCK);
		ADVANCED_REACTOR_ROD = REGISTRY.register("advanced_reactor_rod", AdvancedReactorRodItem::new);
		ADVANCED_ALLOY_FORGE = block(SurvivalReimaginedModBlocks.ADVANCED_ALLOY_FORGE);
		DRAINED_ADVANCED_REACTOR_ROD = REGISTRY.register("drained_advanced_reactor_rod", DrainedAdvancedReactorRodItem::new);
		FUEL_UPGRADE = REGISTRY.register("fuel_upgrade", FuelUpgradeItem::new);
		FUEL_UPGRADE_MKII = REGISTRY.register("fuel_upgrade_mkii", FuelUpgradeMKIIItem::new);
		YIELD_UPGRADE = REGISTRY.register("yield_upgrade", YieldUpgradeItem::new);
		YIELD_UPGRADE_MKII = REGISTRY.register("yield_upgrade_mkii", YieldUpgradeMKIIItem::new);
		YIELD_UPGRADE_MKIII = REGISTRY.register("yield_upgrade_mkiii", YieldUpgradeMKIIIItem::new);
		EFFICIENCY_UPGRADE = REGISTRY.register("efficiency_upgrade", EfficiencyUpgradeItem::new);
		BLOCK_PACKAGING_UPGRADE = REGISTRY.register("block_packaging_upgrade", BlockPackagingUpgradeItem::new);
		PLATED_DIAMOND_BLOCK = block(SurvivalReimaginedModBlocks.PLATED_DIAMOND_BLOCK);
		NETHERITE_SCRAP_BLOCK = block(SurvivalReimaginedModBlocks.NETHERITE_SCRAP_BLOCK);
		BLACK_SAND_PILE = REGISTRY.register("black_sand_pile", BlackSandPileItem::new);
		ORANGE_SAND_PILE = REGISTRY.register("orange_sand_pile", OrangeSandPileItem::new);
		WHITE_SAND_PILE = REGISTRY.register("white_sand_pile", WhiteSandPileItem::new);
		BLACK_SANDSTONE_CHUNK = REGISTRY.register("black_sandstone_chunk", BlackSandstoneChunkItem::new);
		ORANGE_SANDSTONE_CHUNK = REGISTRY.register("orange_sandstone_chunk", OrangeSandstoneChunkItem::new);
		WHITE_SANDSTONE_CHUNK = REGISTRY.register("white_sandstone_chunk", WhiteSandstoneChunkItem::new);
		THERMAL_CALCITE_ROCK = REGISTRY.register("thermal_calcite_rock", ThermalCalciteRockItem::new);
		BRIMSTONE_ROCK = REGISTRY.register("brimstone_rock", BrimstoneRockItem::new);
		FIR_BARK = REGISTRY.register("fir_bark", FirBarkItem::new);
		PINE_BARK = REGISTRY.register("pine_bark", PineBarkItem::new);
		MAPLE_BARK = REGISTRY.register("maple_bark", MapleBarkItem::new);
		REDWOOD_BARK = REGISTRY.register("redwood_bark", RedwoodBarkItem::new);
		MAHOGANY_BARK = REGISTRY.register("mahogany_bark", MahoganyBarkItem::new);
		JACARANDA_BARK = REGISTRY.register("jacaranda_bark", JacarandaBarkItem::new);
		PALM_BARK = REGISTRY.register("palm_bark", PalmBarkItem::new);
		WILLOW_BARK = REGISTRY.register("willow_bark", WillowBarkItem::new);
		DEAD_BARK = REGISTRY.register("dead_bark", DeadBarkItem::new);
		MAGIC_BARK = REGISTRY.register("magic_bark", MagicBarkItem::new);
		UMBRAN_B_ARK = REGISTRY.register("umbran_b_ark", UmbranBArkItem::new);
		EMPYREAL_BARK = REGISTRY.register("empyreal_bark", EmpyrealBarkItem::new);
		HELL_BARK = REGISTRY.register("hell_bark", HellBarkItem::new);
		SILVER_ORE = block(SurvivalReimaginedModBlocks.SILVER_ORE);
		RAW_SILVER = REGISTRY.register("raw_silver", RawSilverItem::new);
		ROUGH_SILVER = REGISTRY.register("rough_silver", RoughSilverItem::new);
		SILVER_INGOT = REGISTRY.register("silver_ingot", SilverIngotItem::new);
		RAW_SILVER_BLOCK = block(SurvivalReimaginedModBlocks.RAW_SILVER_BLOCK);
		SILVER_BLOCK = block(SurvivalReimaginedModBlocks.SILVER_BLOCK);
		SILVER_NUGGET = REGISTRY.register("silver_nugget", SilverNuggetItem::new);
		RAW_SILVER_NUGGET = REGISTRY.register("raw_silver_nugget", RawSilverNuggetItem::new);
		SAPPHIRE_ORE = block(SurvivalReimaginedModBlocks.SAPPHIRE_ORE);
		DEEPSLATE_SAPPHIRE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_SAPPHIRE_ORE);
		SAPPHIRE = REGISTRY.register("sapphire", SapphireItem::new);
		SAPPHIRE_BLOCK = block(SurvivalReimaginedModBlocks.SAPPHIRE_BLOCK);
		SAPPHIRE_SILVER_RUNE = REGISTRY.register("sapphire_silver_rune", SapphireSilverRuneItem::new);
		SAPPHIRE_GOLD_RUNE = REGISTRY.register("sapphire_gold_rune", SapphireGoldRuneItem::new);
		AAF_SCRIPTURE = REGISTRY.register("aaf_scripture", AAFScriptureItem::new);
		BLOOD_MOON_ITEM = REGISTRY.register("blood_moon_item", BloodMoonItemItem::new);
		SOLAR_ECLIPSE_ITEM = REGISTRY.register("solar_eclipse_item", SolarEclipseItemItem::new);
		RADIATION_ITEM = REGISTRY.register("radiation_item", RadiationItemItem::new);
		GAS_MASK_HELMET = REGISTRY.register("gas_mask_helmet", GasMaskItem.Helmet::new);
		CRIMSON_ARACHNID_SPAWN_EGG = REGISTRY.register("crimson_arachnid_spawn_egg", () -> new DeferredSpawnEggItem(SurvivalReimaginedModEntities.CRIMSON_ARACHNID, -14941694, -426884, new Item.Properties()));
		ALPHA_CRIMSON_ARACHNID_SPAWN_EGG = REGISTRY.register("alpha_crimson_arachnid_spawn_egg", () -> new DeferredSpawnEggItem(SurvivalReimaginedModEntities.ALPHA_CRIMSON_ARACHNID, -14941694, -426884, new Item.Properties()));
		CRIMSON_THREAD = REGISTRY.register("crimson_thread", CrimsonThreadItem::new);
		SULFUR_BLOCK = block(SurvivalReimaginedModBlocks.SULFUR_BLOCK);
		NITRE_BLOCK = block(SurvivalReimaginedModBlocks.NITRE_BLOCK);
		SULFUR = REGISTRY.register("sulfur", SulfurItem::new);
		NITRE = REGISTRY.register("nitre", NitreItem::new);
		MORTAR_PESTAL = REGISTRY.register("mortar_pestal", MortarPestalItem::new);
		CHARCOAL_POWDER = REGISTRY.register("charcoal_powder", CharcoalPowderItem::new);
		SULFUR_POWDER = REGISTRY.register("sulfur_powder", SulfurPowderItem::new);
		SALTPETER = REGISTRY.register("saltpeter", SaltpeterItem::new);
		RUNE_CLAY_MOLD = block(SurvivalReimaginedModBlocks.RUNE_CLAY_MOLD);
		RUNE_MOLD = block(SurvivalReimaginedModBlocks.RUNE_MOLD);
		WOODEN_RUNE = REGISTRY.register("wooden_rune", WoodenRuneItem::new);
		EMPTY_SILVER_RUNE = REGISTRY.register("empty_silver_rune", EmptySilverRuneItem::new);
		EMPTY_GOLD_RUNE = REGISTRY.register("empty_gold_rune", EmptyGoldRuneItem::new);
		RUNE_MAGIC_INFUSER = block(SurvivalReimaginedModBlocks.RUNE_MAGIC_INFUSER);
		RUBY_ORE = block(SurvivalReimaginedModBlocks.RUBY_ORE);
		DEEPSLATE_RUBY_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_RUBY_ORE);
		RUBY = REGISTRY.register("ruby", RubyItem::new);
		BLOCK_OF_RUBY = block(SurvivalReimaginedModBlocks.BLOCK_OF_RUBY);
		AMBER_ORE = block(SurvivalReimaginedModBlocks.AMBER_ORE);
		DEEPSLATE_AMBER_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_AMBER_ORE);
		BLOCK_OF_AMBER = block(SurvivalReimaginedModBlocks.BLOCK_OF_AMBER);
		AMBER = REGISTRY.register("amber", AmberItem::new);
		WISTERIA_LOG = block(SurvivalReimaginedModBlocks.WISTERIA_LOG);
		WISTERIA_LEAVES = block(SurvivalReimaginedModBlocks.WISTERIA_LEAVES);
		FLOWING_WISTERIA_LEAVES = block(SurvivalReimaginedModBlocks.FLOWING_WISTERIA_LEAVES);
		WISTERIA_SPIDER_LILY = block(SurvivalReimaginedModBlocks.WISTERIA_SPIDER_LILY);
		WISTERIA_SAPLING = block(SurvivalReimaginedModBlocks.WISTERIA_SAPLING);
		WISTERIA_LEAF_LITTER = block(SurvivalReimaginedModBlocks.WISTERIA_LEAF_LITTER);
		WISTERIA_FLOWER_UPPER = block(SurvivalReimaginedModBlocks.WISTERIA_FLOWER_UPPER);
		WISTERIA_FLOWER_LOWER = block(SurvivalReimaginedModBlocks.WISTERIA_FLOWER_LOWER);
		DEEPSLATE_TIN_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_TIN_ORE);
		SILVER_AMBER_RUNE = REGISTRY.register("silver_amber_rune", SilverAmberRuneItem::new);
		GOLD_AMBER_RUNE = REGISTRY.register("gold_amber_rune", GoldAmberRuneItem::new);
		GOLD_DIAMOND_RUNE = REGISTRY.register("gold_diamond_rune", GoldDiamondRuneItem::new);
		SILVER_DIAMOND_RUNE = REGISTRY.register("silver_diamond_rune", SilverDiamondRuneItem::new);
		SILVER_EMERALD_RUNE = REGISTRY.register("silver_emerald_rune", SilverEmeraldRuneItem::new);
		GOLD_EMERALD_RUNE = REGISTRY.register("gold_emerald_rune", GoldEmeraldRuneItem::new);
		SILVER_RUBY_RUNE = REGISTRY.register("silver_ruby_rune", SilverRubyRuneItem::new);
		GOLD_RUBY_RUNE = REGISTRY.register("gold_ruby_rune", GoldRubyRuneItem::new);
		GOLD_LAPIS_RUNE = REGISTRY.register("gold_lapis_rune", GoldLapisRuneItem::new);
		SILVER_LAPIS_RUNE = REGISTRY.register("silver_lapis_rune", SilverLapisRuneItem::new);
		OBSIDIAN_ROCK = block(SurvivalReimaginedModBlocks.OBSIDIAN_ROCK);
		HEMATITE_ORE = block(SurvivalReimaginedModBlocks.HEMATITE_ORE);
		DEEPSLATE_HEMATITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_HEMATITE_ORE);
		BASALT_HEMATITE_ORE = block(SurvivalReimaginedModBlocks.BASALT_HEMATITE_ORE);
		HEMATITE_BLOCK = block(SurvivalReimaginedModBlocks.HEMATITE_BLOCK);
		MAGNETITE_ORE = block(SurvivalReimaginedModBlocks.MAGNETITE_ORE);
		DEEPSLATE_MAGNETITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_MAGNETITE_ORE);
		BASALT_MAGNETITE_ORE = block(SurvivalReimaginedModBlocks.BASALT_MAGNETITE_ORE);
		MAGNETITE_BLOCK = block(SurvivalReimaginedModBlocks.MAGNETITE_BLOCK);
		MAGNETITE_CHUNK = REGISTRY.register("magnetite_chunk", MagnetiteChunkItem::new);
		HEMATITE_CHUNK = REGISTRY.register("hematite_chunk", HematiteChunkItem::new);
		MAGNETITE_NUGGET = REGISTRY.register("magnetite_nugget", MagnetiteNuggetItem::new);
		HEMATITE_NUGGET = REGISTRY.register("hematite_nugget", HematiteNuggetItem::new);
		MALACHITE_ORE = block(SurvivalReimaginedModBlocks.MALACHITE_ORE);
		DEEPSLATE_MALACHITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_MALACHITE_ORE);
		MALACHITE = REGISTRY.register("malachite", MalachiteItem::new);
		MALACHITE_NUGGET = REGISTRY.register("malachite_nugget", MalachiteNuggetItem::new);
		RAW_MALACHITE_BLOCK = block(SurvivalReimaginedModBlocks.RAW_MALACHITE_BLOCK);
		AZURITE_ORE = block(SurvivalReimaginedModBlocks.AZURITE_ORE);
		DEEPSLATE_AZURITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_AZURITE_ORE);
		AZURITE = REGISTRY.register("azurite", AzuriteItem::new);
		AZURITE_NUGGET = REGISTRY.register("azurite_nugget", AzuriteNuggetItem::new);
		RAW_AZURITE_BLOCK = block(SurvivalReimaginedModBlocks.RAW_AZURITE_BLOCK);
		CASSITERITE_ORE = block(SurvivalReimaginedModBlocks.CASSITERITE_ORE);
		DEEPSLATE_CASSITERITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_CASSITERITE_ORE);
		RAW_CASSITERITE_BLOCK = block(SurvivalReimaginedModBlocks.RAW_CASSITERITE_BLOCK);
		CASSITERITE = REGISTRY.register("cassiterite", CassiteriteItem::new);
		CASSITERITE_NUGGET = REGISTRY.register("cassiterite_nugget", CassiteriteNuggetItem::new);
		DEEPSLATE_SILVER_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_SILVER_ORE);
		ARGENTITE_ORE = block(SurvivalReimaginedModBlocks.ARGENTITE_ORE);
		DEEPSLATE_ARGENTITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_ARGENTITE_ORE);
		BASALT_ARGENTITE_ORE = block(SurvivalReimaginedModBlocks.BASALT_ARGENTITE_ORE);
		ARGENTITE = REGISTRY.register("argentite", ArgentiteItem::new);
		ARGENTITE_NUGGET = REGISTRY.register("argentite_nugget", ArgentiteNuggetItem::new);
		ARGENTITE_BLOCK = block(SurvivalReimaginedModBlocks.ARGENTITE_BLOCK);
		BASALT_URANINITE_ORE = block(SurvivalReimaginedModBlocks.BASALT_URANINITE_ORE);
		CALAVERITE_ORE = block(SurvivalReimaginedModBlocks.CALAVERITE_ORE);
		DEEPSLATE_CALAVERITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_CALAVERITE_ORE);
		BASALT_CALAVERITE_ORE = block(SurvivalReimaginedModBlocks.BASALT_CALAVERITE_ORE);
		CALAVERITE = REGISTRY.register("calaverite", CalaveriteItem::new);
		CALAVERITE_NUGGET = REGISTRY.register("calaverite_nugget", CalaveriteNuggetItem::new);
		CALAVERITE_BLOCK = block(SurvivalReimaginedModBlocks.CALAVERITE_BLOCK);
		MANGANITE_ORE = block(SurvivalReimaginedModBlocks.MANGANITE_ORE);
		DEEPSLATE_MANGANITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_MANGANITE_ORE);
		BASALT_MANGANITE_ORE = block(SurvivalReimaginedModBlocks.BASALT_MANGANITE_ORE);
		MANGANITE_BLOCK = block(SurvivalReimaginedModBlocks.MANGANITE_BLOCK);
		MANGANITE = REGISTRY.register("manganite", ManganiteItem::new);
		MANGANITE_NUGGET = REGISTRY.register("manganite_nugget", ManganiteNuggetItem::new);
		PYROLUSITE_ORE = block(SurvivalReimaginedModBlocks.PYROLUSITE_ORE);
		PYROLUSITE_BLOCK = block(SurvivalReimaginedModBlocks.PYROLUSITE_BLOCK);
		PYROLUSITE = REGISTRY.register("pyrolusite", PyrolusiteItem::new);
		PYROLUSITE_NUGGET = REGISTRY.register("pyrolusite_nugget", PyrolusiteNuggetItem::new);
		DEEPSLATE_PYROLUSITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_PYROLUSITE_ORE);
		URANOPHANE_ORE = block(SurvivalReimaginedModBlocks.URANOPHANE_ORE);
		DEEPSLATE_URANOPHANE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_URANOPHANE_ORE);
		BASALT_URANOPHANE_ORE = block(SurvivalReimaginedModBlocks.BASALT_URANOPHANE_ORE);
		SHALE_URANOPHANE_ORE = block(SurvivalReimaginedModBlocks.SHALE_URANOPHANE_ORE);
		URANOPHANE_BLOCK = block(SurvivalReimaginedModBlocks.URANOPHANE_BLOCK);
		URANOPHANE = REGISTRY.register("uranophane", UranophaneItem::new);
		URANOPHANE_NUGGET = REGISTRY.register("uranophane_nugget", UranophaneNuggetItem::new);
		ILMENITE_ORE = block(SurvivalReimaginedModBlocks.ILMENITE_ORE);
		DEEPSLATE_ILMENITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_ILMENITE_ORE);
		BASALT_ILMENITE_ORE = block(SurvivalReimaginedModBlocks.BASALT_ILMENITE_ORE);
		ILMENITE = REGISTRY.register("ilmenite", IlmeniteItem::new);
		ILMENITE_NUGGET = REGISTRY.register("ilmenite_nugget", IlmeniteNuggetItem::new);
		ILMENITE_BLOCK = block(SurvivalReimaginedModBlocks.ILMENITE_BLOCK);
		KIMBERLITE_ROCK = block(SurvivalReimaginedModBlocks.KIMBERLITE_ROCK);
		KIMBERLITE = block(SurvivalReimaginedModBlocks.KIMBERLITE);
		KIMBERLITE_STALAGMITE_TOP = block(SurvivalReimaginedModBlocks.KIMBERLITE_STALAGMITE_TOP);
		KIMBERLITE_STALAGMITE_MIDDLE = block(SurvivalReimaginedModBlocks.KIMBERLITE_STALAGMITE_MIDDLE);
		KIMBERLITE_STALAGMITE_BASE = block(SurvivalReimaginedModBlocks.KIMBERLITE_STALAGMITE_BASE);
		KIMBERLITE_STALAGTITE_TIP = block(SurvivalReimaginedModBlocks.KIMBERLITE_STALAGTITE_TIP);
		KIMBERLITE_STALAGTITE_MIDDLE = block(SurvivalReimaginedModBlocks.KIMBERLITE_STALAGTITE_MIDDLE);
		KIMBERLITE_STALAGTITE_BASE = block(SurvivalReimaginedModBlocks.KIMBERLITE_STALAGTITE_BASE);
		DEEPSLATE_STALAGMITE_TOP = block(SurvivalReimaginedModBlocks.DEEPSLATE_STALAGMITE_TOP);
		DEEPSLATE_STALAGMITE_MIDDLE = block(SurvivalReimaginedModBlocks.DEEPSLATE_STALAGMITE_MIDDLE);
		DEEPSLATE_STALAGMITE_BASE = block(SurvivalReimaginedModBlocks.DEEPSLATE_STALAGMITE_BASE);
		DEEPSLATE_STALAGTITE_TIP = block(SurvivalReimaginedModBlocks.DEEPSLATE_STALAGTITE_TIP);
		DEEPSLATE_STALAGTITE_MIDDLE = block(SurvivalReimaginedModBlocks.DEEPSLATE_STALAGTITE_MIDDLE);
		DEEPSLATE_STALAGTITE_BASE = block(SurvivalReimaginedModBlocks.DEEPSLATE_STALAGTITE_BASE);
		STONE_STALAGMITE_TOP = block(SurvivalReimaginedModBlocks.STONE_STALAGMITE_TOP);
		STONE_STALAGMITE_MIDDLE = block(SurvivalReimaginedModBlocks.STONE_STALAGMITE_MIDDLE);
		STONE_STALAGMITE_BASE = block(SurvivalReimaginedModBlocks.STONE_STALAGMITE_BASE);
		STONE_STALAGTITE_TIP = block(SurvivalReimaginedModBlocks.STONE_STALAGTITE_TIP);
		STONE_STALAGTITE_MIDDLE = block(SurvivalReimaginedModBlocks.STONE_STALAGTITE_MIDDLE);
		STONE_STALAGTITE_BASE = block(SurvivalReimaginedModBlocks.STONE_STALAGTITE_BASE);
		BASALT_STALAGMITE_TOP = block(SurvivalReimaginedModBlocks.BASALT_STALAGMITE_TOP);
		BASALT_STALAGMITE_MIDDLE = block(SurvivalReimaginedModBlocks.BASALT_STALAGMITE_MIDDLE);
		BASALT_STALAGMITE_BASE = block(SurvivalReimaginedModBlocks.BASALT_STALAGMITE_BASE);
		BASALT_STALAGTITE_TIP = block(SurvivalReimaginedModBlocks.BASALT_STALAGTITE_TIP);
		BASALT_STALAGTITE_MIDDLE = block(SurvivalReimaginedModBlocks.BASALT_STALAGTITE_MIDDLE);
		BASALT_STALAGTITE_BASE = block(SurvivalReimaginedModBlocks.BASALT_STALAGTITE_BASE);
		ROUGH_SAPPHIRE = REGISTRY.register("rough_sapphire", RoughSapphireItem::new);
		BASALT_SAPPHIRE_ORE = block(SurvivalReimaginedModBlocks.BASALT_SAPPHIRE_ORE);
		KIMBERLITE_SAPPHIRE_ORE = block(SurvivalReimaginedModBlocks.KIMBERLITE_SAPPHIRE_ORE);
		BASALT_DIAMOND_ORE = block(SurvivalReimaginedModBlocks.BASALT_DIAMOND_ORE);
		KIMBERLITE_DIAMOND_ORE = block(SurvivalReimaginedModBlocks.KIMBERLITE_DIAMOND_ORE);
		ROUGH_DIAMOND = REGISTRY.register("rough_diamond", RoughDiamondItem::new);
		BASALT_EMERALD_ORE = block(SurvivalReimaginedModBlocks.BASALT_EMERALD_ORE);
		KIMBERLITE_EMERALD_ORE = block(SurvivalReimaginedModBlocks.KIMBERLITE_EMERALD_ORE);
		ROUGH_EMERALD = REGISTRY.register("rough_emerald", RoughEmeraldItem::new);
		BASALT_RUBY_ORE = block(SurvivalReimaginedModBlocks.BASALT_RUBY_ORE);
		KIMBERLITE_RUBY_ORE = block(SurvivalReimaginedModBlocks.KIMBERLITE_RUBY_ORE);
		ROUGH_RUBY = REGISTRY.register("rough_ruby", RoughRubyItem::new);
		BASALT_LAPIS_ORE = block(SurvivalReimaginedModBlocks.BASALT_LAPIS_ORE);
		KIMBERLITE_LAPIS_ORE = block(SurvivalReimaginedModBlocks.KIMBERLITE_LAPIS_ORE);
		BASALT_AMBER_ORE = block(SurvivalReimaginedModBlocks.BASALT_AMBER_ORE);
		KIMBERLITE_AMBER_ORE = block(SurvivalReimaginedModBlocks.KIMBERLITE_AMBER_ORE);
		ROUGH_AMBER = REGISTRY.register("rough_amber", RoughAmberItem::new);
		SULFUR_ORE = block(SurvivalReimaginedModBlocks.SULFUR_ORE);
		NITRE_POWDER = block(SurvivalReimaginedModBlocks.NITRE_POWDER);
		RUBY_HEART_SHARD = REGISTRY.register("ruby_heart_shard", RubyHeartShardItem::new);
		RUBY_HEART = REGISTRY.register("ruby_heart", RubyHeartItem::new);
		GOLD_HEART = REGISTRY.register("gold_heart", GoldHeartItem::new);
		STRIPPED_WISTERIA_LOG = block(SurvivalReimaginedModBlocks.STRIPPED_WISTERIA_LOG);
		WISTERIA_WOOD = block(SurvivalReimaginedModBlocks.WISTERIA_WOOD);
		WISTERIA_PLANKS = block(SurvivalReimaginedModBlocks.WISTERIA_PLANKS);
		WISTERIA_STAIRS = block(SurvivalReimaginedModBlocks.WISTERIA_STAIRS);
		WISTERIA_SLAB = block(SurvivalReimaginedModBlocks.WISTERIA_SLAB);
		WISTERIA_FENCE = block(SurvivalReimaginedModBlocks.WISTERIA_FENCE);
		WISTERIA_FENCE_GATE = block(SurvivalReimaginedModBlocks.WISTERIA_FENCE_GATE);
		WISTERIA_DOOR = doubleBlock(SurvivalReimaginedModBlocks.WISTERIA_DOOR);
		WISTERIA_TRAPDOOR = block(SurvivalReimaginedModBlocks.WISTERIA_TRAPDOOR);
		WISTERIA_PLANK = REGISTRY.register("wisteria_plank", WisteriaPlankItem::new);
		WISTERIA_BUTTON = block(SurvivalReimaginedModBlocks.WISTERIA_BUTTON);
		WISTERIA_PRESSURE_PLATE = block(SurvivalReimaginedModBlocks.WISTERIA_PRESSURE_PLATE);
		WISTERIA_BARK = REGISTRY.register("wisteria_bark", WisteriaBarkItem::new);
		ZOMBIE_FACE = REGISTRY.register("zombie_face", ZombieFaceItem::new);
		PARANOIA_EYE = REGISTRY.register("paranoia_eye", ParanoiaEyeItem::new);
		FEAR_EYE = REGISTRY.register("fear_eye", FearEyeItem::new);
		EYE_CLOSED = REGISTRY.register("eye_closed", EyeClosedItem::new);
		PINE_BARK_RU = REGISTRY.register("pine_bark_ru", PineBarkRUItem::new);
		WILLOW_BARK_RU = REGISTRY.register("willow_bark_ru", WillowBarkRUItem::new);
		REDWOOD_BARK_RU = REGISTRY.register("redwood_bark_ru", RedwoodBarkRUItem::new);
		MAGNOILA_BARK = REGISTRY.register("magnoila_bark", MagnoilaBarkItem::new);
		KAPOK_BARK = REGISTRY.register("kapok_bark", KapokBarkItem::new);
		LARCH_BARK = REGISTRY.register("larch_bark", LarchBarkItem::new);
		EUCALYPTUS_BARK = REGISTRY.register("eucalyptus_bark", EucalyptusBarkItem::new);
		CYPRESS_BARK = REGISTRY.register("cypress_bark", CypressBarkItem::new);
		SOCOTRA_BARK = REGISTRY.register("socotra_bark", SocotraBarkItem::new);
		MAUVE_BARK = REGISTRY.register("mauve_bark", MauveBarkItem::new);
		MAPLE_BARK_RU = REGISTRY.register("maple_bark_ru", MapleBarkRUItem::new);
		DEAD_BARK_RU = REGISTRY.register("dead_bark_ru", DeadBarkRUItem::new);
		COBALT_BARK = REGISTRY.register("cobalt_bark", CobaltBarkItem::new);
		BRIMWOOD_BARK = REGISTRY.register("brimwood_bark", BrimwoodBarkItem::new);
		BAOBAB_BARK = REGISTRY.register("baobab_bark", BaobabBarkItem::new);
		SILVER_BIRCH_BARK = REGISTRY.register("silver_birch_bark", SilverBirchBarkItem::new);
		ASHEN_BARK = REGISTRY.register("ashen_bark", AshenBarkItem::new);
		JOSHUA_BARK = REGISTRY.register("joshua_bark", JoshuaBarkItem::new);
		ALPHA_OAK_BARK = REGISTRY.register("alpha_oak_bark", AlphaOakBarkItem::new);
		BLACKWOOD_BARK = REGISTRY.register("blackwood_bark", BlackwoodBarkItem::new);
		PALM_BARK_RU = REGISTRY.register("palm_bark_ru", PalmBarkRUItem::new);
		ARGILLITE_ROCK = REGISTRY.register("argillite_rock", ArgilliteRockItem::new);
		VOLCANIC_ASH_PILE = REGISTRY.register("volcanic_ash_pile", VolcanicAshPileItem::new);
		ASH_PILE = REGISTRY.register("ash_pile", AshPileItem::new);
		SILT_MUD_PILE = REGISTRY.register("silt_mud_pile", SiltMudPileItem::new);
		SILT_COARSE_DIRT_PILE = REGISTRY.register("silt_coarse_dirt_pile", SiltCoarseDirtPileItem::new);
		SILT_DIRT_PILE = REGISTRY.register("silt_dirt_pile", SiltDirtPileItem::new);
		PEAT_PILE = REGISTRY.register("peat_pile", PeatPileItem::new);
		PEAT_COARSE_DIRT_PILE = REGISTRY.register("peat_coarse_dirt_pile", PeatCoarseDirtPileItem::new);
		PEAT_MUD_PILE = REGISTRY.register("peat_mud_pile", PeatMudPileItem::new);
		ASHEN_DIRT_PILE = REGISTRY.register("ashen_dirt_pile", AshenDirtPileItem::new);
		CHALK_ROCK = REGISTRY.register("chalk_rock", ChalkRockItem::new);
		ALPHA_OAK_PLANK = REGISTRY.register("alpha_oak_plank", AlphaOakPlankItem::new);
		BAOBAB_PLANK = REGISTRY.register("baobab_plank", BaobabPlankItem::new);
		BLACKWOOD_PLANK = REGISTRY.register("blackwood_plank", BlackwoodPlankItem::new);
		BRIMWOOD_PLANK = REGISTRY.register("brimwood_plank", BrimwoodPlankItem::new);
		COBALT_PLANK = REGISTRY.register("cobalt_plank", CobaltPlankItem::new);
		CYPRESS_PLANK = REGISTRY.register("cypress_plank", CypressPlankItem::new);
		DEAD_PLANK = REGISTRY.register("dead_plank", DeadPlankItem::new);
		EUCALYPTUS_PLANK = REGISTRY.register("eucalyptus_plank", EucalyptusPlankItem::new);
		JOSHUA_PLANK = REGISTRY.register("joshua_plank", JoshuaPlankItem::new);
		KAPOK_PLANK = REGISTRY.register("kapok_plank", KapokPlankItem::new);
		LARCH_PLANK = REGISTRY.register("larch_plank", LarchPlankItem::new);
		MAGNOLIA_PLANK = REGISTRY.register("magnolia_plank", MagnoliaPlankItem::new);
		MAPLE_PLANK = REGISTRY.register("maple_plank", MaplePlankItem::new);
		MAUVE_PLANK = REGISTRY.register("mauve_plank", MauvePlankItem::new);
		PALM_PLANK = REGISTRY.register("palm_plank", PalmPlankItem::new);
		PINE_PLANK = REGISTRY.register("pine_plank", PinePlankItem::new);
		REDWOOD_PLANK = REGISTRY.register("redwood_plank", RedwoodPlankItem::new);
		SOCOTRA_PLANK = REGISTRY.register("socotra_plank", SocotraPlankItem::new);
		WILLOW_PLANK = REGISTRY.register("willow_plank", WillowPlankItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new BackpackInventoryCapability(stack), BACKPACK.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new AAFScriptureInventoryCapability(stack), AAF_SCRIPTURE.get());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return doubleBlock(block, new Item.Properties());
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), properties));
	}
}