/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.survivalreimagined.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.event.BlockEntityTypeAddBlocksEvent;
import net.neoforged.neoforge.client.event.RegisterColorHandlersEvent;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.Block;
import net.minecraft.client.renderer.Sheets;

import net.mcreator.survivalreimagined.block.*;
import net.mcreator.survivalreimagined.SurvivalReimaginedMod;

@EventBusSubscriber
public class SurvivalReimaginedModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(SurvivalReimaginedMod.MODID);
	public static final DeferredBlock<Block> FLINTBLOCK;
	public static final DeferredBlock<Block> STONE_ROCK_BLOC;
	public static final DeferredBlock<Block> TIN_ORE;
	public static final DeferredBlock<Block> FORGE;
	public static final DeferredBlock<Block> METAL_REFINING_TABLE;
	public static final DeferredBlock<Block> CLAY_CRUCIBLE;
	public static final DeferredBlock<Block> CRUCIBLE;
	public static final DeferredBlock<Block> AXE_HEAD_MOLD;
	public static final DeferredBlock<Block> PICKAXE_HEAD_MOLD;
	public static final DeferredBlock<Block> SWORD_BLADE_MOLD;
	public static final DeferredBlock<Block> HOE_HEAD_MOLD;
	public static final DeferredBlock<Block> SHOVEL_HEAD_MOLD;
	public static final DeferredBlock<Block> SAW_BLADE_MOLD;
	public static final DeferredBlock<Block> HAMMER_HEAD_MOLD;
	public static final DeferredBlock<Block> CLAY_SWORD_BLADE_MOLD;
	public static final DeferredBlock<Block> CLAY_PICKAXE_HEAD_MOLD;
	public static final DeferredBlock<Block> CLAY_AXE_HEAD_MOLD;
	public static final DeferredBlock<Block> CLAY_SHOVEL_HEAD_MOLD;
	public static final DeferredBlock<Block> CLAY_HOE_BLADE_MOLD;
	public static final DeferredBlock<Block> CLAY_HAMMER_HEAD_MOLD;
	public static final DeferredBlock<Block> CLAY_SAW_BLADE_MOLD;
	public static final DeferredBlock<Block> BLOCK_OF_BRONZE;
	public static final DeferredBlock<Block> ANDESITE_ROCK_BLOCK;
	public static final DeferredBlock<Block> GRANITE_ROCK_BLOCK;
	public static final DeferredBlock<Block> DIORITE_ROCK_B_LOCK;
	public static final DeferredBlock<Block> DRIPSTONE_ROCK_BLOCK;
	public static final DeferredBlock<Block> CALCITE_ROCK_BLOCK;
	public static final DeferredBlock<Block> TUFF_ROCK_BLOCK;
	public static final DeferredBlock<Block> MOSSY_STONE_ROCK_BLOCK;
	public static final DeferredBlock<Block> NETHERRACK_ROCK_BLOCK;
	public static final DeferredBlock<Block> END_STONE_ROCK_BLOCK;
	public static final DeferredBlock<Block> BLACKSTONE_ROCK_BLOCK;
	public static final DeferredBlock<Block> BASALT_ROCK_BLOCK;
	public static final DeferredBlock<Block> DEEPSLATE_ROCK_BLOCK;
	public static final DeferredBlock<Block> BLOCK_OF_RAW_TIN;
	public static final DeferredBlock<Block> BLOCK_OF_TIN;
	public static final DeferredBlock<Block> SAND_SALT_DEPOSIT;
	public static final DeferredBlock<Block> KNIFE_BLADE_MOLD;
	public static final DeferredBlock<Block> CLAY_KNIFE_MOLD;
	public static final DeferredBlock<Block> MANGANESE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_MANGANESE_ORE;
	public static final DeferredBlock<Block> BLOCK_OF_STEEL;
	public static final DeferredBlock<Block> BLOCK_OF_MANGANESE;
	public static final DeferredBlock<Block> BLOCK_OF_RAW_MANGANESE;
	public static final DeferredBlock<Block> BLOCK_OF_RAW_REDSTONE;
	public static final DeferredBlock<Block> MINERAL_PROCESSING_TABLE;
	public static final DeferredBlock<Block> EMBEDDED_OBSIDIAN;
	public static final DeferredBlock<Block> COPPER_ROCK_BLOCK;
	public static final DeferredBlock<Block> APPLE_OAK_LEAVES;
	public static final DeferredBlock<Block> APPLE_TREE_SAPLING;
	public static final DeferredBlock<Block> APPLE;
	public static final DeferredBlock<Block> INGOT_MOLD;
	public static final DeferredBlock<Block> INGOT_CLAY_MOLD;
	public static final DeferredBlock<Block> HEMP;
	public static final DeferredBlock<Block> LIMESTONE_ROCK;
	public static final DeferredBlock<Block> VERIDIUM_ROCK;
	public static final DeferredBlock<Block> OCHRUM_ROCK;
	public static final DeferredBlock<Block> CRIMSITE_ROCK;
	public static final DeferredBlock<Block> SCORCHIA_ROCK;
	public static final DeferredBlock<Block> ASURINE_CRYSTAL;
	public static final DeferredBlock<Block> SCORIA_ROCK;
	public static final DeferredBlock<Block> SHALE;
	public static final DeferredBlock<Block> SHALE_ROCK;
	public static final DeferredBlock<Block> TITANIUM_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_TITANIUM_ORE;
	public static final DeferredBlock<Block> SHALE_TITANIUM_ORE;
	public static final DeferredBlock<Block> BLOCK_OF_TITANIUM;
	public static final DeferredBlock<Block> BLOCK_OF_RAW_TITANIUM;
	public static final DeferredBlock<Block> RADIANT_LOG;
	public static final DeferredBlock<Block> STRIPPED_RADIANT_LOG;
	public static final DeferredBlock<Block> RADIANT_PLANKS;
	public static final DeferredBlock<Block> RADIATED_LEAVES;
	public static final DeferredBlock<Block> RADIATED_SAPLING;
	public static final DeferredBlock<Block> RADIATED_STAIRS;
	public static final DeferredBlock<Block> RADIATED_SLAB;
	public static final DeferredBlock<Block> RADIATED_FENCE;
	public static final DeferredBlock<Block> RADIATED_FENCE_GATE;
	public static final DeferredBlock<Block> RADIATED_PRESSURE_PLATE;
	public static final DeferredBlock<Block> RADIATED_BUTTON;
	public static final DeferredBlock<Block> RADIATED_SHALE;
	public static final DeferredBlock<Block> THIN_RADIATED_VINES;
	public static final DeferredBlock<Block> THIN_RADIATED_VINE_BASE;
	public static final DeferredBlock<Block> RADIATED_MOSS;
	public static final DeferredBlock<Block> RADIATED_TALL_GRASS;
	public static final DeferredBlock<Block> THICK_RADIATED_VINES;
	public static final DeferredBlock<Block> THICK_RADIATED_VINES_BASE;
	public static final DeferredBlock<Block> RADIATED_ORCHID;
	public static final DeferredBlock<Block> SHALE_URANINITE_ORE;
	public static final DeferredBlock<Block> URANINITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_URANINITE_ORE;
	public static final DeferredBlock<Block> BLOCK_OF_RAW_URANINITE;
	public static final DeferredBlock<Block> POLISHED_SHALE;
	public static final DeferredBlock<Block> POLISHED_SHALE_BRICKS;
	public static final DeferredBlock<Block> POLISHED_CHISELED_SHALE;
	public static final DeferredBlock<Block> POLISHED_SHALE_STAIRS;
	public static final DeferredBlock<Block> POLISHED_SHALE_BRICK_STAIRS;
	public static final DeferredBlock<Block> POLISHED_SHALE_SLAB;
	public static final DeferredBlock<Block> POLISHED_SHALE_BRICK_SLAB;
	public static final DeferredBlock<Block> POLISHED_SHALE_WALL;
	public static final DeferredBlock<Block> POLOSHED_SHALE_BRICK_WALL;
	public static final DeferredBlock<Block> SHALE_STAIRS;
	public static final DeferredBlock<Block> SHALE_SLAB;
	public static final DeferredBlock<Block> SHALE_WALL;
	public static final DeferredBlock<Block> BLOCK_OF_URANIUM;
	public static final DeferredBlock<Block> URANIUM_ROD;
	public static final DeferredBlock<Block> RADIANT_TRAPDOOR;
	public static final DeferredBlock<Block> RADIANT_DOOR;
	public static final DeferredBlock<Block> STEEL_DOOR;
	public static final DeferredBlock<Block> STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> TURANITE_BLOCK;
	public static final DeferredBlock<Block> ADVANCED_ALLOY_FORGE;
	public static final DeferredBlock<Block> PLATED_DIAMOND_BLOCK;
	public static final DeferredBlock<Block> NETHERITE_SCRAP_BLOCK;
	public static final DeferredBlock<Block> SILVER_ORE;
	public static final DeferredBlock<Block> RAW_SILVER_BLOCK;
	public static final DeferredBlock<Block> SILVER_BLOCK;
	public static final DeferredBlock<Block> SAPPHIRE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_SAPPHIRE_ORE;
	public static final DeferredBlock<Block> SAPPHIRE_BLOCK;
	public static final DeferredBlock<Block> NITRE_BLOCK;
	public static final DeferredBlock<Block> RUNE_CLAY_MOLD;
	public static final DeferredBlock<Block> RUNE_MOLD;
	public static final DeferredBlock<Block> RUNE_MAGIC_INFUSER;
	public static final DeferredBlock<Block> RUBY_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_RUBY_ORE;
	public static final DeferredBlock<Block> BLOCK_OF_RUBY;
	public static final DeferredBlock<Block> AMBER_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_AMBER_ORE;
	public static final DeferredBlock<Block> BLOCK_OF_AMBER;
	public static final DeferredBlock<Block> WISTERIA_LOG;
	public static final DeferredBlock<Block> WISTERIA_LEAVES;
	public static final DeferredBlock<Block> FLOWING_WISTERIA_LEAVES;
	public static final DeferredBlock<Block> WISTERIA_SPIDER_LILY;
	public static final DeferredBlock<Block> WISTERIA_SAPLING;
	public static final DeferredBlock<Block> WISTERIA_LEAF_LITTER;
	public static final DeferredBlock<Block> WISTERIA_FLOWER_UPPER;
	public static final DeferredBlock<Block> WISTERIA_FLOWER_LOWER;
	public static final DeferredBlock<Block> DEEPSLATE_TIN_ORE;
	public static final DeferredBlock<Block> OBSIDIAN_ROCK;
	public static final DeferredBlock<Block> HEMATITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_HEMATITE_ORE;
	public static final DeferredBlock<Block> BASALT_HEMATITE_ORE;
	public static final DeferredBlock<Block> HEMATITE_BLOCK;
	public static final DeferredBlock<Block> MAGNETITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_MAGNETITE_ORE;
	public static final DeferredBlock<Block> BASALT_MAGNETITE_ORE;
	public static final DeferredBlock<Block> MAGNETITE_BLOCK;
	public static final DeferredBlock<Block> MALACHITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_MALACHITE_ORE;
	public static final DeferredBlock<Block> RAW_MALACHITE_BLOCK;
	public static final DeferredBlock<Block> AZURITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_AZURITE_ORE;
	public static final DeferredBlock<Block> RAW_AZURITE_BLOCK;
	public static final DeferredBlock<Block> CASSITERITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_CASSITERITE_ORE;
	public static final DeferredBlock<Block> RAW_CASSITERITE_BLOCK;
	public static final DeferredBlock<Block> DEEPSLATE_SILVER_ORE;
	public static final DeferredBlock<Block> ARGENTITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_ARGENTITE_ORE;
	public static final DeferredBlock<Block> BASALT_ARGENTITE_ORE;
	public static final DeferredBlock<Block> ARGENTITE_BLOCK;
	public static final DeferredBlock<Block> BASALT_URANINITE_ORE;
	public static final DeferredBlock<Block> CALAVERITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_CALAVERITE_ORE;
	public static final DeferredBlock<Block> BASALT_CALAVERITE_ORE;
	public static final DeferredBlock<Block> CALAVERITE_BLOCK;
	public static final DeferredBlock<Block> MANGANITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_MANGANITE_ORE;
	public static final DeferredBlock<Block> BASALT_PYROLUSITE_ORE;
	public static final DeferredBlock<Block> MANGANITE_BLOCK;
	public static final DeferredBlock<Block> PYROLUSITE_ORE;
	public static final DeferredBlock<Block> PYROLUSITE_BLOCK;
	public static final DeferredBlock<Block> DEEPSLATE_PYROLUSITE_ORE;
	public static final DeferredBlock<Block> URANOPHANE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_URANOPHANE_ORE;
	public static final DeferredBlock<Block> BASALT_URANOPHANE_ORE;
	public static final DeferredBlock<Block> SHALE_URANOPHANE_ORE;
	public static final DeferredBlock<Block> URANOPHANE_BLOCK;
	public static final DeferredBlock<Block> ILMENITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_ILMENITE_ORE;
	public static final DeferredBlock<Block> BASALT_ILMENITE_ORE;
	public static final DeferredBlock<Block> ILMENITE_BLOCK;
	public static final DeferredBlock<Block> KIMBERLITE_ROCK;
	public static final DeferredBlock<Block> KIMBERLITE;
	public static final DeferredBlock<Block> KIMBERLITE_STALAGMITE_TOP;
	public static final DeferredBlock<Block> KIMBERLITE_STALAGMITE_MIDDLE;
	public static final DeferredBlock<Block> KIMBERLITE_STALAGMITE_BASE;
	public static final DeferredBlock<Block> KIMBERLITE_STALAGTITE_TIP;
	public static final DeferredBlock<Block> KIMBERLITE_STALAGTITE_MIDDLE;
	public static final DeferredBlock<Block> KIMBERLITE_STALAGTITE_BASE;
	public static final DeferredBlock<Block> DEEPSLATE_STALAGMITE_TOP;
	public static final DeferredBlock<Block> DEEPSLATE_STALAGMITE_MIDDLE;
	public static final DeferredBlock<Block> DEEPSLATE_STALAGMITE_BASE;
	public static final DeferredBlock<Block> DEEPSLATE_STALAGTITE_TIP;
	public static final DeferredBlock<Block> DEEPSLATE_STALAGTITE_MIDDLE;
	public static final DeferredBlock<Block> DEEPSLATE_STALAGTITE_BASE;
	public static final DeferredBlock<Block> STONE_STALAGMITE_TOP;
	public static final DeferredBlock<Block> STONE_STALAGMITE_MIDDLE;
	public static final DeferredBlock<Block> STONE_STALAGMITE_BASE;
	public static final DeferredBlock<Block> STONE_STALAGTITE_TIP;
	public static final DeferredBlock<Block> STONE_STALAGTITE_MIDDLE;
	public static final DeferredBlock<Block> STONE_STALAGTITE_BASE;
	public static final DeferredBlock<Block> BASALT_STALAGMITE_TOP;
	public static final DeferredBlock<Block> BASALT_STALAGMITE_MIDDLE;
	public static final DeferredBlock<Block> BASALT_STALAGMITE_BASE;
	public static final DeferredBlock<Block> BASALT_STALAGTITE_TIP;
	public static final DeferredBlock<Block> BASALT_STALAGTITE_MIDDLE;
	public static final DeferredBlock<Block> BASALT_STALAGTITE_BASE;
	public static final DeferredBlock<Block> BASALT_SAPPHIRE_ORE;
	public static final DeferredBlock<Block> KIMBERLITE_SAPPHIRE_ORE;
	public static final DeferredBlock<Block> BASALT_DIAMOND_ORE;
	public static final DeferredBlock<Block> KIMBERLITE_DIAMOND_ORE;
	public static final DeferredBlock<Block> BASALT_EMERALD_ORE;
	public static final DeferredBlock<Block> KIMBERLITE_EMERALD_ORE;
	public static final DeferredBlock<Block> BASALT_RUBY_ORE;
	public static final DeferredBlock<Block> KIMBERLITE_RUBY_ORE;
	public static final DeferredBlock<Block> BASALT_LAPIS_ORE;
	public static final DeferredBlock<Block> KIMBERLITE_LAPIS_ORE;
	public static final DeferredBlock<Block> BASALT_AMBER_ORE;
	public static final DeferredBlock<Block> KIMBERLITE_AMBER_ORE;
	public static final DeferredBlock<Block> SULFUR_ORE;
	public static final DeferredBlock<Block> NITRE_POWDER;
	public static final DeferredBlock<Block> STRIPPED_WISTERIA_LOG;
	public static final DeferredBlock<Block> WISTERIA_WOOD;
	public static final DeferredBlock<Block> WISTERIA_PLANKS;
	public static final DeferredBlock<Block> WISTERIA_STAIRS;
	public static final DeferredBlock<Block> WISTERIA_SLAB;
	public static final DeferredBlock<Block> WISTERIA_FENCE;
	public static final DeferredBlock<Block> WISTERIA_FENCE_GATE;
	public static final DeferredBlock<Block> WISTERIA_DOOR;
	public static final DeferredBlock<Block> WISTERIA_TRAPDOOR;
	public static final DeferredBlock<Block> WISTERIA_BUTTON;
	public static final DeferredBlock<Block> WISTERIA_PRESSURE_PLATE;
	public static final DeferredBlock<Block> PURE_SALT_BLOCK;
	public static final DeferredBlock<Block> SALT_DEPOSIT;
	public static final DeferredBlock<Block> SMALL_TROUGH;
	public static final DeferredBlock<Block> SMALL_PALM_LOG;
	public static final DeferredBlock<Block> PALM_LOG;
	public static final DeferredBlock<Block> PALM_LOG_BARKED_TOP;
	public static final DeferredBlock<Block> COCONUT;
	public static final DeferredBlock<Block> COCONUT_MATURE;
	public static final DeferredBlock<Block> PALM_CROWN;
	public static final DeferredBlock<Block> PALM_LEAVES;
	public static final DeferredBlock<Block> ALOE_VERA;
	public static final DeferredBlock<Block> COCONUT_SEEDLING;
	public static final DeferredBlock<Block> STRAWBERRY_PLANT;
	public static final DeferredBlock<Block> BANANA_JUNGLE_LOG;
	public static final DeferredBlock<Block> SMALL_BANANA_JUNGLE_LOG;
	public static final DeferredBlock<Block> BANANA_LEAVES;
	public static final DeferredBlock<Block> BANANA_CLUSTER;
	public static final DeferredBlock<Block> BANANA_GROW_BLOCK;
	public static final DeferredBlock<Block> RADIATED_SIGN;
	public static final DeferredBlock<Block> RADIATED_WALL_SIGN;
	public static final DeferredBlock<Block> HANGING_RADIATED_SIGN;
	public static final DeferredBlock<Block> HANGING_RADIATED_WALL_SIGN;
	public static final DeferredBlock<Block> WISTERIA_SIGN;
	public static final DeferredBlock<Block> WISTERIA_WALL_SIGN;
	public static final DeferredBlock<Block> HANGING_WISTERIA_SIGN;
	public static final DeferredBlock<Block> HANGING_WISTERIA_WALL_SIGN;
	public static final DeferredBlock<Block> MANDARIN_LEAVES;
	public static final DeferredBlock<Block> MANDARIN_LOG;
	public static final DeferredBlock<Block> MANDARIN_FRUIT;
	public static final DeferredBlock<Block> MANDARIN_SAPLING;
	public static final DeferredBlock<Block> CURSED_STONE_TILES;
	public static final DeferredBlock<Block> CHISELED_CURSED_STONE;
	public static final DeferredBlock<Block> CURSED_STONE;
	public static final DeferredBlock<Block> CURSED_STONE_BARS;
	public static final DeferredBlock<Block> CURSED_STONE_TILE_SLAB;
	public static final DeferredBlock<Block> CURSED_STONE_TILE_STAIRS;
	public static final DeferredBlock<Block> CURSED_STONE_SLAB;
	public static final DeferredBlock<Block> CURSED_STONE_STAIRS;
	public static final DeferredBlock<Block> CURSED_STONE_WALL;
	public static final DeferredBlock<Block> SLIM_CURSED_STONE_WALL;
	public static final DeferredBlock<Block> CRACKED_CURSED_STONE_TILES;
	public static final DeferredBlock<Block> CRACKED_CURSED_STONE_WALL;
	public static final DeferredBlock<Block> CURSED_STONE_WALL_STAIRS;
	public static final DeferredBlock<Block> CURSED_STONE_WALL_SLAB;
	public static final DeferredBlock<Block> MILLSTONE;
	public static final DeferredBlock<Block> CAMPFIRE;
	public static final DeferredBlock<Block> LOW_FERTILITY_FARMLAND;
	public static final DeferredBlock<Block> MEDIUM_FERTILITY_DIRT;
	public static final DeferredBlock<Block> MEDIUM_FERTILITY_GRASS;
	public static final DeferredBlock<Block> HIGH_FERTILITY_DIRT;
	public static final DeferredBlock<Block> HIGH_FERTILITY_GRASS;
	public static final DeferredBlock<Block> MEDIUM_FERTILITY_SOIL;
	public static final DeferredBlock<Block> HIGH_FERTILITY_SOIL;
	public static final DeferredBlock<Block> WILD_WHEAT;
	public static final DeferredBlock<Block> WILD_CARROT;
	public static final DeferredBlock<Block> WILD_POTATOES;
	public static final DeferredBlock<Block> BEETROOT;
	public static final DeferredBlock<Block> BLOCK_OF_CHARCOAL;
	public static final DeferredBlock<Block> BRITTLE_OBSIDIAN;
	public static final DeferredBlock<Block> ANTHRACITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_ANTHRACITE_ORE;
	public static final DeferredBlock<Block> BASALT_ANTHRACITE_ORE;
	public static final DeferredBlock<Block> ANTHRACITE_BLOCK;
	public static final DeferredBlock<Block> LIGINITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_LIGINITE_ORE;
	public static final DeferredBlock<Block> BASALT_LIGINITE_ORE;
	public static final DeferredBlock<Block> LIGINITE_BLOCK;
	public static final DeferredBlock<Block> COW_CARCASS;
	public static final DeferredBlock<Block> COW_LEG;
	public static final DeferredBlock<Block> COW_HEAD;
	public static final DeferredBlock<Block> SHEEP_CARCASS;
	public static final DeferredBlock<Block> SHEEP_LEG;
	public static final DeferredBlock<Block> SHEEP_HEAD;
	public static final DeferredBlock<Block> CHICKEN_CARCASS;
	public static final DeferredBlock<Block> PIG_CARCASS;
	public static final DeferredBlock<Block> PIG_LEG;
	public static final DeferredBlock<Block> PIG_HEAD;
	public static final DeferredBlock<Block> GOAT_CARCASS;
	public static final DeferredBlock<Block> GOAT_LEG;
	public static final DeferredBlock<Block> GOAT_HEAD;
	public static final DeferredBlock<Block> DRYING_RACK;
	public static final DeferredBlock<Block> TANNING_BARREL;
	public static final DeferredBlock<Block> WHEAT_CROP;
	public static final DeferredBlock<Block> CORN_STALK_BOTTOM;
	public static final DeferredBlock<Block> CORN_STALK_MIDDLE;
	public static final DeferredBlock<Block> CORN_STALK_TOP;
	public static final DeferredBlock<Block> CARROTS;
	public static final DeferredBlock<Block> POTATOES;
	public static final DeferredBlock<Block> BRONZE_PLATE;
	public static final DeferredBlock<Block> METAL_PLATE_MOLD;
	public static final DeferredBlock<Block> CLAY_METAL_PLATE_MOLD;
	public static final DeferredBlock<Block> WOODEN_PLATE;
	public static final DeferredBlock<Block> STEEL_PLATE;
	public static final DeferredBlock<Block> DIAMOND_PLATE;
	public static final DeferredBlock<Block> NETHERITE_PLATE;
	public static final DeferredBlock<Block> SPELT_SEEDS;
	public static final DeferredBlock<Block> RYE_SEEDS;
	public static final DeferredBlock<Block> WILD_RYE;
	public static final DeferredBlock<Block> WILD_SPELT;
	public static final DeferredBlock<Block> RASPBERRY_PLANT;
	public static final DeferredBlock<Block> WHITE_HORSE;
	public static final DeferredBlock<Block> WHITE_HORSE_STOCKING;
	public static final DeferredBlock<Block> WHITE_HORSE_FIELD;
	public static final DeferredBlock<Block> WHITE_HORSE_WHITE_DOTS;
	public static final DeferredBlock<Block> WHITE_HORSE_BLACK_DOTS;
	public static final DeferredBlock<Block> CREAMY_HORSE;
	public static final DeferredBlock<Block> CREAMY_HORSE_STOCKINGS;
	public static final DeferredBlock<Block> CREAMY_HORSE_FIELD;
	public static final DeferredBlock<Block> CREAMY_HORSE_WHITE_DOTS;
	public static final DeferredBlock<Block> CREAMY_HORSE_BLACK_DOTS;
	public static final DeferredBlock<Block> CHESTNUT_HORSE;
	public static final DeferredBlock<Block> BROWN_HORSE;
	public static final DeferredBlock<Block> BLACK_HORSE;
	public static final DeferredBlock<Block> GRAY_HORSE;
	public static final DeferredBlock<Block> DARK_BROWN_HORSE;
	public static final DeferredBlock<Block> CHESTNUT_HORSE_STOCKINGS;
	public static final DeferredBlock<Block> CHESTNUT_HORSE_FIELD;
	public static final DeferredBlock<Block> CHESTNUT_HORSE_WHITE_DOTS;
	public static final DeferredBlock<Block> CHESTNUT_HORSE_BLACK_DOTS;
	public static final DeferredBlock<Block> BROWN_HORSE_STOCKINGS;
	public static final DeferredBlock<Block> BROWN_HORSE_FIELD;
	public static final DeferredBlock<Block> BROWN_HORSE_WHITE_DOTS;
	public static final DeferredBlock<Block> BROWN_HORSE_BLACK_DOTS;
	public static final DeferredBlock<Block> BLACK_HORSE_STOCKINGS;
	public static final DeferredBlock<Block> BLACK_HORSE_FIELD;
	public static final DeferredBlock<Block> BLACK_HORSE_WHITE_DOTS;
	public static final DeferredBlock<Block> BLACK_HORSE_BLACK_DOTS;
	public static final DeferredBlock<Block> GRAY_HORSE_STOCKINGS;
	public static final DeferredBlock<Block> GRAY_HORSE_FIELD;
	public static final DeferredBlock<Block> GRAY_HORSE_WHITE_DOTS;
	public static final DeferredBlock<Block> GRAY_HORSE_BLACK_DOTS;
	public static final DeferredBlock<Block> DARK_BROWN_HORSE_STOCKINGS;
	public static final DeferredBlock<Block> DARK_BROWN_HORSE_FIELD;
	public static final DeferredBlock<Block> DARK_BROWN_HORSE_WHITE_DOTS;
	public static final DeferredBlock<Block> DARK_BROWN_HORSE_BLACK_DOTS;
	public static final DeferredBlock<Block> SKINNED_HORSE;
	public static final DeferredBlock<Block> HORSE_LEG;
	public static final DeferredBlock<Block> HORSE_HEAD;
	public static final DeferredBlock<Block> STONE_SALT_DEPOSIT;
	static {
		FLINTBLOCK = REGISTRY.register("flintblock", FlintblockBlock::new);
		STONE_ROCK_BLOC = REGISTRY.register("stone_rock_bloc", StoneRockBlocBlock::new);
		TIN_ORE = REGISTRY.register("tin_ore", TinOreBlock::new);
		FORGE = REGISTRY.register("forge", ForgeBlock::new);
		METAL_REFINING_TABLE = REGISTRY.register("metal_refining_table", MetalRefiningTableBlock::new);
		CLAY_CRUCIBLE = REGISTRY.register("clay_crucible", ClayCrucibleBlock::new);
		CRUCIBLE = REGISTRY.register("crucible", CrucibleBlock::new);
		AXE_HEAD_MOLD = REGISTRY.register("axe_head_mold", AxeHeadMoldBlock::new);
		PICKAXE_HEAD_MOLD = REGISTRY.register("pickaxe_head_mold", PickaxeHeadMoldBlock::new);
		SWORD_BLADE_MOLD = REGISTRY.register("sword_blade_mold", SwordBladeMoldBlock::new);
		HOE_HEAD_MOLD = REGISTRY.register("hoe_head_mold", HoeHeadMoldBlock::new);
		SHOVEL_HEAD_MOLD = REGISTRY.register("shovel_head_mold", ShovelHeadMoldBlock::new);
		SAW_BLADE_MOLD = REGISTRY.register("saw_blade_mold", SawBladeMoldBlock::new);
		HAMMER_HEAD_MOLD = REGISTRY.register("hammer_head_mold", HammerHeadMoldBlock::new);
		CLAY_SWORD_BLADE_MOLD = REGISTRY.register("clay_sword_blade_mold", ClaySwordBladeMoldBlock::new);
		CLAY_PICKAXE_HEAD_MOLD = REGISTRY.register("clay_pickaxe_head_mold", ClayPickaxeHeadMoldBlock::new);
		CLAY_AXE_HEAD_MOLD = REGISTRY.register("clay_axe_head_mold", ClayAxeHeadMoldBlock::new);
		CLAY_SHOVEL_HEAD_MOLD = REGISTRY.register("clay_shovel_head_mold", ClayShovelHeadMoldBlock::new);
		CLAY_HOE_BLADE_MOLD = REGISTRY.register("clay_hoe_blade_mold", ClayHoeBladeMoldBlock::new);
		CLAY_HAMMER_HEAD_MOLD = REGISTRY.register("clay_hammer_head_mold", ClayHammerHeadMoldBlock::new);
		CLAY_SAW_BLADE_MOLD = REGISTRY.register("clay_saw_blade_mold", ClaySawBladeMoldBlock::new);
		BLOCK_OF_BRONZE = REGISTRY.register("block_of_bronze", BlockOfBronzeBlock::new);
		ANDESITE_ROCK_BLOCK = REGISTRY.register("andesite_rock_block", AndesiteRockBlockBlock::new);
		GRANITE_ROCK_BLOCK = REGISTRY.register("granite_rock_block", GraniteRockBlockBlock::new);
		DIORITE_ROCK_B_LOCK = REGISTRY.register("diorite_rock_b_lock", DioriteRockBLockBlock::new);
		DRIPSTONE_ROCK_BLOCK = REGISTRY.register("dripstone_rock_block", DripstoneRockBlockBlock::new);
		CALCITE_ROCK_BLOCK = REGISTRY.register("calcite_rock_block", CalciteRockBlockBlock::new);
		TUFF_ROCK_BLOCK = REGISTRY.register("tuff_rock_block", TuffRockBlockBlock::new);
		MOSSY_STONE_ROCK_BLOCK = REGISTRY.register("mossy_stone_rock_block", MossyStoneRockBlockBlock::new);
		NETHERRACK_ROCK_BLOCK = REGISTRY.register("netherrack_rock_block", NetherrackRockBlockBlock::new);
		END_STONE_ROCK_BLOCK = REGISTRY.register("end_stone_rock_block", EndStoneRockBlockBlock::new);
		BLACKSTONE_ROCK_BLOCK = REGISTRY.register("blackstone_rock_block", BlackstoneRockBlockBlock::new);
		BASALT_ROCK_BLOCK = REGISTRY.register("basalt_rock_block", BasaltRockBlockBlock::new);
		DEEPSLATE_ROCK_BLOCK = REGISTRY.register("deepslate_rock_block", DeepslateRockBlockBlock::new);
		BLOCK_OF_RAW_TIN = REGISTRY.register("block_of_raw_tin", BlockOfRawTinBlock::new);
		BLOCK_OF_TIN = REGISTRY.register("block_of_tin", BlockOfTinBlock::new);
		SAND_SALT_DEPOSIT = REGISTRY.register("sand_salt_deposit", SandSaltDepositBlock::new);
		KNIFE_BLADE_MOLD = REGISTRY.register("knife_blade_mold", KnifeBladeMoldBlock::new);
		CLAY_KNIFE_MOLD = REGISTRY.register("clay_knife_mold", ClayKnifeMoldBlock::new);
		MANGANESE_ORE = REGISTRY.register("manganese_ore", ManganeseOreBlock::new);
		DEEPSLATE_MANGANESE_ORE = REGISTRY.register("deepslate_manganese_ore", DeepslateManganeseOreBlock::new);
		BLOCK_OF_STEEL = REGISTRY.register("block_of_steel", BlockOfSteelBlock::new);
		BLOCK_OF_MANGANESE = REGISTRY.register("block_of_manganese", BlockOfManganeseBlock::new);
		BLOCK_OF_RAW_MANGANESE = REGISTRY.register("block_of_raw_manganese", BlockOfRawManganeseBlock::new);
		BLOCK_OF_RAW_REDSTONE = REGISTRY.register("block_of_raw_redstone", BlockOfRawRedstoneBlock::new);
		MINERAL_PROCESSING_TABLE = REGISTRY.register("mineral_processing_table", MineralProcessingTableBlock::new);
		EMBEDDED_OBSIDIAN = REGISTRY.register("embedded_obsidian", EmbeddedObsidianBlock::new);
		COPPER_ROCK_BLOCK = REGISTRY.register("copper_rock_block", CopperRockBlockBlock::new);
		APPLE_OAK_LEAVES = REGISTRY.register("apple_oak_leaves", AppleOakLeavesBlock::new);
		APPLE_TREE_SAPLING = REGISTRY.register("apple_tree_sapling", AppleTreeSaplingBlock::new);
		APPLE = REGISTRY.register("apple", AppleBlock::new);
		INGOT_MOLD = REGISTRY.register("ingot_mold", IngotMoldBlock::new);
		INGOT_CLAY_MOLD = REGISTRY.register("ingot_clay_mold", IngotClayMoldBlock::new);
		HEMP = REGISTRY.register("hemp", HempBlock::new);
		LIMESTONE_ROCK = REGISTRY.register("limestone_rock", LimestoneRockBlock::new);
		VERIDIUM_ROCK = REGISTRY.register("veridium_rock", VeridiumRockBlock::new);
		OCHRUM_ROCK = REGISTRY.register("ochrum_rock", OchrumRockBlock::new);
		CRIMSITE_ROCK = REGISTRY.register("crimsite_rock", CrimsiteBlockBlock::new);
		SCORCHIA_ROCK = REGISTRY.register("scorchia_rock", ScorchiaRockBlock::new);
		ASURINE_CRYSTAL = REGISTRY.register("asurine_crystal", AsurineCrystalBlock::new);
		SCORIA_ROCK = REGISTRY.register("scoria_rock", ScoriaRockBlock::new);
		SHALE = REGISTRY.register("shale", ShaleBlock::new);
		SHALE_ROCK = REGISTRY.register("shale_rock", ShaleRockBlock::new);
		TITANIUM_ORE = REGISTRY.register("titanium_ore", TitaniumOreBlock::new);
		DEEPSLATE_TITANIUM_ORE = REGISTRY.register("deepslate_titanium_ore", DeepslateTitaniumOreBlock::new);
		SHALE_TITANIUM_ORE = REGISTRY.register("shale_titanium_ore", ShaleTitaniumOreBlock::new);
		BLOCK_OF_TITANIUM = REGISTRY.register("block_of_titanium", BlockOfTitaniumBlock::new);
		BLOCK_OF_RAW_TITANIUM = REGISTRY.register("block_of_raw_titanium", BlockOfRawTitaniumBlock::new);
		RADIANT_LOG = REGISTRY.register("radiant_log", RadiantLogBlock::new);
		STRIPPED_RADIANT_LOG = REGISTRY.register("stripped_radiant_log", StrippedRadiantLogBlock::new);
		RADIANT_PLANKS = REGISTRY.register("radiant_planks", RadiantPlanksBlock::new);
		RADIATED_LEAVES = REGISTRY.register("radiated_leaves", RadiatedLeavesBlock::new);
		RADIATED_SAPLING = REGISTRY.register("radiated_sapling", RadiatedSaplingBlock::new);
		RADIATED_STAIRS = REGISTRY.register("radiated_stairs", RadiatedStairsBlock::new);
		RADIATED_SLAB = REGISTRY.register("radiated_slab", RadiatedSlabBlock::new);
		RADIATED_FENCE = REGISTRY.register("radiated_fence", RadiatedFenceBlock::new);
		RADIATED_FENCE_GATE = REGISTRY.register("radiated_fence_gate", RadiatedFenceGateBlock::new);
		RADIATED_PRESSURE_PLATE = REGISTRY.register("radiated_pressure_plate", RadiatedPressurePlateBlock::new);
		RADIATED_BUTTON = REGISTRY.register("radiated_button", RadiatedButtonBlock::new);
		RADIATED_SHALE = REGISTRY.register("radiated_shale", RadiatedGrassBlock::new);
		THIN_RADIATED_VINES = REGISTRY.register("thin_radiated_vines", ThinRadiatedVinesBlock::new);
		THIN_RADIATED_VINE_BASE = REGISTRY.register("thin_radiated_vine_base", ThinRadiatedVineBaseBlock::new);
		RADIATED_MOSS = REGISTRY.register("radiated_moss", RadiatedMossBlock::new);
		RADIATED_TALL_GRASS = REGISTRY.register("radiated_tall_grass", RadiatedTallGrassBlock::new);
		THICK_RADIATED_VINES = REGISTRY.register("thick_radiated_vines", ThickRadiatedVinesBlock::new);
		THICK_RADIATED_VINES_BASE = REGISTRY.register("thick_radiated_vines_base", ThickRadiatedVinesBaseBlock::new);
		RADIATED_ORCHID = REGISTRY.register("radiated_orchid", RadiatedOrchidBlock::new);
		SHALE_URANINITE_ORE = REGISTRY.register("shale_uraninite_ore", ShaleUraniumOreBlock::new);
		URANINITE_ORE = REGISTRY.register("uraninite_ore", UraniumOreBlock::new);
		DEEPSLATE_URANINITE_ORE = REGISTRY.register("deepslate_uraninite_ore", DeepslateUraniumOreBlock::new);
		BLOCK_OF_RAW_URANINITE = REGISTRY.register("block_of_raw_uraninite", BlockOfRawUraniniteBlock::new);
		POLISHED_SHALE = REGISTRY.register("polished_shale", PolishedShaleBlock::new);
		POLISHED_SHALE_BRICKS = REGISTRY.register("polished_shale_bricks", PolishedShaleBricksBlock::new);
		POLISHED_CHISELED_SHALE = REGISTRY.register("polished_chiseled_shale", PolishedChiseledShaleBlock::new);
		POLISHED_SHALE_STAIRS = REGISTRY.register("polished_shale_stairs", PolishedShaleStairsBlock::new);
		POLISHED_SHALE_BRICK_STAIRS = REGISTRY.register("polished_shale_brick_stairs", PolishedShaleBrickStairsBlock::new);
		POLISHED_SHALE_SLAB = REGISTRY.register("polished_shale_slab", PolishedShaleSlabBlock::new);
		POLISHED_SHALE_BRICK_SLAB = REGISTRY.register("polished_shale_brick_slab", PolishedShaleBrickSlabBlock::new);
		POLISHED_SHALE_WALL = REGISTRY.register("polished_shale_wall", PolishedShaleWallBlock::new);
		POLOSHED_SHALE_BRICK_WALL = REGISTRY.register("poloshed_shale_brick_wall", PoloshedShaleBrickWallBlock::new);
		SHALE_STAIRS = REGISTRY.register("shale_stairs", ShaleStairsBlock::new);
		SHALE_SLAB = REGISTRY.register("shale_slab", ShaleSlabBlock::new);
		SHALE_WALL = REGISTRY.register("shale_wall", ShaleWallBlock::new);
		BLOCK_OF_URANIUM = REGISTRY.register("block_of_uranium", BlockOfUraniumBlock::new);
		URANIUM_ROD = REGISTRY.register("uranium_rod", UraniumRodBlock::new);
		RADIANT_TRAPDOOR = REGISTRY.register("radiant_trapdoor", RadiantTrapdoorBlock::new);
		RADIANT_DOOR = REGISTRY.register("radiant_door", RadiantDoorBlock::new);
		STEEL_DOOR = REGISTRY.register("steel_door", SteelDoorBlock::new);
		STEEL_TRAPDOOR = REGISTRY.register("steel_trapdoor", SteelTrapdoorBlock::new);
		TURANITE_BLOCK = REGISTRY.register("turanite_block", TuraniteBlockBlock::new);
		ADVANCED_ALLOY_FORGE = REGISTRY.register("advanced_alloy_forge", AdvancedAlloyForgeBlock::new);
		PLATED_DIAMOND_BLOCK = REGISTRY.register("plated_diamond_block", PlatedDiamondBlockBlock::new);
		NETHERITE_SCRAP_BLOCK = REGISTRY.register("netherite_scrap_block", NetheriteScrapBlockBlock::new);
		SILVER_ORE = REGISTRY.register("silver_ore", SilverOreBlock::new);
		RAW_SILVER_BLOCK = REGISTRY.register("raw_silver_block", RawSilverBlockBlock::new);
		SILVER_BLOCK = REGISTRY.register("silver_block", SilverBlockBlock::new);
		SAPPHIRE_ORE = REGISTRY.register("sapphire_ore", SapphireOreBlock::new);
		DEEPSLATE_SAPPHIRE_ORE = REGISTRY.register("deepslate_sapphire_ore", DeepslateSapphireOreBlock::new);
		SAPPHIRE_BLOCK = REGISTRY.register("sapphire_block", SapphireBlockBlock::new);
		NITRE_BLOCK = REGISTRY.register("nitre_block", NitreBlockBlock::new);
		RUNE_CLAY_MOLD = REGISTRY.register("rune_clay_mold", RuneClayMoldBlock::new);
		RUNE_MOLD = REGISTRY.register("rune_mold", RuneMoldBlock::new);
		RUNE_MAGIC_INFUSER = REGISTRY.register("rune_magic_infuser", RuneMagicInfuserBlock::new);
		RUBY_ORE = REGISTRY.register("ruby_ore", RubyOreBlock::new);
		DEEPSLATE_RUBY_ORE = REGISTRY.register("deepslate_ruby_ore", DeepslateRubyOreBlock::new);
		BLOCK_OF_RUBY = REGISTRY.register("block_of_ruby", BlockOfRubyBlock::new);
		AMBER_ORE = REGISTRY.register("amber_ore", AmberOreBlock::new);
		DEEPSLATE_AMBER_ORE = REGISTRY.register("deepslate_amber_ore", DeepslateAmberOreBlock::new);
		BLOCK_OF_AMBER = REGISTRY.register("block_of_amber", BlockOfAmberBlock::new);
		WISTERIA_LOG = REGISTRY.register("wisteria_log", WisteriaLogBlock::new);
		WISTERIA_LEAVES = REGISTRY.register("wisteria_leaves", WisteriaLeavesBlock::new);
		FLOWING_WISTERIA_LEAVES = REGISTRY.register("flowing_wisteria_leaves", FlowingWisteriaLeavesBlock::new);
		WISTERIA_SPIDER_LILY = REGISTRY.register("wisteria_spider_lily", WisteriaSpiderLilyBlock::new);
		WISTERIA_SAPLING = REGISTRY.register("wisteria_sapling", WisteriaSaplingBlock::new);
		WISTERIA_LEAF_LITTER = REGISTRY.register("wisteria_leaf_litter", WisteriaLeafLitterBlock::new);
		WISTERIA_FLOWER_UPPER = REGISTRY.register("wisteria_flower_upper", WisteriaFlowerUpperBlock::new);
		WISTERIA_FLOWER_LOWER = REGISTRY.register("wisteria_flower_lower", WisteriaFlowerLowerBlock::new);
		DEEPSLATE_TIN_ORE = REGISTRY.register("deepslate_tin_ore", DeepslateTinOreBlock::new);
		OBSIDIAN_ROCK = REGISTRY.register("obsidian_rock", ObsidianRockBlockBlock::new);
		HEMATITE_ORE = REGISTRY.register("hematite_ore", HematiteOreBlock::new);
		DEEPSLATE_HEMATITE_ORE = REGISTRY.register("deepslate_hematite_ore", DeepslateHematiteOreBlock::new);
		BASALT_HEMATITE_ORE = REGISTRY.register("basalt_hematite_ore", BasaltHematiteOreBlock::new);
		HEMATITE_BLOCK = REGISTRY.register("hematite_block", HematiteBlockBlock::new);
		MAGNETITE_ORE = REGISTRY.register("magnetite_ore", MagnetiteOreBlock::new);
		DEEPSLATE_MAGNETITE_ORE = REGISTRY.register("deepslate_magnetite_ore", DeepslateMagnetiteOreBlock::new);
		BASALT_MAGNETITE_ORE = REGISTRY.register("basalt_magnetite_ore", BasaltMagenetiteOreBlock::new);
		MAGNETITE_BLOCK = REGISTRY.register("magnetite_block", MagnetiteBlockBlock::new);
		MALACHITE_ORE = REGISTRY.register("malachite_ore", MalachiteOreBlock::new);
		DEEPSLATE_MALACHITE_ORE = REGISTRY.register("deepslate_malachite_ore", DeepslateMalachiteOreBlock::new);
		RAW_MALACHITE_BLOCK = REGISTRY.register("raw_malachite_block", RawMalachiteBlockBlock::new);
		AZURITE_ORE = REGISTRY.register("azurite_ore", AzuriteOreBlock::new);
		DEEPSLATE_AZURITE_ORE = REGISTRY.register("deepslate_azurite_ore", DeepslateAzuriteOreBlock::new);
		RAW_AZURITE_BLOCK = REGISTRY.register("raw_azurite_block", RawAzuriteBlockBlock::new);
		CASSITERITE_ORE = REGISTRY.register("cassiterite_ore", CassiteriteOreBlock::new);
		DEEPSLATE_CASSITERITE_ORE = REGISTRY.register("deepslate_cassiterite_ore", DeepslateCassiteriteOreBlock::new);
		RAW_CASSITERITE_BLOCK = REGISTRY.register("raw_cassiterite_block", RawCassiteriteBlockBlock::new);
		DEEPSLATE_SILVER_ORE = REGISTRY.register("deepslate_silver_ore", DeepslateNativeSilverOreBlock::new);
		ARGENTITE_ORE = REGISTRY.register("argentite_ore", ArgentiteOreBlock::new);
		DEEPSLATE_ARGENTITE_ORE = REGISTRY.register("deepslate_argentite_ore", DeepslateArgentiteOreBlock::new);
		BASALT_ARGENTITE_ORE = REGISTRY.register("basalt_argentite_ore", BasaltArgentiteOreBlock::new);
		ARGENTITE_BLOCK = REGISTRY.register("argentite_block", ArgentiteBlockBlock::new);
		BASALT_URANINITE_ORE = REGISTRY.register("basalt_uraninite_ore", BasaltUraniniteOreBlock::new);
		CALAVERITE_ORE = REGISTRY.register("calaverite_ore", CalaveriteOreBlock::new);
		DEEPSLATE_CALAVERITE_ORE = REGISTRY.register("deepslate_calaverite_ore", DeepslateCalaveriteOreBlock::new);
		BASALT_CALAVERITE_ORE = REGISTRY.register("basalt_calaverite_ore", BasaltCalaveriteOreBlock::new);
		CALAVERITE_BLOCK = REGISTRY.register("calaverite_block", CalaveriteBlockBlock::new);
		MANGANITE_ORE = REGISTRY.register("manganite_ore", ManganiteOreBlock::new);
		DEEPSLATE_MANGANITE_ORE = REGISTRY.register("deepslate_manganite_ore", DeepslateManganiteOreBlock::new);
		BASALT_PYROLUSITE_ORE = REGISTRY.register("basalt_pyrolusite_ore", BasaltManganiteOreBlock::new);
		MANGANITE_BLOCK = REGISTRY.register("manganite_block", ManganiteBlockBlock::new);
		PYROLUSITE_ORE = REGISTRY.register("pyrolusite_ore", PyrolusiteOreBlock::new);
		PYROLUSITE_BLOCK = REGISTRY.register("pyrolusite_block", PyrolusiteBlockBlock::new);
		DEEPSLATE_PYROLUSITE_ORE = REGISTRY.register("deepslate_pyrolusite_ore", DeepslatePyrolusiteOreBlock::new);
		URANOPHANE_ORE = REGISTRY.register("uranophane_ore", UranophaneOreBlock::new);
		DEEPSLATE_URANOPHANE_ORE = REGISTRY.register("deepslate_uranophane_ore", DeepslateUranophaneOreBlock::new);
		BASALT_URANOPHANE_ORE = REGISTRY.register("basalt_uranophane_ore", BasaltUranophaneOreBlock::new);
		SHALE_URANOPHANE_ORE = REGISTRY.register("shale_uranophane_ore", ShaleUranophaneOreBlock::new);
		URANOPHANE_BLOCK = REGISTRY.register("uranophane_block", UranophaneBlockBlock::new);
		ILMENITE_ORE = REGISTRY.register("ilmenite_ore", IlmeniteOreBlock::new);
		DEEPSLATE_ILMENITE_ORE = REGISTRY.register("deepslate_ilmenite_ore", DeepslateIlmeniteOreBlock::new);
		BASALT_ILMENITE_ORE = REGISTRY.register("basalt_ilmenite_ore", BasaltIlmeniteOreBlock::new);
		ILMENITE_BLOCK = REGISTRY.register("ilmenite_block", IlmeniteBlockBlock::new);
		KIMBERLITE_ROCK = REGISTRY.register("kimberlite_rock", KimberliteRockBlock::new);
		KIMBERLITE = REGISTRY.register("kimberlite", KimberliteBlock::new);
		KIMBERLITE_STALAGMITE_TOP = REGISTRY.register("kimberlite_stalagmite_top", KimberliteStalagmiteTopBlock::new);
		KIMBERLITE_STALAGMITE_MIDDLE = REGISTRY.register("kimberlite_stalagmite_middle", KimberliteStalagmiteMiddleBlock::new);
		KIMBERLITE_STALAGMITE_BASE = REGISTRY.register("kimberlite_stalagmite_base", KimberliteStalagmiteBaseBlock::new);
		KIMBERLITE_STALAGTITE_TIP = REGISTRY.register("kimberlite_stalagtite_tip", KimberliteStalagtiteTipBlock::new);
		KIMBERLITE_STALAGTITE_MIDDLE = REGISTRY.register("kimberlite_stalagtite_middle", KimberliteStalagtiteMiddleBlock::new);
		KIMBERLITE_STALAGTITE_BASE = REGISTRY.register("kimberlite_stalagtite_base", KimberliteStalagtiteBaseBlock::new);
		DEEPSLATE_STALAGMITE_TOP = REGISTRY.register("deepslate_stalagmite_top", DeepslateStalagmiteTopBlock::new);
		DEEPSLATE_STALAGMITE_MIDDLE = REGISTRY.register("deepslate_stalagmite_middle", DeepslateStalagmiteMiddleBlock::new);
		DEEPSLATE_STALAGMITE_BASE = REGISTRY.register("deepslate_stalagmite_base", DeepslateStalagmiteBaseBlock::new);
		DEEPSLATE_STALAGTITE_TIP = REGISTRY.register("deepslate_stalagtite_tip", DeepslateStalagtiteTipBlock::new);
		DEEPSLATE_STALAGTITE_MIDDLE = REGISTRY.register("deepslate_stalagtite_middle", DeepslateStalagtiteMiddleBlock::new);
		DEEPSLATE_STALAGTITE_BASE = REGISTRY.register("deepslate_stalagtite_base", DeepslateStalagtiteBaseBlock::new);
		STONE_STALAGMITE_TOP = REGISTRY.register("stone_stalagmite_top", StoneStalagmiteTopBlock::new);
		STONE_STALAGMITE_MIDDLE = REGISTRY.register("stone_stalagmite_middle", StoneStalagmiteMiddleBlock::new);
		STONE_STALAGMITE_BASE = REGISTRY.register("stone_stalagmite_base", StoneStalagmiteBaseBlock::new);
		STONE_STALAGTITE_TIP = REGISTRY.register("stone_stalagtite_tip", StoneStalagtiteTipBlock::new);
		STONE_STALAGTITE_MIDDLE = REGISTRY.register("stone_stalagtite_middle", StoneStalagtiteMiddleBlock::new);
		STONE_STALAGTITE_BASE = REGISTRY.register("stone_stalagtite_base", StoneStalagtiteBaseBlock::new);
		BASALT_STALAGMITE_TOP = REGISTRY.register("basalt_stalagmite_top", BasaltStalagmiteTopBlock::new);
		BASALT_STALAGMITE_MIDDLE = REGISTRY.register("basalt_stalagmite_middle", BasaltStalagmiteMiddleBlock::new);
		BASALT_STALAGMITE_BASE = REGISTRY.register("basalt_stalagmite_base", BasaltStalagmiteBaseBlock::new);
		BASALT_STALAGTITE_TIP = REGISTRY.register("basalt_stalagtite_tip", BasaltStalagtiteTipBlock::new);
		BASALT_STALAGTITE_MIDDLE = REGISTRY.register("basalt_stalagtite_middle", BasaltStalagtiteMiddleBlock::new);
		BASALT_STALAGTITE_BASE = REGISTRY.register("basalt_stalagtite_base", BasaltStalagtiteBaseBlock::new);
		BASALT_SAPPHIRE_ORE = REGISTRY.register("basalt_sapphire_ore", BasaltSapphireOreBlock::new);
		KIMBERLITE_SAPPHIRE_ORE = REGISTRY.register("kimberlite_sapphire_ore", KimberliteSapphireOreBlock::new);
		BASALT_DIAMOND_ORE = REGISTRY.register("basalt_diamond_ore", BasaltDiamondOreBlock::new);
		KIMBERLITE_DIAMOND_ORE = REGISTRY.register("kimberlite_diamond_ore", KimberliteDiamondOreBlock::new);
		BASALT_EMERALD_ORE = REGISTRY.register("basalt_emerald_ore", BasaltEmeraldOreBlock::new);
		KIMBERLITE_EMERALD_ORE = REGISTRY.register("kimberlite_emerald_ore", KimberliteEmeraldOreBlock::new);
		BASALT_RUBY_ORE = REGISTRY.register("basalt_ruby_ore", BasaltRubyOreBlock::new);
		KIMBERLITE_RUBY_ORE = REGISTRY.register("kimberlite_ruby_ore", KimberliteRubyOreBlock::new);
		BASALT_LAPIS_ORE = REGISTRY.register("basalt_lapis_ore", BasaltLazuriteOreBlock::new);
		KIMBERLITE_LAPIS_ORE = REGISTRY.register("kimberlite_lapis_ore", KimberliteLapisOreBlock::new);
		BASALT_AMBER_ORE = REGISTRY.register("basalt_amber_ore", BasaltAmberOreBlock::new);
		KIMBERLITE_AMBER_ORE = REGISTRY.register("kimberlite_amber_ore", KimberliteAmberOreBlock::new);
		SULFUR_ORE = REGISTRY.register("sulfur_ore", SulfurOreBlock::new);
		NITRE_POWDER = REGISTRY.register("nitre_powder", NitrePowderBlock::new);
		STRIPPED_WISTERIA_LOG = REGISTRY.register("stripped_wisteria_log", StrippedWisteriaLogBlock::new);
		WISTERIA_WOOD = REGISTRY.register("wisteria_wood", WisteriaWoodBlock::new);
		WISTERIA_PLANKS = REGISTRY.register("wisteria_planks", WisteriaPlanksBlock::new);
		WISTERIA_STAIRS = REGISTRY.register("wisteria_stairs", WisteriaStairsBlock::new);
		WISTERIA_SLAB = REGISTRY.register("wisteria_slab", WisteriaSlabBlock::new);
		WISTERIA_FENCE = REGISTRY.register("wisteria_fence", WisteriaFenceBlock::new);
		WISTERIA_FENCE_GATE = REGISTRY.register("wisteria_fence_gate", WisteriaFenceGateBlock::new);
		WISTERIA_DOOR = REGISTRY.register("wisteria_door", WisteriaDoorBlock::new);
		WISTERIA_TRAPDOOR = REGISTRY.register("wisteria_trapdoor", WisteriaTrapdoorBlock::new);
		WISTERIA_BUTTON = REGISTRY.register("wisteria_button", WisteriaButtonBlock::new);
		WISTERIA_PRESSURE_PLATE = REGISTRY.register("wisteria_pressure_plate", WisteriaPressurePlateBlock::new);
		PURE_SALT_BLOCK = REGISTRY.register("pure_salt_block", PureSaltBlockBlock::new);
		SALT_DEPOSIT = REGISTRY.register("salt_deposit", SaltDepositBlock::new);
		SMALL_TROUGH = REGISTRY.register("small_trough", SmallTroughBlock::new);
		SMALL_PALM_LOG = REGISTRY.register("small_palm_log", SmallPalmLogBlock::new);
		PALM_LOG = REGISTRY.register("palm_log", PalmLogBlock::new);
		PALM_LOG_BARKED_TOP = REGISTRY.register("palm_log_barked_top", PalmLogBarkedTopBlock::new);
		COCONUT = REGISTRY.register("coconut", CoconutBlock::new);
		COCONUT_MATURE = REGISTRY.register("coconut_mature", CoconutMatureBlock::new);
		PALM_CROWN = REGISTRY.register("palm_crown", PalmCrownBlock::new);
		PALM_LEAVES = REGISTRY.register("palm_leaves", PalmLeavesBlock::new);
		ALOE_VERA = REGISTRY.register("aloe_vera", AloeVeraBlock::new);
		COCONUT_SEEDLING = REGISTRY.register("coconut_seedling", CoconutSeedlingBlock::new);
		STRAWBERRY_PLANT = REGISTRY.register("strawberry_plant", StrawberryPlantBlock::new);
		BANANA_JUNGLE_LOG = REGISTRY.register("banana_jungle_log", BananaJungleLogBlock::new);
		SMALL_BANANA_JUNGLE_LOG = REGISTRY.register("small_banana_jungle_log", SmallBananaJungleLogBlock::new);
		BANANA_LEAVES = REGISTRY.register("banana_leaves", BananaLeavesBlock::new);
		BANANA_CLUSTER = REGISTRY.register("banana_cluster", BananaBlock::new);
		BANANA_GROW_BLOCK = REGISTRY.register("banana_grow_block", BananaGrowBlockBlock::new);
		RADIATED_SIGN = REGISTRY.register("radiated_sign", RadiatedSignBlock::new);
		RADIATED_WALL_SIGN = REGISTRY.register("radiated_wall_sign", RadiatedWallSignBlock::new);
		HANGING_RADIATED_SIGN = REGISTRY.register("hanging_radiated_sign", HangingRadiatedSignBlock::new);
		HANGING_RADIATED_WALL_SIGN = REGISTRY.register("hanging_radiated_wall_sign", HangingRadiatedWallSignBlock::new);
		WISTERIA_SIGN = REGISTRY.register("wisteria_sign", WisteriaSignBlock::new);
		WISTERIA_WALL_SIGN = REGISTRY.register("wisteria_wall_sign", WisteriaWallSignBlock::new);
		HANGING_WISTERIA_SIGN = REGISTRY.register("hanging_wisteria_sign", HangingWisteriaSignBlock::new);
		HANGING_WISTERIA_WALL_SIGN = REGISTRY.register("hanging_wisteria_wall_sign", HangingWisteriaWallSignBlock::new);
		MANDARIN_LEAVES = REGISTRY.register("mandarin_leaves", MandarinLeavesBlock::new);
		MANDARIN_LOG = REGISTRY.register("mandarin_log", MandarinLogBlock::new);
		MANDARIN_FRUIT = REGISTRY.register("mandarin_fruit", MandarinFruitBlock::new);
		MANDARIN_SAPLING = REGISTRY.register("mandarin_sapling", MandarinSaplingBlock::new);
		CURSED_STONE_TILES = REGISTRY.register("cursed_stone_tiles", CursedStoneTilesBlock::new);
		CHISELED_CURSED_STONE = REGISTRY.register("chiseled_cursed_stone", ChiseledCursedStoneBlock::new);
		CURSED_STONE = REGISTRY.register("cursed_stone", CursedStoneBlock::new);
		CURSED_STONE_BARS = REGISTRY.register("cursed_stone_bars", CursedStoneBarsBlock::new);
		CURSED_STONE_TILE_SLAB = REGISTRY.register("cursed_stone_tile_slab", CursedStoneTileSlabBlock::new);
		CURSED_STONE_TILE_STAIRS = REGISTRY.register("cursed_stone_tile_stairs", CursedStoneTileStairsBlock::new);
		CURSED_STONE_SLAB = REGISTRY.register("cursed_stone_slab", CursedStoneSlabBlock::new);
		CURSED_STONE_STAIRS = REGISTRY.register("cursed_stone_stairs", CursedStoneStairsBlock::new);
		CURSED_STONE_WALL = REGISTRY.register("cursed_stone_wall", CursedStoneWallBlock::new);
		SLIM_CURSED_STONE_WALL = REGISTRY.register("slim_cursed_stone_wall", SlimCursedStoneWallBlock::new);
		CRACKED_CURSED_STONE_TILES = REGISTRY.register("cracked_cursed_stone_tiles", CrackedCursedStoneTilesBlock::new);
		CRACKED_CURSED_STONE_WALL = REGISTRY.register("cracked_cursed_stone_wall", CrackedCursedStoneWallBlock::new);
		CURSED_STONE_WALL_STAIRS = REGISTRY.register("cursed_stone_wall_stairs", CursedStoneWallStairsBlock::new);
		CURSED_STONE_WALL_SLAB = REGISTRY.register("cursed_stone_wall_slab", CursedStoneWallSlabBlock::new);
		MILLSTONE = REGISTRY.register("millstone", MillstoneBlock::new);
		CAMPFIRE = REGISTRY.register("campfire", CampfireBlock::new);
		LOW_FERTILITY_FARMLAND = REGISTRY.register("low_fertility_farmland", LowFertilityFarmlandBlock::new);
		MEDIUM_FERTILITY_DIRT = REGISTRY.register("medium_fertility_dirt", MediumFertilityDirtBlock::new);
		MEDIUM_FERTILITY_GRASS = REGISTRY.register("medium_fertility_grass", MediumFertilityGrassBlock::new);
		HIGH_FERTILITY_DIRT = REGISTRY.register("high_fertility_dirt", HighFertilityDirtBlock::new);
		HIGH_FERTILITY_GRASS = REGISTRY.register("high_fertility_grass", HighFertilityGrassBlock::new);
		MEDIUM_FERTILITY_SOIL = REGISTRY.register("medium_fertility_soil", MediumFertilitySoilBlock::new);
		HIGH_FERTILITY_SOIL = REGISTRY.register("high_fertility_soil", HighFertilitySoilBlock::new);
		WILD_WHEAT = REGISTRY.register("wild_wheat", WildWheatBlock::new);
		WILD_CARROT = REGISTRY.register("wild_carrot", WildCarrotBlock::new);
		WILD_POTATOES = REGISTRY.register("wild_potatoes", WildPotatoesBlock::new);
		BEETROOT = REGISTRY.register("beetroot", BeetrootBlock::new);
		BLOCK_OF_CHARCOAL = REGISTRY.register("block_of_charcoal", BlockOfCharcoalBlock::new);
		BRITTLE_OBSIDIAN = REGISTRY.register("brittle_obsidian", BrittleObsidianBlock::new);
		ANTHRACITE_ORE = REGISTRY.register("anthracite_ore", AnthraciteOreBlock::new);
		DEEPSLATE_ANTHRACITE_ORE = REGISTRY.register("deepslate_anthracite_ore", DeepslateAnthraciteOreBlock::new);
		BASALT_ANTHRACITE_ORE = REGISTRY.register("basalt_anthracite_ore", BasaltAnthraciteOreBlock::new);
		ANTHRACITE_BLOCK = REGISTRY.register("anthracite_block", AnthraciteBlockBlock::new);
		LIGINITE_ORE = REGISTRY.register("liginite_ore", LiginiteOreBlock::new);
		DEEPSLATE_LIGINITE_ORE = REGISTRY.register("deepslate_liginite_ore", DeepslateLiginiteOreBlock::new);
		BASALT_LIGINITE_ORE = REGISTRY.register("basalt_liginite_ore", BasaltDeepslateOreBlock::new);
		LIGINITE_BLOCK = REGISTRY.register("liginite_block", LiginiteBlockBlock::new);
		COW_CARCASS = REGISTRY.register("cow_carcass", CowCarcassBlock::new);
		COW_LEG = REGISTRY.register("cow_leg", CowLegBlock::new);
		COW_HEAD = REGISTRY.register("cow_head", CowHeadBlock::new);
		SHEEP_CARCASS = REGISTRY.register("sheep_carcass", SheepCarcassBlock::new);
		SHEEP_LEG = REGISTRY.register("sheep_leg", SheepLegBlock::new);
		SHEEP_HEAD = REGISTRY.register("sheep_head", SheepHeadBlock::new);
		CHICKEN_CARCASS = REGISTRY.register("chicken_carcass", ChickenCarcassBlock::new);
		PIG_CARCASS = REGISTRY.register("pig_carcass", PigCarcassBlock::new);
		PIG_LEG = REGISTRY.register("pig_leg", PigLegBlock::new);
		PIG_HEAD = REGISTRY.register("pig_head", PigHeadBlock::new);
		GOAT_CARCASS = REGISTRY.register("goat_carcass", GoatCarcassBlock::new);
		GOAT_LEG = REGISTRY.register("goat_leg", GoatLegBlock::new);
		GOAT_HEAD = REGISTRY.register("goat_head", GoatHeadBlock::new);
		DRYING_RACK = REGISTRY.register("drying_rack", DryingRackBlock::new);
		TANNING_BARREL = REGISTRY.register("tanning_barrel", TanningBarrelBlock::new);
		WHEAT_CROP = REGISTRY.register("wheat_crop", WheatCropBlock::new);
		CORN_STALK_BOTTOM = REGISTRY.register("corn_stalk_bottom", CornStalkBottomBlock::new);
		CORN_STALK_MIDDLE = REGISTRY.register("corn_stalk_middle", CornStalkMiddleBlock::new);
		CORN_STALK_TOP = REGISTRY.register("corn_stalk_top", CornStalkTopBlock::new);
		CARROTS = REGISTRY.register("carrots", CarrotsBlock::new);
		POTATOES = REGISTRY.register("potatoes", PotatoesBlock::new);
		BRONZE_PLATE = REGISTRY.register("bronze_plate", BronzePlateBlock::new);
		METAL_PLATE_MOLD = REGISTRY.register("metal_plate_mold", MetalPlateMoldBlock::new);
		CLAY_METAL_PLATE_MOLD = REGISTRY.register("clay_metal_plate_mold", ClayMetalPlateMoldBlock::new);
		WOODEN_PLATE = REGISTRY.register("wooden_plate", WoodenPlateBlock::new);
		STEEL_PLATE = REGISTRY.register("steel_plate", SteelPlateBlock::new);
		DIAMOND_PLATE = REGISTRY.register("diamond_plate", DiamondPlateBlock::new);
		NETHERITE_PLATE = REGISTRY.register("netherite_plate", NetheritePlateBlock::new);
		SPELT_SEEDS = REGISTRY.register("spelt_seeds", SpeltSeedsBlock::new);
		RYE_SEEDS = REGISTRY.register("rye_seeds", RyeSeedsBlock::new);
		WILD_RYE = REGISTRY.register("wild_rye", WildRyeBlock::new);
		WILD_SPELT = REGISTRY.register("wild_spelt", WildSpeltBlock::new);
		RASPBERRY_PLANT = REGISTRY.register("raspberry_plant", RaspberryPlantBlock::new);
		WHITE_HORSE = REGISTRY.register("white_horse", WhiteHorseBlock::new);
		WHITE_HORSE_STOCKING = REGISTRY.register("white_horse_stocking", WhiteHorseStockingBlock::new);
		WHITE_HORSE_FIELD = REGISTRY.register("white_horse_field", WhiteHorseFieldBlock::new);
		WHITE_HORSE_WHITE_DOTS = REGISTRY.register("white_horse_white_dots", WhiteHorseWhiteDotsBlock::new);
		WHITE_HORSE_BLACK_DOTS = REGISTRY.register("white_horse_black_dots", WhiteHorseBlackDotsBlock::new);
		CREAMY_HORSE = REGISTRY.register("creamy_horse", CreamyHorseBlock::new);
		CREAMY_HORSE_STOCKINGS = REGISTRY.register("creamy_horse_stockings", CreamyHorseStockingsBlock::new);
		CREAMY_HORSE_FIELD = REGISTRY.register("creamy_horse_field", CreamyHorseFieldBlock::new);
		CREAMY_HORSE_WHITE_DOTS = REGISTRY.register("creamy_horse_white_dots", CreamyHorseWhiteDotsBlock::new);
		CREAMY_HORSE_BLACK_DOTS = REGISTRY.register("creamy_horse_black_dots", CreamyHorseBlackDotsBlock::new);
		CHESTNUT_HORSE = REGISTRY.register("chestnut_horse", ChestnutHorseBlock::new);
		BROWN_HORSE = REGISTRY.register("brown_horse", BrownHorseBlock::new);
		BLACK_HORSE = REGISTRY.register("black_horse", BlackHorseBlock::new);
		GRAY_HORSE = REGISTRY.register("gray_horse", GrayHorseBlock::new);
		DARK_BROWN_HORSE = REGISTRY.register("dark_brown_horse", DarkBrownHorseBlock::new);
		CHESTNUT_HORSE_STOCKINGS = REGISTRY.register("chestnut_horse_stockings", ChestnutHorseStockingsBlock::new);
		CHESTNUT_HORSE_FIELD = REGISTRY.register("chestnut_horse_field", ChestnutHorseFieldBlock::new);
		CHESTNUT_HORSE_WHITE_DOTS = REGISTRY.register("chestnut_horse_white_dots", ChestnutHorseWhiteDotsBlock::new);
		CHESTNUT_HORSE_BLACK_DOTS = REGISTRY.register("chestnut_horse_black_dots", ChestnutHorseBlackDotsBlock::new);
		BROWN_HORSE_STOCKINGS = REGISTRY.register("brown_horse_stockings", BrownHorseStockingsBlock::new);
		BROWN_HORSE_FIELD = REGISTRY.register("brown_horse_field", BrownHorseFieldBlock::new);
		BROWN_HORSE_WHITE_DOTS = REGISTRY.register("brown_horse_white_dots", BrownHorseWhiteDotsBlock::new);
		BROWN_HORSE_BLACK_DOTS = REGISTRY.register("brown_horse_black_dots", BrownHorseBlackDotsBlock::new);
		BLACK_HORSE_STOCKINGS = REGISTRY.register("black_horse_stockings", BlackHorseStockingsBlock::new);
		BLACK_HORSE_FIELD = REGISTRY.register("black_horse_field", BlackHorseFieldBlock::new);
		BLACK_HORSE_WHITE_DOTS = REGISTRY.register("black_horse_white_dots", BlackHorseWhiteDotsBlock::new);
		BLACK_HORSE_BLACK_DOTS = REGISTRY.register("black_horse_black_dots", BlackHorseBlackDotsBlock::new);
		GRAY_HORSE_STOCKINGS = REGISTRY.register("gray_horse_stockings", GrayHorseStockingsBlock::new);
		GRAY_HORSE_FIELD = REGISTRY.register("gray_horse_field", GrayHorseFieldBlock::new);
		GRAY_HORSE_WHITE_DOTS = REGISTRY.register("gray_horse_white_dots", GrayHorseWhiteDotsBlock::new);
		GRAY_HORSE_BLACK_DOTS = REGISTRY.register("gray_horse_black_dots", GrayHorseBlackDotsBlock::new);
		DARK_BROWN_HORSE_STOCKINGS = REGISTRY.register("dark_brown_horse_stockings", DarkBrownHorseStockingsBlock::new);
		DARK_BROWN_HORSE_FIELD = REGISTRY.register("dark_brown_horse_field", DarkBrownHorseFieldBlock::new);
		DARK_BROWN_HORSE_WHITE_DOTS = REGISTRY.register("dark_brown_horse_white_dots", DarkBrownHorseWhiteDotsBlock::new);
		DARK_BROWN_HORSE_BLACK_DOTS = REGISTRY.register("dark_brown_horse_black_dots", DarkBrownHorseBlackDotsBlock::new);
		SKINNED_HORSE = REGISTRY.register("skinned_horse", SkinnedHorseBlock::new);
		HORSE_LEG = REGISTRY.register("horse_leg", HorseLegBlock::new);
		HORSE_HEAD = REGISTRY.register("horse_head", HorseHeadBlock::new);
		STONE_SALT_DEPOSIT = REGISTRY.register("stone_salt_deposit", StoneSaltDepositBlock::new);
	}

	// Start of user code block custom blocks
	// End of user code block custom blocks
	@EventBusSubscriber(Dist.CLIENT)
	public static class BlocksClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			AppleOakLeavesBlock.blockColorLoad(event);
			MediumFertilityGrassBlock.blockColorLoad(event);
			HighFertilityGrassBlock.blockColorLoad(event);
		}

		@SubscribeEvent
		public static void itemColorLoad(RegisterColorHandlersEvent.Item event) {
			AppleOakLeavesBlock.itemColorLoad(event);
			MediumFertilityGrassBlock.itemColorLoad(event);
			HighFertilityGrassBlock.itemColorLoad(event);
		}

		@SubscribeEvent
		public static void clientSetup(FMLClientSetupEvent event) {
			Sheets.addWoodType(SurvivalReimaginedModWoodTypes.HANGING_WISTERIA_SIGN_WOOD_TYPE);
			Sheets.addWoodType(SurvivalReimaginedModWoodTypes.RADIATED_SIGN_WOOD_TYPE);
			Sheets.addWoodType(SurvivalReimaginedModWoodTypes.WISTERIA_SIGN_WOOD_TYPE);
			Sheets.addWoodType(SurvivalReimaginedModWoodTypes.HANGING_RADIATED_SIGN_WOOD_TYPE);
		}
	}

	@SubscribeEvent
	public static void registerSigns(BlockEntityTypeAddBlocksEvent event) {
		event.modify(BlockEntityType.HANGING_SIGN, HANGING_WISTERIA_SIGN.get(), HANGING_WISTERIA_WALL_SIGN.get());
		event.modify(BlockEntityType.SIGN, RADIATED_SIGN.get(), RADIATED_WALL_SIGN.get());
		event.modify(BlockEntityType.SIGN, WISTERIA_SIGN.get(), WISTERIA_WALL_SIGN.get());
		event.modify(BlockEntityType.HANGING_SIGN, HANGING_RADIATED_SIGN.get(), HANGING_RADIATED_WALL_SIGN.get());
	}
}