
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.survivalreimagined.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.survivalreimagined.item.inventory.BackpackInventoryCapability;
import net.mcreator.survivalreimagined.item.inventory.AAFScriptureInventoryCapability;
import net.mcreator.survivalreimagined.item.ZombieFaceItem;
import net.mcreator.survivalreimagined.item.YieldUpgradeMKIIItem;
import net.mcreator.survivalreimagined.item.YieldUpgradeMKIIIItem;
import net.mcreator.survivalreimagined.item.YieldUpgradeItem;
import net.mcreator.survivalreimagined.item.YellowGlassShardItem;
import net.mcreator.survivalreimagined.item.WoodenSawItem;
import net.mcreator.survivalreimagined.item.WoodenRuneItem;
import net.mcreator.survivalreimagined.item.WoodenKnifeItem;
import net.mcreator.survivalreimagined.item.WoodenItem;
import net.mcreator.survivalreimagined.item.WoodenHammerItem;
import net.mcreator.survivalreimagined.item.WoodIngotItem;
import net.mcreator.survivalreimagined.item.WisteriaPlankItem;
import net.mcreator.survivalreimagined.item.WisteriaBarkItem;
import net.mcreator.survivalreimagined.item.WillowBarkRUItem;
import net.mcreator.survivalreimagined.item.WillowBarkItem;
import net.mcreator.survivalreimagined.item.WhiteSandstoneChunkItem;
import net.mcreator.survivalreimagined.item.WhiteSandPileItem;
import net.mcreator.survivalreimagined.item.WhiteGlassShardItem;
import net.mcreator.survivalreimagined.item.WarpedPlankItem;
import net.mcreator.survivalreimagined.item.VolcanicAshPileItem;
import net.mcreator.survivalreimagined.item.UsedFilterItem;
import net.mcreator.survivalreimagined.item.UranophaneNuggetItem;
import net.mcreator.survivalreimagined.item.UranophaneItem;
import net.mcreator.survivalreimagined.item.UraniumNuggetItem;
import net.mcreator.survivalreimagined.item.UraniumIngotItem;
import net.mcreator.survivalreimagined.item.UraniumDustItem;
import net.mcreator.survivalreimagined.item.UmbranBArkItem;
import net.mcreator.survivalreimagined.item.TuraniteNuggetItem;
import net.mcreator.survivalreimagined.item.TuraniteIngotItem;
import net.mcreator.survivalreimagined.item.TuffRockItem;
import net.mcreator.survivalreimagined.item.TitaniumNuggetItem;
import net.mcreator.survivalreimagined.item.TitaniumIngotItem;
import net.mcreator.survivalreimagined.item.TinNuggetItem;
import net.mcreator.survivalreimagined.item.TinIngotItem;
import net.mcreator.survivalreimagined.item.TinChunkItem;
import net.mcreator.survivalreimagined.item.ThermalCalciteRockItem;
import net.mcreator.survivalreimagined.item.SulfurPowderItem;
import net.mcreator.survivalreimagined.item.SulfurItem;
import net.mcreator.survivalreimagined.item.StoneSawItem;
import net.mcreator.survivalreimagined.item.StoneRockItem;
import net.mcreator.survivalreimagined.item.StoneKnifeItem;
import net.mcreator.survivalreimagined.item.StoneHammerItem;
import net.mcreator.survivalreimagined.item.StomachItem;
import net.mcreator.survivalreimagined.item.SteelSwordItem;
import net.mcreator.survivalreimagined.item.SteelSwordBladeItem;
import net.mcreator.survivalreimagined.item.SteelShovelItem;
import net.mcreator.survivalreimagined.item.SteelShovelHeadItem;
import net.mcreator.survivalreimagined.item.SteelSawItem;
import net.mcreator.survivalreimagined.item.SteelSawBladeItem;
import net.mcreator.survivalreimagined.item.SteelPickaxeItem;
import net.mcreator.survivalreimagined.item.SteelPickaxeHeadItem;
import net.mcreator.survivalreimagined.item.SteelNuggetItem;
import net.mcreator.survivalreimagined.item.SteelKnifeItem;
import net.mcreator.survivalreimagined.item.SteelKnifeBladeItem;
import net.mcreator.survivalreimagined.item.SteelIngotItem;
import net.mcreator.survivalreimagined.item.SteelHoeItem;
import net.mcreator.survivalreimagined.item.SteelHoeBladeItem;
import net.mcreator.survivalreimagined.item.SteelHammerItem;
import net.mcreator.survivalreimagined.item.SteelHammerHeadItem;
import net.mcreator.survivalreimagined.item.SteelChiselItem;
import net.mcreator.survivalreimagined.item.SteelAxeItem;
import net.mcreator.survivalreimagined.item.SteelAxeHeadItem;
import net.mcreator.survivalreimagined.item.SteelArmorItem;
import net.mcreator.survivalreimagined.item.SprucePlankItem;
import net.mcreator.survivalreimagined.item.SpoiledStomachItem;
import net.mcreator.survivalreimagined.item.SpoiledSalmanItem;
import net.mcreator.survivalreimagined.item.SpoiledRabbitItem;
import net.mcreator.survivalreimagined.item.SpoiledPorkchopItem;
import net.mcreator.survivalreimagined.item.SpoiledMuttonItem;
import net.mcreator.survivalreimagined.item.SpoiledLungsItem;
import net.mcreator.survivalreimagined.item.SpoiledLiverItem;
import net.mcreator.survivalreimagined.item.SpoiledIntestinesItem;
import net.mcreator.survivalreimagined.item.SpoiledHeartItem;
import net.mcreator.survivalreimagined.item.SpoiledCodItem;
import net.mcreator.survivalreimagined.item.SpoiledChickenItem;
import net.mcreator.survivalreimagined.item.SpoiledBrainItem;
import net.mcreator.survivalreimagined.item.SpoiledBeefItem;
import net.mcreator.survivalreimagined.item.SoulSandPileItem;
import net.mcreator.survivalreimagined.item.SolarEclipseItemItem;
import net.mcreator.survivalreimagined.item.SocotraBarkItem;
import net.mcreator.survivalreimagined.item.SmallStickItem;
import net.mcreator.survivalreimagined.item.SmallObsidianHandleItem;
import net.mcreator.survivalreimagined.item.SmallCopperHandleItem;
import net.mcreator.survivalreimagined.item.SmallCoalChunkItem;
import net.mcreator.survivalreimagined.item.SmallBronzeHandleItem;
import net.mcreator.survivalreimagined.item.SilverRubyRuneItem;
import net.mcreator.survivalreimagined.item.SilverNuggetItem;
import net.mcreator.survivalreimagined.item.SilverLapisRuneItem;
import net.mcreator.survivalreimagined.item.SilverIngotItem;
import net.mcreator.survivalreimagined.item.SilverEmeraldRuneItem;
import net.mcreator.survivalreimagined.item.SilverDiamondRuneItem;
import net.mcreator.survivalreimagined.item.SilverBirchBarkItem;
import net.mcreator.survivalreimagined.item.SilverAmberRuneItem;
import net.mcreator.survivalreimagined.item.SiltMudPileItem;
import net.mcreator.survivalreimagined.item.SiltDirtPileItem;
import net.mcreator.survivalreimagined.item.SiltCoarseDirtPileItem;
import net.mcreator.survivalreimagined.item.SheepHideItem;
import net.mcreator.survivalreimagined.item.SapphireSilverRuneItem;
import net.mcreator.survivalreimagined.item.SapphireItem;
import net.mcreator.survivalreimagined.item.SapphireGoldRuneItem;
import net.mcreator.survivalreimagined.item.SandstoneChunkItem;
import net.mcreator.survivalreimagined.item.SandPileItem;
import net.mcreator.survivalreimagined.item.SaltpeterItem;
import net.mcreator.survivalreimagined.item.SaltItem;
import net.mcreator.survivalreimagined.item.RubyItem;
import net.mcreator.survivalreimagined.item.RubyHeartShardItem;
import net.mcreator.survivalreimagined.item.RubyHeartItem;
import net.mcreator.survivalreimagined.item.RoughZincItem;
import net.mcreator.survivalreimagined.item.RoughUraniumItem;
import net.mcreator.survivalreimagined.item.RoughTuraniteItem;
import net.mcreator.survivalreimagined.item.RoughTitaniumItem;
import net.mcreator.survivalreimagined.item.RoughTinItem;
import net.mcreator.survivalreimagined.item.RoughSteelItem;
import net.mcreator.survivalreimagined.item.RoughSilverItem;
import net.mcreator.survivalreimagined.item.RoughSapphireItem;
import net.mcreator.survivalreimagined.item.RoughRubyItem;
import net.mcreator.survivalreimagined.item.RoughRedstoneItem;
import net.mcreator.survivalreimagined.item.RoughPlatedDiamondItem;
import net.mcreator.survivalreimagined.item.RoughNetheriteItem;
import net.mcreator.survivalreimagined.item.RoughManganeseItem;
import net.mcreator.survivalreimagined.item.RoughIronItem;
import net.mcreator.survivalreimagined.item.RoughGoldItem;
import net.mcreator.survivalreimagined.item.RoughEmeraldItem;
import net.mcreator.survivalreimagined.item.RoughDiamondItem;
import net.mcreator.survivalreimagined.item.RoughCopperItem;
import net.mcreator.survivalreimagined.item.RoughBronzeItem;
import net.mcreator.survivalreimagined.item.RoughBrassItem;
import net.mcreator.survivalreimagined.item.RoughAmberItem;
import net.mcreator.survivalreimagined.item.RootedDirtPileItem;
import net.mcreator.survivalreimagined.item.RedwoodBarkRUItem;
import net.mcreator.survivalreimagined.item.RedwoodBarkItem;
import net.mcreator.survivalreimagined.item.RedstoneNuggetItem;
import net.mcreator.survivalreimagined.item.RedstoneIngotItem;
import net.mcreator.survivalreimagined.item.RedstoneChunkItem;
import net.mcreator.survivalreimagined.item.RedstoneChargedUraniumDustItem;
import net.mcreator.survivalreimagined.item.RedSandstoneChunkItem;
import net.mcreator.survivalreimagined.item.RedSandPileItem;
import net.mcreator.survivalreimagined.item.RedGlassShardItem;
import net.mcreator.survivalreimagined.item.ReactorRodItem;
import net.mcreator.survivalreimagined.item.RawZincNuggetItem;
import net.mcreator.survivalreimagined.item.RawUraniniteNuggetItem;
import net.mcreator.survivalreimagined.item.RawUraniniteItem;
import net.mcreator.survivalreimagined.item.RawTitaniumNuggetItem;
import net.mcreator.survivalreimagined.item.RawTitaniumItem;
import net.mcreator.survivalreimagined.item.RawTinItem;
import net.mcreator.survivalreimagined.item.RawSilverNuggetItem;
import net.mcreator.survivalreimagined.item.RawSilverItem;
import net.mcreator.survivalreimagined.item.RawRedstoneItem;
import net.mcreator.survivalreimagined.item.RawManganeseItem;
import net.mcreator.survivalreimagined.item.RadiationItemItem;
import net.mcreator.survivalreimagined.item.RadiatedPlankItem;
import net.mcreator.survivalreimagined.item.RadiatedBarkItem;
import net.mcreator.survivalreimagined.item.PyrolusiteNuggetItem;
import net.mcreator.survivalreimagined.item.PyrolusiteItem;
import net.mcreator.survivalreimagined.item.PurpleGlassShardItem;
import net.mcreator.survivalreimagined.item.PlantFiberItem;
import net.mcreator.survivalreimagined.item.PinkGlassShardItem;
import net.mcreator.survivalreimagined.item.PineBarkRUItem;
import net.mcreator.survivalreimagined.item.PineBarkItem;
import net.mcreator.survivalreimagined.item.PeatPileItem;
import net.mcreator.survivalreimagined.item.PeatMudPileItem;
import net.mcreator.survivalreimagined.item.PeatCoarseDirtPileItem;
import net.mcreator.survivalreimagined.item.ParanoiaEyeItem;
import net.mcreator.survivalreimagined.item.PalmBarkRUItem;
import net.mcreator.survivalreimagined.item.PalmBarkItem;
import net.mcreator.survivalreimagined.item.OrangeSandstoneChunkItem;
import net.mcreator.survivalreimagined.item.OrangeSandPileItem;
import net.mcreator.survivalreimagined.item.OrangeGlassShardItem;
import net.mcreator.survivalreimagined.item.ObsidianHandleItem;
import net.mcreator.survivalreimagined.item.OakPlankItem;
import net.mcreator.survivalreimagined.item.NitreItem;
import net.mcreator.survivalreimagined.item.NetherrackRockItem;
import net.mcreator.survivalreimagined.item.NetheriteSawItem;
import net.mcreator.survivalreimagined.item.NetheriteKnifeItem;
import net.mcreator.survivalreimagined.item.NetheriteHammerItem;
import net.mcreator.survivalreimagined.item.MudRockItem;
import net.mcreator.survivalreimagined.item.MudPileItem;
import net.mcreator.survivalreimagined.item.MossyStoneRockItem;
import net.mcreator.survivalreimagined.item.MortarPestalItem;
import net.mcreator.survivalreimagined.item.MauveBarkItem;
import net.mcreator.survivalreimagined.item.MapleBarkRUItem;
import net.mcreator.survivalreimagined.item.MapleBarkItem;
import net.mcreator.survivalreimagined.item.MangrovePlankItem;
import net.mcreator.survivalreimagined.item.ManganiteNuggetItem;
import net.mcreator.survivalreimagined.item.ManganiteItem;
import net.mcreator.survivalreimagined.item.ManganeseNuggetItem;
import net.mcreator.survivalreimagined.item.ManganeseIngotItem;
import net.mcreator.survivalreimagined.item.ManganeseChunkItem;
import net.mcreator.survivalreimagined.item.MalachiteNuggetItem;
import net.mcreator.survivalreimagined.item.MalachiteItem;
import net.mcreator.survivalreimagined.item.MahoganyBarkItem;
import net.mcreator.survivalreimagined.item.MagnoilaBarkItem;
import net.mcreator.survivalreimagined.item.MagnetiteNuggetItem;
import net.mcreator.survivalreimagined.item.MagnetiteChunkItem;
import net.mcreator.survivalreimagined.item.MagicBarkItem;
import net.mcreator.survivalreimagined.item.MagentaGlassShardItem;
import net.mcreator.survivalreimagined.item.LungsItem;
import net.mcreator.survivalreimagined.item.LiverItem;
import net.mcreator.survivalreimagined.item.LimeGreenGlassShardItem;
import net.mcreator.survivalreimagined.item.LightGreyGlassShardItem;
import net.mcreator.survivalreimagined.item.LightBlueGlassShardItem;
import net.mcreator.survivalreimagined.item.LargeWarpedBarkItem;
import net.mcreator.survivalreimagined.item.LargeSpruceBarkItem;
import net.mcreator.survivalreimagined.item.LargeOakBarkItem;
import net.mcreator.survivalreimagined.item.LargeMangroveBarkItem;
import net.mcreator.survivalreimagined.item.LargeJungleBarkItem;
import net.mcreator.survivalreimagined.item.LargeDarkOakBarkItem;
import net.mcreator.survivalreimagined.item.LargeCrimsonBarkItem;
import net.mcreator.survivalreimagined.item.LargeCherryBarkItem;
import net.mcreator.survivalreimagined.item.LargeBirchBarkItem;
import net.mcreator.survivalreimagined.item.LargeAcaciaBarkItem;
import net.mcreator.survivalreimagined.item.LarchBarkItem;
import net.mcreator.survivalreimagined.item.KapokBarkItem;
import net.mcreator.survivalreimagined.item.JunglePlankItem;
import net.mcreator.survivalreimagined.item.JoshuaBarkItem;
import net.mcreator.survivalreimagined.item.JacarandaBarkItem;
import net.mcreator.survivalreimagined.item.IronChunkItem;
import net.mcreator.survivalreimagined.item.IntestinesItem;
import net.mcreator.survivalreimagined.item.IlmeniteNuggetItem;
import net.mcreator.survivalreimagined.item.IlmeniteItem;
import net.mcreator.survivalreimagined.item.HempSeedsItem;
import net.mcreator.survivalreimagined.item.HempPaperItem;
import net.mcreator.survivalreimagined.item.HempMeshItem;
import net.mcreator.survivalreimagined.item.HempLeafItem;
import net.mcreator.survivalreimagined.item.HematiteNuggetItem;
import net.mcreator.survivalreimagined.item.HematiteChunkItem;
import net.mcreator.survivalreimagined.item.HellBarkItem;
import net.mcreator.survivalreimagined.item.HeartOfTheNetherItem;
import net.mcreator.survivalreimagined.item.HeartOfTheBloodMoonItem;
import net.mcreator.survivalreimagined.item.HeartItemItem;
import net.mcreator.survivalreimagined.item.HeartItem;
import net.mcreator.survivalreimagined.item.GreyGlassShardItem;
import net.mcreator.survivalreimagined.item.GreenGlassShardItem;
import net.mcreator.survivalreimagined.item.GravelPileItem;
import net.mcreator.survivalreimagined.item.GraniteRockItem;
import net.mcreator.survivalreimagined.item.GoldRubyRuneItem;
import net.mcreator.survivalreimagined.item.GoldRodItem;
import net.mcreator.survivalreimagined.item.GoldLapisRuneItem;
import net.mcreator.survivalreimagined.item.GoldHeartItem;
import net.mcreator.survivalreimagined.item.GoldEmeraldRuneItem;
import net.mcreator.survivalreimagined.item.GoldDiamondRuneItem;
import net.mcreator.survivalreimagined.item.GoldChunkItem;
import net.mcreator.survivalreimagined.item.GoldAmberRuneItem;
import net.mcreator.survivalreimagined.item.GlassShardItem;
import net.mcreator.survivalreimagined.item.GasMaskItem;
import net.mcreator.survivalreimagined.item.GasMaskFilterItem;
import net.mcreator.survivalreimagined.item.FuelUpgradeMKIIItem;
import net.mcreator.survivalreimagined.item.FuelUpgradeItem;
import net.mcreator.survivalreimagined.item.FlintToolItem;
import net.mcreator.survivalreimagined.item.FleshItem;
import net.mcreator.survivalreimagined.item.FirBarkItem;
import net.mcreator.survivalreimagined.item.FearEyeItem;
import net.mcreator.survivalreimagined.item.EyeOfEnderFusionDustItem;
import net.mcreator.survivalreimagined.item.EyeClosedItem;
import net.mcreator.survivalreimagined.item.EucalyptusBarkItem;
import net.mcreator.survivalreimagined.item.EndStoneRockItem;
import net.mcreator.survivalreimagined.item.EmpyrealBarkItem;
import net.mcreator.survivalreimagined.item.EmptySilverRuneItem;
import net.mcreator.survivalreimagined.item.EmptyGoldRuneItem;
import net.mcreator.survivalreimagined.item.EfficiencyUpgradeItem;
import net.mcreator.survivalreimagined.item.DripstoneRockItem;
import net.mcreator.survivalreimagined.item.DrainedAdvancedReactorRodItem;
import net.mcreator.survivalreimagined.item.DirtPileItem;
import net.mcreator.survivalreimagined.item.DioriteRockItem;
import net.mcreator.survivalreimagined.item.DiamondSwordBladeItem;
import net.mcreator.survivalreimagined.item.DiamondShovelHeadItem;
import net.mcreator.survivalreimagined.item.DiamondSawItem;
import net.mcreator.survivalreimagined.item.DiamondSawBladeItem;
import net.mcreator.survivalreimagined.item.DiamondPlatedIngotItem;
import net.mcreator.survivalreimagined.item.DiamondPickaxeHeadItem;
import net.mcreator.survivalreimagined.item.DiamondKnifeItem;
import net.mcreator.survivalreimagined.item.DiamondKnifeBladeItem;
import net.mcreator.survivalreimagined.item.DiamondHoeBladeItem;
import net.mcreator.survivalreimagined.item.DiamondHammerItem;
import net.mcreator.survivalreimagined.item.DiamondHammerHeadItem;
import net.mcreator.survivalreimagined.item.DiamondChiselItem;
import net.mcreator.survivalreimagined.item.DiamondAxeHeadItem;
import net.mcreator.survivalreimagined.item.DepletedReactorRodItem;
import net.mcreator.survivalreimagined.item.DeepslateRockItem;
import net.mcreator.survivalreimagined.item.DeadBarkRUItem;
import net.mcreator.survivalreimagined.item.DeadBarkItem;
import net.mcreator.survivalreimagined.item.DarkOakPlankItem;
import net.mcreator.survivalreimagined.item.CypressBarkItem;
import net.mcreator.survivalreimagined.item.CyanGlassShardItem;
import net.mcreator.survivalreimagined.item.CuredStomachItem;
import net.mcreator.survivalreimagined.item.CuredSteakItem;
import net.mcreator.survivalreimagined.item.CuredRabbitItem;
import net.mcreator.survivalreimagined.item.CuredPorkchopItem;
import net.mcreator.survivalreimagined.item.CuredMuttonItem;
import net.mcreator.survivalreimagined.item.CuredLungsItem;
import net.mcreator.survivalreimagined.item.CuredLiverItem;
import net.mcreator.survivalreimagined.item.CuredIntestinesItem;
import net.mcreator.survivalreimagined.item.CuredHeartItem;
import net.mcreator.survivalreimagined.item.CuredChickenItem;
import net.mcreator.survivalreimagined.item.CuredBrainItem;
import net.mcreator.survivalreimagined.item.CryingObsidianRockItem;
import net.mcreator.survivalreimagined.item.CrimsonThreadItem;
import net.mcreator.survivalreimagined.item.CrimsonPlankItem;
import net.mcreator.survivalreimagined.item.CowHideItem;
import net.mcreator.survivalreimagined.item.CopperNuggetItem;
import net.mcreator.survivalreimagined.item.CopperHandleItem;
import net.mcreator.survivalreimagined.item.CopperChunkItem;
import net.mcreator.survivalreimagined.item.CopperChiselItem;
import net.mcreator.survivalreimagined.item.CookedStomachItem;
import net.mcreator.survivalreimagined.item.CookedLungsItem;
import net.mcreator.survivalreimagined.item.CookedLiverItem;
import net.mcreator.survivalreimagined.item.CookedIntestinesItem;
import net.mcreator.survivalreimagined.item.CookedHeartItem;
import net.mcreator.survivalreimagined.item.CookedBrainItem;
import net.mcreator.survivalreimagined.item.CobaltBarkItem;
import net.mcreator.survivalreimagined.item.CoarseDirtPileItem;
import net.mcreator.survivalreimagined.item.ClayBrickItem;
import net.mcreator.survivalreimagined.item.CherryPlankItem;
import net.mcreator.survivalreimagined.item.CharcoalPowderItem;
import net.mcreator.survivalreimagined.item.CassiteriteNuggetItem;
import net.mcreator.survivalreimagined.item.CassiteriteItem;
import net.mcreator.survivalreimagined.item.CalciteRockItem;
import net.mcreator.survivalreimagined.item.CalaveriteNuggetItem;
import net.mcreator.survivalreimagined.item.CalaveriteItem;
import net.mcreator.survivalreimagined.item.BrownGlassShardItem;
import net.mcreator.survivalreimagined.item.BronzeSwordItem;
import net.mcreator.survivalreimagined.item.BronzeSwordBladeItem;
import net.mcreator.survivalreimagined.item.BronzeShovelItem;
import net.mcreator.survivalreimagined.item.BronzeShovelHeadItem;
import net.mcreator.survivalreimagined.item.BronzeSawItem;
import net.mcreator.survivalreimagined.item.BronzeSawBladeItem;
import net.mcreator.survivalreimagined.item.BronzePickaxeItem;
import net.mcreator.survivalreimagined.item.BronzePickaxeHeadItem;
import net.mcreator.survivalreimagined.item.BronzeNuggetItem;
import net.mcreator.survivalreimagined.item.BronzeKnifeItem;
import net.mcreator.survivalreimagined.item.BronzeKnifeBladeItem;
import net.mcreator.survivalreimagined.item.BronzeIngotItem;
import net.mcreator.survivalreimagined.item.BronzeHoeItem;
import net.mcreator.survivalreimagined.item.BronzeHoeBladeItem;
import net.mcreator.survivalreimagined.item.BronzeHandleItem;
import net.mcreator.survivalreimagined.item.BronzeHammerItem;
import net.mcreator.survivalreimagined.item.BronzeHammerHeadItem;
import net.mcreator.survivalreimagined.item.BronzeChiselItem;
import net.mcreator.survivalreimagined.item.BronzeAxeItem;
import net.mcreator.survivalreimagined.item.BronzeAxeHeadItem;
import net.mcreator.survivalreimagined.item.BronzeArmorItem;
import net.mcreator.survivalreimagined.item.BrimwoodBarkItem;
import net.mcreator.survivalreimagined.item.BrimstoneRockItem;
import net.mcreator.survivalreimagined.item.BrainItem;
import net.mcreator.survivalreimagined.item.BoatPaddlesItem;
import net.mcreator.survivalreimagined.item.BlueGlassShardItem;
import net.mcreator.survivalreimagined.item.BloodMoonsMusicDiscItem;
import net.mcreator.survivalreimagined.item.BloodMoonItemItem;
import net.mcreator.survivalreimagined.item.BloodMoonDiscFragmentItem;
import net.mcreator.survivalreimagined.item.BlockPackagingUpgradeItem;
import net.mcreator.survivalreimagined.item.BlackwoodBarkItem;
import net.mcreator.survivalreimagined.item.BlackstoneRockItem;
import net.mcreator.survivalreimagined.item.BlackSandstoneChunkItem;
import net.mcreator.survivalreimagined.item.BlackSandPileItem;
import net.mcreator.survivalreimagined.item.BlackGlassShardItem;
import net.mcreator.survivalreimagined.item.BirchPlankItem;
import net.mcreator.survivalreimagined.item.BasaltRockItem;
import net.mcreator.survivalreimagined.item.BaobabBarkItem;
import net.mcreator.survivalreimagined.item.BackpackItem;
import net.mcreator.survivalreimagined.item.AzuriteNuggetItem;
import net.mcreator.survivalreimagined.item.AzuriteItem;
import net.mcreator.survivalreimagined.item.AshenDirtPileItem;
import net.mcreator.survivalreimagined.item.AshenBarkItem;
import net.mcreator.survivalreimagined.item.AshPileItem;
import net.mcreator.survivalreimagined.item.ArgilliteRockItem;
import net.mcreator.survivalreimagined.item.ArgentiteNuggetItem;
import net.mcreator.survivalreimagined.item.ArgentiteItem;
import net.mcreator.survivalreimagined.item.AndesiteRockItem;
import net.mcreator.survivalreimagined.item.AncientDebrisChunkItem;
import net.mcreator.survivalreimagined.item.AmberItem;
import net.mcreator.survivalreimagined.item.AlphaOakBarkItem;
import net.mcreator.survivalreimagined.item.AdvancedReactorRodItem;
import net.mcreator.survivalreimagined.item.AcaciaPlankItem;
import net.mcreator.survivalreimagined.item.AAFScriptureItem;
import net.mcreator.survivalreimagined.SurvivalReimaginedMod;

@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD)
public class SurvivalReimaginedModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(SurvivalReimaginedMod.MODID);
	public static final DeferredItem<Item> FLINTBLOCK = block(SurvivalReimaginedModBlocks.FLINTBLOCK);
	public static final DeferredItem<Item> FLINT_TOOL = REGISTRY.register("flint_tool", FlintToolItem::new);
	public static final DeferredItem<Item> LARGE_OAK_BARK = REGISTRY.register("large_oak_bark", LargeOakBarkItem::new);
	public static final DeferredItem<Item> LARGE_DARK_OAK_BARK = REGISTRY.register("large_dark_oak_bark", LargeDarkOakBarkItem::new);
	public static final DeferredItem<Item> LARGE_SPRUCE_BARK = REGISTRY.register("large_spruce_bark", LargeSpruceBarkItem::new);
	public static final DeferredItem<Item> LARGE_BIRCH_BARK = REGISTRY.register("large_birch_bark", LargeBirchBarkItem::new);
	public static final DeferredItem<Item> LARGE_MANGROVE_BARK = REGISTRY.register("large_mangrove_bark", LargeMangroveBarkItem::new);
	public static final DeferredItem<Item> LARGE_CHERRY_BARK = REGISTRY.register("large_cherry_bark", LargeCherryBarkItem::new);
	public static final DeferredItem<Item> LARGE_ACACIA_BARK = REGISTRY.register("large_acacia_bark", LargeAcaciaBarkItem::new);
	public static final DeferredItem<Item> LARGE_JUNGLE_BARK = REGISTRY.register("large_jungle_bark", LargeJungleBarkItem::new);
	public static final DeferredItem<Item> LARGE_CRIMSON_BARK = REGISTRY.register("large_crimson_bark", LargeCrimsonBarkItem::new);
	public static final DeferredItem<Item> LARGE_WARPED_BARK = REGISTRY.register("large_warped_bark", LargeWarpedBarkItem::new);
	public static final DeferredItem<Item> STONE_ROCK = REGISTRY.register("stone_rock", StoneRockItem::new);
	public static final DeferredItem<Item> STONE_ROCK_BLOC = block(SurvivalReimaginedModBlocks.STONE_ROCK_BLOC);
	public static final DeferredItem<Item> HEMP_FIBER = REGISTRY.register("hemp_fiber", PlantFiberItem::new);
	public static final DeferredItem<Item> COPPER_CHUNK = REGISTRY.register("copper_chunk", CopperChunkItem::new);
	public static final DeferredItem<Item> COPPER_NUGGET = REGISTRY.register("copper_nugget", CopperNuggetItem::new);
	public static final DeferredItem<Item> COPPER_CHISEL = REGISTRY.register("copper_chisel", CopperChiselItem::new);
	public static final DeferredItem<Item> SMALL_COAL_CHUNK = REGISTRY.register("small_coal_chunk", SmallCoalChunkItem::new);
	public static final DeferredItem<Item> TIN_ORE = block(SurvivalReimaginedModBlocks.TIN_ORE);
	public static final DeferredItem<Item> RAW_TIN = REGISTRY.register("raw_tin", RawTinItem::new);
	public static final DeferredItem<Item> TIN_INGOT = REGISTRY.register("tin_ingot", TinIngotItem::new);
	public static final DeferredItem<Item> TIN_NUGGET = REGISTRY.register("tin_nugget", TinNuggetItem::new);
	public static final DeferredItem<Item> DEEPSLATE_ROCK = REGISTRY.register("deepslate_rock", DeepslateRockItem::new);
	public static final DeferredItem<Item> FORGE = block(SurvivalReimaginedModBlocks.FORGE);
	public static final DeferredItem<Item> BRONZE_INGOT = REGISTRY.register("bronze_ingot", BronzeIngotItem::new);
	public static final DeferredItem<Item> ROUGH_BRONZE = REGISTRY.register("rough_bronze", RoughBronzeItem::new);
	public static final DeferredItem<Item> ROUGH_IRON = REGISTRY.register("rough_iron", RoughIronItem::new);
	public static final DeferredItem<Item> ROUGH_GOLD = REGISTRY.register("rough_gold", RoughGoldItem::new);
	public static final DeferredItem<Item> ROUGH_COPPER = REGISTRY.register("rough_copper", RoughCopperItem::new);
	public static final DeferredItem<Item> ROUGH_TIN = REGISTRY.register("rough_tin", RoughTinItem::new);
	public static final DeferredItem<Item> STONE_HAMMER = REGISTRY.register("stone_hammer", StoneHammerItem::new);
	public static final DeferredItem<Item> METAL_REFINING_TABLE = block(SurvivalReimaginedModBlocks.METAL_REFINING_TABLE);
	public static final DeferredItem<Item> OAK_PLANK = REGISTRY.register("oak_plank", OakPlankItem::new);
	public static final DeferredItem<Item> DARK_OAK_PLANK = REGISTRY.register("dark_oak_plank", DarkOakPlankItem::new);
	public static final DeferredItem<Item> SPRUCE_PLANK = REGISTRY.register("spruce_plank", SprucePlankItem::new);
	public static final DeferredItem<Item> BIRCH_PLANK = REGISTRY.register("birch_plank", BirchPlankItem::new);
	public static final DeferredItem<Item> ACACIA_PLANK = REGISTRY.register("acacia_plank", AcaciaPlankItem::new);
	public static final DeferredItem<Item> JUNGLE_PLANK = REGISTRY.register("jungle_plank", JunglePlankItem::new);
	public static final DeferredItem<Item> CHERRY_PLANK = REGISTRY.register("cherry_plank", CherryPlankItem::new);
	public static final DeferredItem<Item> MANGROVE_PLANK = REGISTRY.register("mangrove_plank", MangrovePlankItem::new);
	public static final DeferredItem<Item> CRIMSON_PLANK = REGISTRY.register("crimson_plank", CrimsonPlankItem::new);
	public static final DeferredItem<Item> WARPED_PLANK = REGISTRY.register("warped_plank", WarpedPlankItem::new);
	public static final DeferredItem<Item> STONE_SAW = REGISTRY.register("stone_saw", StoneSawItem::new);
	public static final DeferredItem<Item> CLAY_BRICK = REGISTRY.register("clay_brick", ClayBrickItem::new);
	public static final DeferredItem<Item> CLAY_CRUCIBLE = block(SurvivalReimaginedModBlocks.CLAY_CRUCIBLE);
	public static final DeferredItem<Item> CRUCIBLE = block(SurvivalReimaginedModBlocks.CRUCIBLE);
	public static final DeferredItem<Item> BRONZE_PICKAXE = REGISTRY.register("bronze_pickaxe", BronzePickaxeItem::new);
	public static final DeferredItem<Item> BRONZE_AXE = REGISTRY.register("bronze_axe", BronzeAxeItem::new);
	public static final DeferredItem<Item> BRONZE_SWORD = REGISTRY.register("bronze_sword", BronzeSwordItem::new);
	public static final DeferredItem<Item> BRONZE_SHOVEL = REGISTRY.register("bronze_shovel", BronzeShovelItem::new);
	public static final DeferredItem<Item> BRONZE_HOE = REGISTRY.register("bronze_hoe", BronzeHoeItem::new);
	public static final DeferredItem<Item> COPPER_HANDLE = REGISTRY.register("copper_handle", CopperHandleItem::new);
	public static final DeferredItem<Item> AXE_HEAD_MOLD = block(SurvivalReimaginedModBlocks.AXE_HEAD_MOLD);
	public static final DeferredItem<Item> PICKAXE_HEAD_MOLD = block(SurvivalReimaginedModBlocks.PICKAXE_HEAD_MOLD);
	public static final DeferredItem<Item> SWORD_BLADE_MOLD = block(SurvivalReimaginedModBlocks.SWORD_BLADE_MOLD);
	public static final DeferredItem<Item> HOE_HEAD_MOLD = block(SurvivalReimaginedModBlocks.HOE_HEAD_MOLD);
	public static final DeferredItem<Item> SHOVEL_HEAD_MOLD = block(SurvivalReimaginedModBlocks.SHOVEL_HEAD_MOLD);
	public static final DeferredItem<Item> SAW_BLADE_MOLD = block(SurvivalReimaginedModBlocks.SAW_BLADE_MOLD);
	public static final DeferredItem<Item> HAMMER_HEAD_MOLD = block(SurvivalReimaginedModBlocks.HAMMER_HEAD_MOLD);
	public static final DeferredItem<Item> HELMET_MOLD = block(SurvivalReimaginedModBlocks.HELMET_MOLD);
	public static final DeferredItem<Item> CHESTPLATE_MOLD = block(SurvivalReimaginedModBlocks.CHESTPLATE_MOLD);
	public static final DeferredItem<Item> LEGGING_MOLD = block(SurvivalReimaginedModBlocks.LEGGING_MOLD);
	public static final DeferredItem<Item> BOOTS_MOLD = block(SurvivalReimaginedModBlocks.BOOTS_MOLD);
	public static final DeferredItem<Item> CLAY_SWORD_BLADE_MOLD = block(SurvivalReimaginedModBlocks.CLAY_SWORD_BLADE_MOLD);
	public static final DeferredItem<Item> CLAY_PICKAXE_HEAD_MOLD = block(SurvivalReimaginedModBlocks.CLAY_PICKAXE_HEAD_MOLD);
	public static final DeferredItem<Item> CLAY_AXE_HEAD_MOLD = block(SurvivalReimaginedModBlocks.CLAY_AXE_HEAD_MOLD);
	public static final DeferredItem<Item> CLAY_SHOVEL_HEAD_MOLD = block(SurvivalReimaginedModBlocks.CLAY_SHOVEL_HEAD_MOLD);
	public static final DeferredItem<Item> CLAY_HOE_BLADE_MOLD = block(SurvivalReimaginedModBlocks.CLAY_HOE_BLADE_MOLD);
	public static final DeferredItem<Item> CLAY_HAMMER_HEAD_MOLD = block(SurvivalReimaginedModBlocks.CLAY_HAMMER_HEAD_MOLD);
	public static final DeferredItem<Item> CLAY_SAW_BLADE_MOLD = block(SurvivalReimaginedModBlocks.CLAY_SAW_BLADE_MOLD);
	public static final DeferredItem<Item> CLAY_HELMET_MOLD = block(SurvivalReimaginedModBlocks.CLAY_HELMET_MOLD);
	public static final DeferredItem<Item> CLAY_CHESTPLATE_MOLD = block(SurvivalReimaginedModBlocks.CLAY_CHESTPLATE_MOLD);
	public static final DeferredItem<Item> CLAY_LEGGINGS_MOLD = block(SurvivalReimaginedModBlocks.CLAY_LEGGINGS_MOLD);
	public static final DeferredItem<Item> CLAY_BOOTS_MOLD = block(SurvivalReimaginedModBlocks.CLAY_BOOTS_MOLD);
	public static final DeferredItem<Item> BRONZE_ARMOR_HELMET = REGISTRY.register("bronze_armor_helmet", BronzeArmorItem.Helmet::new);
	public static final DeferredItem<Item> BRONZE_ARMOR_CHESTPLATE = REGISTRY.register("bronze_armor_chestplate", BronzeArmorItem.Chestplate::new);
	public static final DeferredItem<Item> BRONZE_ARMOR_LEGGINGS = REGISTRY.register("bronze_armor_leggings", BronzeArmorItem.Leggings::new);
	public static final DeferredItem<Item> BRONZE_ARMOR_BOOTS = REGISTRY.register("bronze_armor_boots", BronzeArmorItem.Boots::new);
	public static final DeferredItem<Item> BRONZE_SAW = REGISTRY.register("bronze_saw", BronzeSawItem::new);
	public static final DeferredItem<Item> BRONZE_HAMMER = REGISTRY.register("bronze_hammer", BronzeHammerItem::new);
	public static final DeferredItem<Item> BRONZE_PICKAXE_HEAD = REGISTRY.register("bronze_pickaxe_head", BronzePickaxeHeadItem::new);
	public static final DeferredItem<Item> BRONZE_AXE_HEAD = REGISTRY.register("bronze_axe_head", BronzeAxeHeadItem::new);
	public static final DeferredItem<Item> BRONZE_SWORD_BLADE = REGISTRY.register("bronze_sword_blade", BronzeSwordBladeItem::new);
	public static final DeferredItem<Item> BRONZE_HOE_BLADE = REGISTRY.register("bronze_hoe_blade", BronzeHoeBladeItem::new);
	public static final DeferredItem<Item> BRONZE_SHOVEL_HEAD = REGISTRY.register("bronze_shovel_head", BronzeShovelHeadItem::new);
	public static final DeferredItem<Item> BRONZE_HAMMER_HEAD = REGISTRY.register("bronze_hammer_head", BronzeHammerHeadItem::new);
	public static final DeferredItem<Item> BRONZE_SAW_BLADE = REGISTRY.register("bronze_saw_blade", BronzeSawBladeItem::new);
	public static final DeferredItem<Item> WOODEN_SAW = REGISTRY.register("wooden_saw", WoodenSawItem::new);
	public static final DeferredItem<Item> WOODEN_HAMMER = REGISTRY.register("wooden_hammer", WoodenHammerItem::new);
	public static final DeferredItem<Item> WOODEN_HELMET = REGISTRY.register("wooden_helmet", WoodenItem.Helmet::new);
	public static final DeferredItem<Item> WOODEN_CHESTPLATE = REGISTRY.register("wooden_chestplate", WoodenItem.Chestplate::new);
	public static final DeferredItem<Item> WOODEN_LEGGINGS = REGISTRY.register("wooden_leggings", WoodenItem.Leggings::new);
	public static final DeferredItem<Item> WOODEN_BOOTS = REGISTRY.register("wooden_boots", WoodenItem.Boots::new);
	public static final DeferredItem<Item> IRON_CHUNK = REGISTRY.register("iron_chunk", IronChunkItem::new);
	public static final DeferredItem<Item> BLOCK_OF_BRONZE = block(SurvivalReimaginedModBlocks.BLOCK_OF_BRONZE);
	public static final DeferredItem<Item> TIN_CHUNK = REGISTRY.register("tin_chunk", TinChunkItem::new);
	public static final DeferredItem<Item> HEART = REGISTRY.register("heart", HeartItem::new);
	public static final DeferredItem<Item> ANDESITE_ROCK = REGISTRY.register("andesite_rock", AndesiteRockItem::new);
	public static final DeferredItem<Item> ANDESITE_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.ANDESITE_ROCK_BLOCK);
	public static final DeferredItem<Item> GRANITE_ROCK = REGISTRY.register("granite_rock", GraniteRockItem::new);
	public static final DeferredItem<Item> GRANITE_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.GRANITE_ROCK_BLOCK);
	public static final DeferredItem<Item> DIORITE_ROCK_B_LOCK = block(SurvivalReimaginedModBlocks.DIORITE_ROCK_B_LOCK);
	public static final DeferredItem<Item> DIORITE_ROCK = REGISTRY.register("diorite_rock", DioriteRockItem::new);
	public static final DeferredItem<Item> DRIPSTONE_ROCK = REGISTRY.register("dripstone_rock", DripstoneRockItem::new);
	public static final DeferredItem<Item> DRIPSTONE_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.DRIPSTONE_ROCK_BLOCK);
	public static final DeferredItem<Item> CALCITE_ROCK = REGISTRY.register("calcite_rock", CalciteRockItem::new);
	public static final DeferredItem<Item> CALCITE_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.CALCITE_ROCK_BLOCK);
	public static final DeferredItem<Item> TUFF_ROCK = REGISTRY.register("tuff_rock", TuffRockItem::new);
	public static final DeferredItem<Item> TUFF_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.TUFF_ROCK_BLOCK);
	public static final DeferredItem<Item> MOSSY_STONE_ROCK = REGISTRY.register("mossy_stone_rock", MossyStoneRockItem::new);
	public static final DeferredItem<Item> MOSSY_STONE_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.MOSSY_STONE_ROCK_BLOCK);
	public static final DeferredItem<Item> NETHERRACK_ROCK = REGISTRY.register("netherrack_rock", NetherrackRockItem::new);
	public static final DeferredItem<Item> NETHERRACK_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.NETHERRACK_ROCK_BLOCK);
	public static final DeferredItem<Item> END_STONE_ROCK = REGISTRY.register("end_stone_rock", EndStoneRockItem::new);
	public static final DeferredItem<Item> END_STONE_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.END_STONE_ROCK_BLOCK);
	public static final DeferredItem<Item> BLACKSTONE_ROCK = REGISTRY.register("blackstone_rock", BlackstoneRockItem::new);
	public static final DeferredItem<Item> BLACKSTONE_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.BLACKSTONE_ROCK_BLOCK);
	public static final DeferredItem<Item> BASALT_ROCK = REGISTRY.register("basalt_rock", BasaltRockItem::new);
	public static final DeferredItem<Item> BASALT_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.BASALT_ROCK_BLOCK);
	public static final DeferredItem<Item> DEEPSLATE_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.DEEPSLATE_ROCK_BLOCK);
	public static final DeferredItem<Item> BOAT_PADDLES = REGISTRY.register("boat_paddles", BoatPaddlesItem::new);
	public static final DeferredItem<Item> BLOCK_OF_RAW_TIN = block(SurvivalReimaginedModBlocks.BLOCK_OF_RAW_TIN);
	public static final DeferredItem<Item> BLOCK_OF_TIN = block(SurvivalReimaginedModBlocks.BLOCK_OF_TIN);
	public static final DeferredItem<Item> COW_CARCASS = block(SurvivalReimaginedModBlocks.COW_CARCASS);
	public static final DeferredItem<Item> STONE_KNIFE = REGISTRY.register("stone_knife", StoneKnifeItem::new);
	public static final DeferredItem<Item> COW_HIDE = REGISTRY.register("cow_hide", CowHideItem::new);
	public static final DeferredItem<Item> COW_LEG = block(SurvivalReimaginedModBlocks.COW_LEG);
	public static final DeferredItem<Item> COW_HEAD = block(SurvivalReimaginedModBlocks.COW_HEAD);
	public static final DeferredItem<Item> BRAIN = REGISTRY.register("brain", BrainItem::new);
	public static final DeferredItem<Item> HEART_ITEM = REGISTRY.register("heart_item", HeartItemItem::new);
	public static final DeferredItem<Item> INTESTINES = REGISTRY.register("intestines", IntestinesItem::new);
	public static final DeferredItem<Item> STOMACH = REGISTRY.register("stomach", StomachItem::new);
	public static final DeferredItem<Item> LIVER = REGISTRY.register("liver", LiverItem::new);
	public static final DeferredItem<Item> LUNGS = REGISTRY.register("lungs", LungsItem::new);
	public static final DeferredItem<Item> COOKED_BRAIN = REGISTRY.register("cooked_brain", CookedBrainItem::new);
	public static final DeferredItem<Item> COOKED_HEART = REGISTRY.register("cooked_heart", CookedHeartItem::new);
	public static final DeferredItem<Item> COOKED_INTESTINES = REGISTRY.register("cooked_intestines", CookedIntestinesItem::new);
	public static final DeferredItem<Item> COOKED_LIVER = REGISTRY.register("cooked_liver", CookedLiverItem::new);
	public static final DeferredItem<Item> COOKED_STOMACH = REGISTRY.register("cooked_stomach", CookedStomachItem::new);
	public static final DeferredItem<Item> COOKED_LUNGS = REGISTRY.register("cooked_lungs", CookedLungsItem::new);
	public static final DeferredItem<Item> SPOILED_BRAIN = REGISTRY.register("spoiled_brain", SpoiledBrainItem::new);
	public static final DeferredItem<Item> SPOILED_HEART = REGISTRY.register("spoiled_heart", SpoiledHeartItem::new);
	public static final DeferredItem<Item> SPOILED_INTESTINES = REGISTRY.register("spoiled_intestines", SpoiledIntestinesItem::new);
	public static final DeferredItem<Item> SPOILED_LIVER = REGISTRY.register("spoiled_liver", SpoiledLiverItem::new);
	public static final DeferredItem<Item> SPOILED_LUNGS = REGISTRY.register("spoiled_lungs", SpoiledLungsItem::new);
	public static final DeferredItem<Item> SPOILED_STOMACH = REGISTRY.register("spoiled_stomach", SpoiledStomachItem::new);
	public static final DeferredItem<Item> SPOILED_COD = REGISTRY.register("spoiled_cod", SpoiledCodItem::new);
	public static final DeferredItem<Item> SPOILED_SALMAN = REGISTRY.register("spoiled_salman", SpoiledSalmanItem::new);
	public static final DeferredItem<Item> SPOILED_CHICKEN = REGISTRY.register("spoiled_chicken", SpoiledChickenItem::new);
	public static final DeferredItem<Item> SPOILED_RABBIT = REGISTRY.register("spoiled_rabbit", SpoiledRabbitItem::new);
	public static final DeferredItem<Item> SPOILED_MUTTON = REGISTRY.register("spoiled_mutton", SpoiledMuttonItem::new);
	public static final DeferredItem<Item> SPOILED_PORKCHOP = REGISTRY.register("spoiled_porkchop", SpoiledPorkchopItem::new);
	public static final DeferredItem<Item> SPOILED_BEEF = REGISTRY.register("spoiled_beef", SpoiledBeefItem::new);
	public static final DeferredItem<Item> SALT = REGISTRY.register("salt", SaltItem::new);
	public static final DeferredItem<Item> CURED_STEAK = REGISTRY.register("cured_steak", CuredSteakItem::new);
	public static final DeferredItem<Item> CURED_PORKCHOP = REGISTRY.register("cured_porkchop", CuredPorkchopItem::new);
	public static final DeferredItem<Item> CURED_CHICKEN = REGISTRY.register("cured_chicken", CuredChickenItem::new);
	public static final DeferredItem<Item> CURED_RABBIT = REGISTRY.register("cured_rabbit", CuredRabbitItem::new);
	public static final DeferredItem<Item> CURED_MUTTON = REGISTRY.register("cured_mutton", CuredMuttonItem::new);
	public static final DeferredItem<Item> CURED_HEART = REGISTRY.register("cured_heart", CuredHeartItem::new);
	public static final DeferredItem<Item> CURED_INTESTINES = REGISTRY.register("cured_intestines", CuredIntestinesItem::new);
	public static final DeferredItem<Item> CURED_BRAIN = REGISTRY.register("cured_brain", CuredBrainItem::new);
	public static final DeferredItem<Item> CURED_LIVER = REGISTRY.register("cured_liver", CuredLiverItem::new);
	public static final DeferredItem<Item> CURED_STOMACH = REGISTRY.register("cured_stomach", CuredStomachItem::new);
	public static final DeferredItem<Item> CURED_LUNGS = REGISTRY.register("cured_lungs", CuredLungsItem::new);
	public static final DeferredItem<Item> SAND_SALT_DEPOSIT = block(SurvivalReimaginedModBlocks.SAND_SALT_DEPOSIT);
	public static final DeferredItem<Item> SHEEP_CARCASS = block(SurvivalReimaginedModBlocks.SHEEP_CARCASS);
	public static final DeferredItem<Item> SHEEP_HIDE = REGISTRY.register("sheep_hide", SheepHideItem::new);
	public static final DeferredItem<Item> SHEEP_LEG = block(SurvivalReimaginedModBlocks.SHEEP_LEG);
	public static final DeferredItem<Item> SHEEP_HEAD = block(SurvivalReimaginedModBlocks.SHEEP_HEAD);
	public static final DeferredItem<Item> CHICKEN_CARCASS = block(SurvivalReimaginedModBlocks.CHICKEN_CARCASS);
	public static final DeferredItem<Item> PIG_CARCASS = block(SurvivalReimaginedModBlocks.PIG_CARCASS);
	public static final DeferredItem<Item> PIG_HEAD = block(SurvivalReimaginedModBlocks.PIG_HEAD);
	public static final DeferredItem<Item> PIG_LEG = block(SurvivalReimaginedModBlocks.PIG_LEG);
	public static final DeferredItem<Item> BRONZE_KNIFE = REGISTRY.register("bronze_knife", BronzeKnifeItem::new);
	public static final DeferredItem<Item> BRONZE_KNIFE_BLADE = REGISTRY.register("bronze_knife_blade", BronzeKnifeBladeItem::new);
	public static final DeferredItem<Item> WOODEN_KNIFE = REGISTRY.register("wooden_knife", WoodenKnifeItem::new);
	public static final DeferredItem<Item> SMALL_STICK = REGISTRY.register("small_stick", SmallStickItem::new);
	public static final DeferredItem<Item> KNIFE_BLADE_MOLD = block(SurvivalReimaginedModBlocks.KNIFE_BLADE_MOLD);
	public static final DeferredItem<Item> CLAY_KNIFE_MOLD = block(SurvivalReimaginedModBlocks.CLAY_KNIFE_MOLD);
	public static final DeferredItem<Item> SMALL_COPPER_HANDLE = REGISTRY.register("small_copper_handle", SmallCopperHandleItem::new);
	public static final DeferredItem<Item> ROUGH_MANGANESE = REGISTRY.register("rough_manganese", RoughManganeseItem::new);
	public static final DeferredItem<Item> MANGANESE_INGOT = REGISTRY.register("manganese_ingot", ManganeseIngotItem::new);
	public static final DeferredItem<Item> RAW_MANGANESE = REGISTRY.register("raw_manganese", RawManganeseItem::new);
	public static final DeferredItem<Item> MANGANESE_CHUNK = REGISTRY.register("manganese_chunk", ManganeseChunkItem::new);
	public static final DeferredItem<Item> MANGANESE_NUGGET = REGISTRY.register("manganese_nugget", ManganeseNuggetItem::new);
	public static final DeferredItem<Item> ROUGH_STEEL = REGISTRY.register("rough_steel", RoughSteelItem::new);
	public static final DeferredItem<Item> STEEL_INGOT = REGISTRY.register("steel_ingot", SteelIngotItem::new);
	public static final DeferredItem<Item> MANGANESE_ORE = block(SurvivalReimaginedModBlocks.MANGANESE_ORE);
	public static final DeferredItem<Item> DEEPSLATE_MANGANESE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_MANGANESE_ORE);
	public static final DeferredItem<Item> BLOCK_OF_STEEL = block(SurvivalReimaginedModBlocks.BLOCK_OF_STEEL);
	public static final DeferredItem<Item> BLOCK_OF_MANGANESE = block(SurvivalReimaginedModBlocks.BLOCK_OF_MANGANESE);
	public static final DeferredItem<Item> BLOCK_OF_RAW_MANGANESE = block(SurvivalReimaginedModBlocks.BLOCK_OF_RAW_MANGANESE);
	public static final DeferredItem<Item> STEEL_SWORD = REGISTRY.register("steel_sword", SteelSwordItem::new);
	public static final DeferredItem<Item> STEEL_PICKAXE = REGISTRY.register("steel_pickaxe", SteelPickaxeItem::new);
	public static final DeferredItem<Item> STEEL_AXE = REGISTRY.register("steel_axe", SteelAxeItem::new);
	public static final DeferredItem<Item> STEEL_SHOVEL = REGISTRY.register("steel_shovel", SteelShovelItem::new);
	public static final DeferredItem<Item> STEEL_HOE = REGISTRY.register("steel_hoe", SteelHoeItem::new);
	public static final DeferredItem<Item> STEEL_ARMOR_HELMET = REGISTRY.register("steel_armor_helmet", SteelArmorItem.Helmet::new);
	public static final DeferredItem<Item> STEEL_ARMOR_CHESTPLATE = REGISTRY.register("steel_armor_chestplate", SteelArmorItem.Chestplate::new);
	public static final DeferredItem<Item> STEEL_ARMOR_LEGGINGS = REGISTRY.register("steel_armor_leggings", SteelArmorItem.Leggings::new);
	public static final DeferredItem<Item> STEEL_ARMOR_BOOTS = REGISTRY.register("steel_armor_boots", SteelArmorItem.Boots::new);
	public static final DeferredItem<Item> STEEL_KNIFE = REGISTRY.register("steel_knife", SteelKnifeItem::new);
	public static final DeferredItem<Item> STEEL_HAMMER = REGISTRY.register("steel_hammer", SteelHammerItem::new);
	public static final DeferredItem<Item> STEEL_SAW = REGISTRY.register("steel_saw", SteelSawItem::new);
	public static final DeferredItem<Item> STEEL_SWORD_BLADE = REGISTRY.register("steel_sword_blade", SteelSwordBladeItem::new);
	public static final DeferredItem<Item> STEEL_PICKAXE_HEAD = REGISTRY.register("steel_pickaxe_head", SteelPickaxeHeadItem::new);
	public static final DeferredItem<Item> STEEL_AXE_HEAD = REGISTRY.register("steel_axe_head", SteelAxeHeadItem::new);
	public static final DeferredItem<Item> STEEL_SHOVEL_HEAD = REGISTRY.register("steel_shovel_head", SteelShovelHeadItem::new);
	public static final DeferredItem<Item> STEEL_HOE_BLADE = REGISTRY.register("steel_hoe_blade", SteelHoeBladeItem::new);
	public static final DeferredItem<Item> STEEL_KNIFE_BLADE = REGISTRY.register("steel_knife_blade", SteelKnifeBladeItem::new);
	public static final DeferredItem<Item> STEEL_HAMMER_HEAD = REGISTRY.register("steel_hammer_head", SteelHammerHeadItem::new);
	public static final DeferredItem<Item> STEEL_SAW_BLADE = REGISTRY.register("steel_saw_blade", SteelSawBladeItem::new);
	public static final DeferredItem<Item> BRONZE_HANDLE = REGISTRY.register("bronze_handle", BronzeHandleItem::new);
	public static final DeferredItem<Item> SMALL_BRONZE_HANDLE = REGISTRY.register("small_bronze_handle", SmallBronzeHandleItem::new);
	public static final DeferredItem<Item> BRONZE_NUGGET = REGISTRY.register("bronze_nugget", BronzeNuggetItem::new);
	public static final DeferredItem<Item> GOLD_CHUNK = REGISTRY.register("gold_chunk", GoldChunkItem::new);
	public static final DeferredItem<Item> SANDSTONE_CHUNK = REGISTRY.register("sandstone_chunk", SandstoneChunkItem::new);
	public static final DeferredItem<Item> RED_SANDSTONE_CHUNK = REGISTRY.register("red_sandstone_chunk", RedSandstoneChunkItem::new);
	public static final DeferredItem<Item> GLASS_SHARD = REGISTRY.register("glass_shard", GlassShardItem::new);
	public static final DeferredItem<Item> DIRT_PILE = REGISTRY.register("dirt_pile", DirtPileItem::new);
	public static final DeferredItem<Item> SAND_PILE = REGISTRY.register("sand_pile", SandPileItem::new);
	public static final DeferredItem<Item> RED_SAND_PILE = REGISTRY.register("red_sand_pile", RedSandPileItem::new);
	public static final DeferredItem<Item> COARSE_DIRT_PILE = REGISTRY.register("coarse_dirt_pile", CoarseDirtPileItem::new);
	public static final DeferredItem<Item> ROOTED_DIRT_PILE = REGISTRY.register("rooted_dirt_pile", RootedDirtPileItem::new);
	public static final DeferredItem<Item> GRAVEL_PILE = REGISTRY.register("gravel_pile", GravelPileItem::new);
	public static final DeferredItem<Item> SOUL_SAND_PILE = REGISTRY.register("soul_sand_pile", SoulSandPileItem::new);
	public static final DeferredItem<Item> MUD_PILE = REGISTRY.register("mud_pile", MudPileItem::new);
	public static final DeferredItem<Item> RAW_REDSTONE = REGISTRY.register("raw_redstone", RawRedstoneItem::new);
	public static final DeferredItem<Item> REDSTONE_CHUNK = REGISTRY.register("redstone_chunk", RedstoneChunkItem::new);
	public static final DeferredItem<Item> ROUGH_REDSTONE = REGISTRY.register("rough_redstone", RoughRedstoneItem::new);
	public static final DeferredItem<Item> REDSTONE_INGOT = REGISTRY.register("redstone_ingot", RedstoneIngotItem::new);
	public static final DeferredItem<Item> REDSTONE_NUGGET = REGISTRY.register("redstone_nugget", RedstoneNuggetItem::new);
	public static final DeferredItem<Item> BLOCK_OF_RAW_REDSTONE = block(SurvivalReimaginedModBlocks.BLOCK_OF_RAW_REDSTONE);
	public static final DeferredItem<Item> BRONZE_CHISEL = REGISTRY.register("bronze_chisel", BronzeChiselItem::new);
	public static final DeferredItem<Item> STEEL_CHISEL = REGISTRY.register("steel_chisel", SteelChiselItem::new);
	public static final DeferredItem<Item> STEEL_NUGGET = REGISTRY.register("steel_nugget", SteelNuggetItem::new);
	public static final DeferredItem<Item> MUD_ROCK = REGISTRY.register("mud_rock", MudRockItem::new);
	public static final DeferredItem<Item> CRYING_OBSIDIAN_ROCK = REGISTRY.register("crying_obsidian_rock", CryingObsidianRockItem::new);
	public static final DeferredItem<Item> ANCIENT_DEBRIS_CHUNK = REGISTRY.register("ancient_debris_chunk", AncientDebrisChunkItem::new);
	public static final DeferredItem<Item> MINERAL_PROCESSING_TABLE = block(SurvivalReimaginedModBlocks.MINERAL_PROCESSING_TABLE);
	public static final DeferredItem<Item> REDSTONE_CHARGED_URANIUM_DUST = REGISTRY.register("redstone_charged_uranium_dust", RedstoneChargedUraniumDustItem::new);
	public static final DeferredItem<Item> REACTOR_ROD = REGISTRY.register("reactor_rod", ReactorRodItem::new);
	public static final DeferredItem<Item> DEPLETED_REACTOR_ROD = REGISTRY.register("depleted_reactor_rod", DepletedReactorRodItem::new);
	public static final DeferredItem<Item> DIAMOND_PLATED_INGOT = REGISTRY.register("diamond_plated_ingot", DiamondPlatedIngotItem::new);
	public static final DeferredItem<Item> DIAMOND_SWORD_BLADE = REGISTRY.register("diamond_sword_blade", DiamondSwordBladeItem::new);
	public static final DeferredItem<Item> DIAMOND_AXE_HEAD = REGISTRY.register("diamond_axe_head", DiamondAxeHeadItem::new);
	public static final DeferredItem<Item> DIAMOND_HOE_BLADE = REGISTRY.register("diamond_hoe_blade", DiamondHoeBladeItem::new);
	public static final DeferredItem<Item> DIAMOND_PICKAXE_HEAD = REGISTRY.register("diamond_pickaxe_head", DiamondPickaxeHeadItem::new);
	public static final DeferredItem<Item> DIAMOND_SHOVEL_HEAD = REGISTRY.register("diamond_shovel_head", DiamondShovelHeadItem::new);
	public static final DeferredItem<Item> DIAMOND_KNIFE_BLADE = REGISTRY.register("diamond_knife_blade", DiamondKnifeBladeItem::new);
	public static final DeferredItem<Item> DIAMOND_HAMMER_HEAD = REGISTRY.register("diamond_hammer_head", DiamondHammerHeadItem::new);
	public static final DeferredItem<Item> DIAMOND_SAW_BLADE = REGISTRY.register("diamond_saw_blade", DiamondSawBladeItem::new);
	public static final DeferredItem<Item> DIAMOND_HAMMER = REGISTRY.register("diamond_hammer", DiamondHammerItem::new);
	public static final DeferredItem<Item> DIAMOND_KNIFE = REGISTRY.register("diamond_knife", DiamondKnifeItem::new);
	public static final DeferredItem<Item> DIAMOND_SAW = REGISTRY.register("diamond_saw", DiamondSawItem::new);
	public static final DeferredItem<Item> DIAMOND_CHISEL = REGISTRY.register("diamond_chisel", DiamondChiselItem::new);
	public static final DeferredItem<Item> OBSIDIAN_HANDLE = REGISTRY.register("obsidian_handle", ObsidianHandleItem::new);
	public static final DeferredItem<Item> SMALL_OBSIDIAN_HANDLE = REGISTRY.register("small_obsidian_handle", SmallObsidianHandleItem::new);
	public static final DeferredItem<Item> ROUGH_PLATED_DIAMOND = REGISTRY.register("rough_plated_diamond", RoughPlatedDiamondItem::new);
	public static final DeferredItem<Item> EMBEDDED_OBSIDIAN = block(SurvivalReimaginedModBlocks.EMBEDDED_OBSIDIAN);
	public static final DeferredItem<Item> BACKPACK = REGISTRY.register("backpack", BackpackItem::new);
	public static final DeferredItem<Item> GOLD_ROD = REGISTRY.register("gold_rod", GoldRodItem::new);
	public static final DeferredItem<Item> BLOOD_MOON_ZOMBIE_SPAWN_EGG = REGISTRY.register("blood_moon_zombie_spawn_egg", () -> new DeferredSpawnEggItem(SurvivalReimaginedModEntities.BLOOD_MOON_ZOMBIE, -8966363, -12046045, new Item.Properties()));
	public static final DeferredItem<Item> FLESH = REGISTRY.register("flesh", FleshItem::new);
	public static final DeferredItem<Item> HEART_OF_THE_BLOOD_MOON = REGISTRY.register("heart_of_the_blood_moon", HeartOfTheBloodMoonItem::new);
	public static final DeferredItem<Item> HEART_OF_THE_NETHER = REGISTRY.register("heart_of_the_nether", HeartOfTheNetherItem::new);
	public static final DeferredItem<Item> BLOOD_MOONS_MUSIC_DISC = REGISTRY.register("blood_moons_music_disc", BloodMoonsMusicDiscItem::new);
	public static final DeferredItem<Item> BLOOD_MOON_DISC_FRAGMENT = REGISTRY.register("blood_moon_disc_fragment", BloodMoonDiscFragmentItem::new);
	public static final DeferredItem<Item> COPPER_ROCK_BLOCK = block(SurvivalReimaginedModBlocks.COPPER_ROCK_BLOCK);
	public static final DeferredItem<Item> APPLE_OAK_LEAVES = block(SurvivalReimaginedModBlocks.APPLE_OAK_LEAVES);
	public static final DeferredItem<Item> APPLE_TREE_SAPLING = block(SurvivalReimaginedModBlocks.APPLE_TREE_SAPLING);
	public static final DeferredItem<Item> APPLE = block(SurvivalReimaginedModBlocks.APPLE);
	public static final DeferredItem<Item> EYE_OF_ENDER_FUSION_DUST = REGISTRY.register("eye_of_ender_fusion_dust", EyeOfEnderFusionDustItem::new);
	public static final DeferredItem<Item> WHITE_GLASS_SHARD = REGISTRY.register("white_glass_shard", WhiteGlassShardItem::new);
	public static final DeferredItem<Item> ORANGE_GLASS_SHARD = REGISTRY.register("orange_glass_shard", OrangeGlassShardItem::new);
	public static final DeferredItem<Item> MAGENTA_GLASS_SHARD = REGISTRY.register("magenta_glass_shard", MagentaGlassShardItem::new);
	public static final DeferredItem<Item> LIGHT_BLUE_GLASS_SHARD = REGISTRY.register("light_blue_glass_shard", LightBlueGlassShardItem::new);
	public static final DeferredItem<Item> YELLOW_GLASS_SHARD = REGISTRY.register("yellow_glass_shard", YellowGlassShardItem::new);
	public static final DeferredItem<Item> LIME_GREEN_GLASS_SHARD = REGISTRY.register("lime_green_glass_shard", LimeGreenGlassShardItem::new);
	public static final DeferredItem<Item> PINK_GLASS_SHARD = REGISTRY.register("pink_glass_shard", PinkGlassShardItem::new);
	public static final DeferredItem<Item> BLACK_GLASS_SHARD = REGISTRY.register("black_glass_shard", BlackGlassShardItem::new);
	public static final DeferredItem<Item> LIGHT_GREY_GLASS_SHARD = REGISTRY.register("light_grey_glass_shard", LightGreyGlassShardItem::new);
	public static final DeferredItem<Item> CYAN_GLASS_SHARD = REGISTRY.register("cyan_glass_shard", CyanGlassShardItem::new);
	public static final DeferredItem<Item> PURPLE_GLASS_SHARD = REGISTRY.register("purple_glass_shard", PurpleGlassShardItem::new);
	public static final DeferredItem<Item> BLUE_GLASS_SHARD = REGISTRY.register("blue_glass_shard", BlueGlassShardItem::new);
	public static final DeferredItem<Item> GREEN_GLASS_SHARD = REGISTRY.register("green_glass_shard", GreenGlassShardItem::new);
	public static final DeferredItem<Item> BROWN_GLASS_SHARD = REGISTRY.register("brown_glass_shard", BrownGlassShardItem::new);
	public static final DeferredItem<Item> RED_GLASS_SHARD = REGISTRY.register("red_glass_shard", RedGlassShardItem::new);
	public static final DeferredItem<Item> GREY_GLASS_SHARD = REGISTRY.register("grey_glass_shard", GreyGlassShardItem::new);
	public static final DeferredItem<Item> INGOT_MOLD = block(SurvivalReimaginedModBlocks.INGOT_MOLD);
	public static final DeferredItem<Item> INGOT_CLAY_MOLD = block(SurvivalReimaginedModBlocks.INGOT_CLAY_MOLD);
	public static final DeferredItem<Item> HEMP_SEEDS = REGISTRY.register("hemp_seeds", HempSeedsItem::new);
	public static final DeferredItem<Item> HEMP = block(SurvivalReimaginedModBlocks.HEMP);
	public static final DeferredItem<Item> HEMP_LEAF = REGISTRY.register("hemp_leaf", HempLeafItem::new);
	public static final DeferredItem<Item> HEMP_PAPER = REGISTRY.register("hemp_paper", HempPaperItem::new);
	public static final DeferredItem<Item> ROUGH_NETHERITE = REGISTRY.register("rough_netherite", RoughNetheriteItem::new);
	public static final DeferredItem<Item> NETHERITE_HAMMER = REGISTRY.register("netherite_hammer", NetheriteHammerItem::new);
	public static final DeferredItem<Item> NETHERITE_KNIFE = REGISTRY.register("netherite_knife", NetheriteKnifeItem::new);
	public static final DeferredItem<Item> NETHERITE_SAW = REGISTRY.register("netherite_saw", NetheriteSawItem::new);
	public static final DeferredItem<Item> WOOD_INGOT = REGISTRY.register("wood_ingot", WoodIngotItem::new);
	public static final DeferredItem<Item> ROUGH_ZINC = REGISTRY.register("rough_zinc", RoughZincItem::new);
	public static final DeferredItem<Item> ROUGH_BRASS = REGISTRY.register("rough_brass", RoughBrassItem::new);
	public static final DeferredItem<Item> RAW_ZINC_NUGGET = REGISTRY.register("raw_zinc_nugget", RawZincNuggetItem::new);
	public static final DeferredItem<Item> LIMESTONE_ROCK = block(SurvivalReimaginedModBlocks.LIMESTONE_ROCK);
	public static final DeferredItem<Item> VERIDIUM_ROCK = block(SurvivalReimaginedModBlocks.VERIDIUM_ROCK);
	public static final DeferredItem<Item> OCHRUM_ROCK = block(SurvivalReimaginedModBlocks.OCHRUM_ROCK);
	public static final DeferredItem<Item> CRIMSITE_ROCK = block(SurvivalReimaginedModBlocks.CRIMSITE_ROCK);
	public static final DeferredItem<Item> SCORCHIA_ROCK = block(SurvivalReimaginedModBlocks.SCORCHIA_ROCK);
	public static final DeferredItem<Item> ASURINE_CRYSTAL = block(SurvivalReimaginedModBlocks.ASURINE_CRYSTAL);
	public static final DeferredItem<Item> SCORIA_ROCK = block(SurvivalReimaginedModBlocks.SCORIA_ROCK);
	public static final DeferredItem<Item> SHALE = block(SurvivalReimaginedModBlocks.SHALE);
	public static final DeferredItem<Item> SHALE_ROCK = block(SurvivalReimaginedModBlocks.SHALE_ROCK);
	public static final DeferredItem<Item> TITANIUM_ORE = block(SurvivalReimaginedModBlocks.TITANIUM_ORE);
	public static final DeferredItem<Item> DEEPSLATE_TITANIUM_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_TITANIUM_ORE);
	public static final DeferredItem<Item> SHALE_TITANIUM_ORE = block(SurvivalReimaginedModBlocks.SHALE_TITANIUM_ORE);
	public static final DeferredItem<Item> RAW_TITANIUM = REGISTRY.register("raw_titanium", RawTitaniumItem::new);
	public static final DeferredItem<Item> ROUGH_TITANIUM = REGISTRY.register("rough_titanium", RoughTitaniumItem::new);
	public static final DeferredItem<Item> TITANIUM_INGOT = REGISTRY.register("titanium_ingot", TitaniumIngotItem::new);
	public static final DeferredItem<Item> RAW_TITANIUM_NUGGET = REGISTRY.register("raw_titanium_nugget", RawTitaniumNuggetItem::new);
	public static final DeferredItem<Item> TITANIUM_NUGGET = REGISTRY.register("titanium_nugget", TitaniumNuggetItem::new);
	public static final DeferredItem<Item> BLOCK_OF_TITANIUM = block(SurvivalReimaginedModBlocks.BLOCK_OF_TITANIUM);
	public static final DeferredItem<Item> BLOCK_OF_RAW_TITANIUM = block(SurvivalReimaginedModBlocks.BLOCK_OF_RAW_TITANIUM);
	public static final DeferredItem<Item> RADIANT_LOG = block(SurvivalReimaginedModBlocks.RADIANT_LOG);
	public static final DeferredItem<Item> RADIATED_BARK = REGISTRY.register("radiated_bark", RadiatedBarkItem::new);
	public static final DeferredItem<Item> RADIATED_PLANK = REGISTRY.register("radiated_plank", RadiatedPlankItem::new);
	public static final DeferredItem<Item> STRIPPED_RADIANT_LOG = block(SurvivalReimaginedModBlocks.STRIPPED_RADIANT_LOG);
	public static final DeferredItem<Item> RADIANT_PLANKS = block(SurvivalReimaginedModBlocks.RADIANT_PLANKS);
	public static final DeferredItem<Item> RADIATED_LEAVES = block(SurvivalReimaginedModBlocks.RADIATED_LEAVES);
	public static final DeferredItem<Item> RADIATED_SAPLING = block(SurvivalReimaginedModBlocks.RADIATED_SAPLING);
	public static final DeferredItem<Item> RADIATED_STAIRS = block(SurvivalReimaginedModBlocks.RADIATED_STAIRS);
	public static final DeferredItem<Item> RADIATED_SLAB = block(SurvivalReimaginedModBlocks.RADIATED_SLAB);
	public static final DeferredItem<Item> RADIATED_FENCE = block(SurvivalReimaginedModBlocks.RADIATED_FENCE);
	public static final DeferredItem<Item> RADIATED_FENCE_GATE = block(SurvivalReimaginedModBlocks.RADIATED_FENCE_GATE);
	public static final DeferredItem<Item> RADIATED_PRESSURE_PLATE = block(SurvivalReimaginedModBlocks.RADIATED_PRESSURE_PLATE);
	public static final DeferredItem<Item> RADIATED_BUTTON = block(SurvivalReimaginedModBlocks.RADIATED_BUTTON);
	public static final DeferredItem<Item> RADIATED_SHALE = block(SurvivalReimaginedModBlocks.RADIATED_SHALE);
	public static final DeferredItem<Item> THIN_RADIATED_VINES = block(SurvivalReimaginedModBlocks.THIN_RADIATED_VINES);
	public static final DeferredItem<Item> THIN_RADIATED_VINE_BASE = block(SurvivalReimaginedModBlocks.THIN_RADIATED_VINE_BASE);
	public static final DeferredItem<Item> RADIATED_MOSS = block(SurvivalReimaginedModBlocks.RADIATED_MOSS);
	public static final DeferredItem<Item> RADIATED_TALL_GRASS = block(SurvivalReimaginedModBlocks.RADIATED_TALL_GRASS);
	public static final DeferredItem<Item> THICK_RADIATED_VINES = block(SurvivalReimaginedModBlocks.THICK_RADIATED_VINES);
	public static final DeferredItem<Item> THICK_RADIATED_VINES_BASE = block(SurvivalReimaginedModBlocks.THICK_RADIATED_VINES_BASE);
	public static final DeferredItem<Item> RADIATED_ORCHID = block(SurvivalReimaginedModBlocks.RADIATED_ORCHID);
	public static final DeferredItem<Item> SHALE_URANINITE_ORE = block(SurvivalReimaginedModBlocks.SHALE_URANINITE_ORE);
	public static final DeferredItem<Item> URANINITE_ORE = block(SurvivalReimaginedModBlocks.URANINITE_ORE);
	public static final DeferredItem<Item> DEEPSLATE_URANINITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_URANINITE_ORE);
	public static final DeferredItem<Item> URANIUM_DUST = REGISTRY.register("uranium_dust", UraniumDustItem::new);
	public static final DeferredItem<Item> RAW_URANINITE = REGISTRY.register("raw_uraninite", RawUraniniteItem::new);
	public static final DeferredItem<Item> RAW_URANINITE_NUGGET = REGISTRY.register("raw_uraninite_nugget", RawUraniniteNuggetItem::new);
	public static final DeferredItem<Item> BLOCK_OF_RAW_URANINITE = block(SurvivalReimaginedModBlocks.BLOCK_OF_RAW_URANINITE);
	public static final DeferredItem<Item> POLISHED_SHALE = block(SurvivalReimaginedModBlocks.POLISHED_SHALE);
	public static final DeferredItem<Item> POLISHED_SHALE_BRICKS = block(SurvivalReimaginedModBlocks.POLISHED_SHALE_BRICKS);
	public static final DeferredItem<Item> POLISHED_CHISELED_SHALE = block(SurvivalReimaginedModBlocks.POLISHED_CHISELED_SHALE);
	public static final DeferredItem<Item> POLISHED_SHALE_STAIRS = block(SurvivalReimaginedModBlocks.POLISHED_SHALE_STAIRS);
	public static final DeferredItem<Item> POLISHED_SHALE_BRICK_STAIRS = block(SurvivalReimaginedModBlocks.POLISHED_SHALE_BRICK_STAIRS);
	public static final DeferredItem<Item> POLISHED_SHALE_SLAB = block(SurvivalReimaginedModBlocks.POLISHED_SHALE_SLAB);
	public static final DeferredItem<Item> POLISHED_SHALE_BRICK_SLAB = block(SurvivalReimaginedModBlocks.POLISHED_SHALE_BRICK_SLAB);
	public static final DeferredItem<Item> POLISHED_SHALE_WALL = block(SurvivalReimaginedModBlocks.POLISHED_SHALE_WALL);
	public static final DeferredItem<Item> POLOSHED_SHALE_BRICK_WALL = block(SurvivalReimaginedModBlocks.POLOSHED_SHALE_BRICK_WALL);
	public static final DeferredItem<Item> SHALE_STAIRS = block(SurvivalReimaginedModBlocks.SHALE_STAIRS);
	public static final DeferredItem<Item> SHALE_SLAB = block(SurvivalReimaginedModBlocks.SHALE_SLAB);
	public static final DeferredItem<Item> SHALE_WALL = block(SurvivalReimaginedModBlocks.SHALE_WALL);
	public static final DeferredItem<Item> ROUGH_URANIUM = REGISTRY.register("rough_uranium", RoughUraniumItem::new);
	public static final DeferredItem<Item> URANIUM_INGOT = REGISTRY.register("uranium_ingot", UraniumIngotItem::new);
	public static final DeferredItem<Item> URANIUM_NUGGET = REGISTRY.register("uranium_nugget", UraniumNuggetItem::new);
	public static final DeferredItem<Item> BLOCK_OF_URANIUM = block(SurvivalReimaginedModBlocks.BLOCK_OF_URANIUM);
	public static final DeferredItem<Item> GAS_MASK_FILTER = REGISTRY.register("gas_mask_filter", GasMaskFilterItem::new);
	public static final DeferredItem<Item> HEMP_MESH = REGISTRY.register("hemp_mesh", HempMeshItem::new);
	public static final DeferredItem<Item> USED_FILTER = REGISTRY.register("used_filter", UsedFilterItem::new);
	public static final DeferredItem<Item> URANIUM_ROD = block(SurvivalReimaginedModBlocks.URANIUM_ROD);
	public static final DeferredItem<Item> RADIANT_TRAPDOOR = block(SurvivalReimaginedModBlocks.RADIANT_TRAPDOOR);
	public static final DeferredItem<Item> RADIANT_DOOR = doubleBlock(SurvivalReimaginedModBlocks.RADIANT_DOOR);
	public static final DeferredItem<Item> STEEL_DOOR = doubleBlock(SurvivalReimaginedModBlocks.STEEL_DOOR);
	public static final DeferredItem<Item> STEEL_TRAPDOOR = block(SurvivalReimaginedModBlocks.STEEL_TRAPDOOR);
	public static final DeferredItem<Item> ROUGH_TURANITE = REGISTRY.register("rough_turanite", RoughTuraniteItem::new);
	public static final DeferredItem<Item> TURANITE_INGOT = REGISTRY.register("turanite_ingot", TuraniteIngotItem::new);
	public static final DeferredItem<Item> TURANITE_NUGGET = REGISTRY.register("turanite_nugget", TuraniteNuggetItem::new);
	public static final DeferredItem<Item> TURANITE_BLOCK = block(SurvivalReimaginedModBlocks.TURANITE_BLOCK);
	public static final DeferredItem<Item> ADVANCED_REACTOR_ROD = REGISTRY.register("advanced_reactor_rod", AdvancedReactorRodItem::new);
	public static final DeferredItem<Item> ADVANCED_ALLOY_FORGE = block(SurvivalReimaginedModBlocks.ADVANCED_ALLOY_FORGE);
	public static final DeferredItem<Item> DRAINED_ADVANCED_REACTOR_ROD = REGISTRY.register("drained_advanced_reactor_rod", DrainedAdvancedReactorRodItem::new);
	public static final DeferredItem<Item> FUEL_UPGRADE = REGISTRY.register("fuel_upgrade", FuelUpgradeItem::new);
	public static final DeferredItem<Item> FUEL_UPGRADE_MKII = REGISTRY.register("fuel_upgrade_mkii", FuelUpgradeMKIIItem::new);
	public static final DeferredItem<Item> YIELD_UPGRADE = REGISTRY.register("yield_upgrade", YieldUpgradeItem::new);
	public static final DeferredItem<Item> YIELD_UPGRADE_MKII = REGISTRY.register("yield_upgrade_mkii", YieldUpgradeMKIIItem::new);
	public static final DeferredItem<Item> YIELD_UPGRADE_MKIII = REGISTRY.register("yield_upgrade_mkiii", YieldUpgradeMKIIIItem::new);
	public static final DeferredItem<Item> EFFICIENCY_UPGRADE = REGISTRY.register("efficiency_upgrade", EfficiencyUpgradeItem::new);
	public static final DeferredItem<Item> BLOCK_PACKAGING_UPGRADE = REGISTRY.register("block_packaging_upgrade", BlockPackagingUpgradeItem::new);
	public static final DeferredItem<Item> PLATED_DIAMOND_BLOCK = block(SurvivalReimaginedModBlocks.PLATED_DIAMOND_BLOCK);
	public static final DeferredItem<Item> NETHERITE_SCRAP_BLOCK = block(SurvivalReimaginedModBlocks.NETHERITE_SCRAP_BLOCK);
	public static final DeferredItem<Item> BLACK_SAND_PILE = REGISTRY.register("black_sand_pile", BlackSandPileItem::new);
	public static final DeferredItem<Item> ORANGE_SAND_PILE = REGISTRY.register("orange_sand_pile", OrangeSandPileItem::new);
	public static final DeferredItem<Item> WHITE_SAND_PILE = REGISTRY.register("white_sand_pile", WhiteSandPileItem::new);
	public static final DeferredItem<Item> BLACK_SANDSTONE_CHUNK = REGISTRY.register("black_sandstone_chunk", BlackSandstoneChunkItem::new);
	public static final DeferredItem<Item> ORANGE_SANDSTONE_CHUNK = REGISTRY.register("orange_sandstone_chunk", OrangeSandstoneChunkItem::new);
	public static final DeferredItem<Item> WHITE_SANDSTONE_CHUNK = REGISTRY.register("white_sandstone_chunk", WhiteSandstoneChunkItem::new);
	public static final DeferredItem<Item> THERMAL_CALCITE_ROCK = REGISTRY.register("thermal_calcite_rock", ThermalCalciteRockItem::new);
	public static final DeferredItem<Item> BRIMSTONE_ROCK = REGISTRY.register("brimstone_rock", BrimstoneRockItem::new);
	public static final DeferredItem<Item> FIR_BARK = REGISTRY.register("fir_bark", FirBarkItem::new);
	public static final DeferredItem<Item> PINE_BARK = REGISTRY.register("pine_bark", PineBarkItem::new);
	public static final DeferredItem<Item> MAPLE_BARK = REGISTRY.register("maple_bark", MapleBarkItem::new);
	public static final DeferredItem<Item> REDWOOD_BARK = REGISTRY.register("redwood_bark", RedwoodBarkItem::new);
	public static final DeferredItem<Item> MAHOGANY_BARK = REGISTRY.register("mahogany_bark", MahoganyBarkItem::new);
	public static final DeferredItem<Item> JACARANDA_BARK = REGISTRY.register("jacaranda_bark", JacarandaBarkItem::new);
	public static final DeferredItem<Item> PALM_BARK = REGISTRY.register("palm_bark", PalmBarkItem::new);
	public static final DeferredItem<Item> WILLOW_BARK = REGISTRY.register("willow_bark", WillowBarkItem::new);
	public static final DeferredItem<Item> DEAD_BARK = REGISTRY.register("dead_bark", DeadBarkItem::new);
	public static final DeferredItem<Item> MAGIC_BARK = REGISTRY.register("magic_bark", MagicBarkItem::new);
	public static final DeferredItem<Item> UMBRAN_B_ARK = REGISTRY.register("umbran_b_ark", UmbranBArkItem::new);
	public static final DeferredItem<Item> EMPYREAL_BARK = REGISTRY.register("empyreal_bark", EmpyrealBarkItem::new);
	public static final DeferredItem<Item> HELL_BARK = REGISTRY.register("hell_bark", HellBarkItem::new);
	public static final DeferredItem<Item> SILVER_ORE = block(SurvivalReimaginedModBlocks.SILVER_ORE);
	public static final DeferredItem<Item> RAW_SILVER = REGISTRY.register("raw_silver", RawSilverItem::new);
	public static final DeferredItem<Item> ROUGH_SILVER = REGISTRY.register("rough_silver", RoughSilverItem::new);
	public static final DeferredItem<Item> SILVER_INGOT = REGISTRY.register("silver_ingot", SilverIngotItem::new);
	public static final DeferredItem<Item> RAW_SILVER_BLOCK = block(SurvivalReimaginedModBlocks.RAW_SILVER_BLOCK);
	public static final DeferredItem<Item> SILVER_BLOCK = block(SurvivalReimaginedModBlocks.SILVER_BLOCK);
	public static final DeferredItem<Item> SILVER_NUGGET = REGISTRY.register("silver_nugget", SilverNuggetItem::new);
	public static final DeferredItem<Item> RAW_SILVER_NUGGET = REGISTRY.register("raw_silver_nugget", RawSilverNuggetItem::new);
	public static final DeferredItem<Item> SAPPHIRE_ORE = block(SurvivalReimaginedModBlocks.SAPPHIRE_ORE);
	public static final DeferredItem<Item> DEEPSLATE_SAPPHIRE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_SAPPHIRE_ORE);
	public static final DeferredItem<Item> SAPPHIRE = REGISTRY.register("sapphire", SapphireItem::new);
	public static final DeferredItem<Item> SAPPHIRE_BLOCK = block(SurvivalReimaginedModBlocks.SAPPHIRE_BLOCK);
	public static final DeferredItem<Item> SAPPHIRE_SILVER_RUNE = REGISTRY.register("sapphire_silver_rune", SapphireSilverRuneItem::new);
	public static final DeferredItem<Item> SAPPHIRE_GOLD_RUNE = REGISTRY.register("sapphire_gold_rune", SapphireGoldRuneItem::new);
	public static final DeferredItem<Item> AAF_SCRIPTURE = REGISTRY.register("aaf_scripture", AAFScriptureItem::new);
	public static final DeferredItem<Item> BLOOD_MOON_ITEM = REGISTRY.register("blood_moon_item", BloodMoonItemItem::new);
	public static final DeferredItem<Item> SOLAR_ECLIPSE_ITEM = REGISTRY.register("solar_eclipse_item", SolarEclipseItemItem::new);
	public static final DeferredItem<Item> RADIATION_ITEM = REGISTRY.register("radiation_item", RadiationItemItem::new);
	public static final DeferredItem<Item> GAS_MASK_HELMET = REGISTRY.register("gas_mask_helmet", GasMaskItem.Helmet::new);
	public static final DeferredItem<Item> CRIMSON_ARACHNID_SPAWN_EGG = REGISTRY.register("crimson_arachnid_spawn_egg", () -> new DeferredSpawnEggItem(SurvivalReimaginedModEntities.CRIMSON_ARACHNID, -14941694, -426884, new Item.Properties()));
	public static final DeferredItem<Item> ALPHA_CRIMSON_ARACHNID_SPAWN_EGG = REGISTRY.register("alpha_crimson_arachnid_spawn_egg",
			() -> new DeferredSpawnEggItem(SurvivalReimaginedModEntities.ALPHA_CRIMSON_ARACHNID, -14941694, -426884, new Item.Properties()));
	public static final DeferredItem<Item> CRIMSON_THREAD = REGISTRY.register("crimson_thread", CrimsonThreadItem::new);
	public static final DeferredItem<Item> SULFUR_BLOCK = block(SurvivalReimaginedModBlocks.SULFUR_BLOCK);
	public static final DeferredItem<Item> NITRE_BLOCK = block(SurvivalReimaginedModBlocks.NITRE_BLOCK);
	public static final DeferredItem<Item> SULFUR = REGISTRY.register("sulfur", SulfurItem::new);
	public static final DeferredItem<Item> NITRE = REGISTRY.register("nitre", NitreItem::new);
	public static final DeferredItem<Item> MORTAR_PESTAL = REGISTRY.register("mortar_pestal", MortarPestalItem::new);
	public static final DeferredItem<Item> CHARCOAL_POWDER = REGISTRY.register("charcoal_powder", CharcoalPowderItem::new);
	public static final DeferredItem<Item> SULFUR_POWDER = REGISTRY.register("sulfur_powder", SulfurPowderItem::new);
	public static final DeferredItem<Item> SALTPETER = REGISTRY.register("saltpeter", SaltpeterItem::new);
	public static final DeferredItem<Item> RUNE_CLAY_MOLD = block(SurvivalReimaginedModBlocks.RUNE_CLAY_MOLD);
	public static final DeferredItem<Item> RUNE_MOLD = block(SurvivalReimaginedModBlocks.RUNE_MOLD);
	public static final DeferredItem<Item> WOODEN_RUNE = REGISTRY.register("wooden_rune", WoodenRuneItem::new);
	public static final DeferredItem<Item> EMPTY_SILVER_RUNE = REGISTRY.register("empty_silver_rune", EmptySilverRuneItem::new);
	public static final DeferredItem<Item> EMPTY_GOLD_RUNE = REGISTRY.register("empty_gold_rune", EmptyGoldRuneItem::new);
	public static final DeferredItem<Item> RUNE_MAGIC_INFUSER = block(SurvivalReimaginedModBlocks.RUNE_MAGIC_INFUSER);
	public static final DeferredItem<Item> RUBY_ORE = block(SurvivalReimaginedModBlocks.RUBY_ORE);
	public static final DeferredItem<Item> DEEPSLATE_RUBY_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_RUBY_ORE);
	public static final DeferredItem<Item> RUBY = REGISTRY.register("ruby", RubyItem::new);
	public static final DeferredItem<Item> BLOCK_OF_RUBY = block(SurvivalReimaginedModBlocks.BLOCK_OF_RUBY);
	public static final DeferredItem<Item> AMBER_ORE = block(SurvivalReimaginedModBlocks.AMBER_ORE);
	public static final DeferredItem<Item> DEEPSLATE_AMBER_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_AMBER_ORE);
	public static final DeferredItem<Item> BLOCK_OF_AMBER = block(SurvivalReimaginedModBlocks.BLOCK_OF_AMBER);
	public static final DeferredItem<Item> AMBER = REGISTRY.register("amber", AmberItem::new);
	public static final DeferredItem<Item> WISTERIA_LOG = block(SurvivalReimaginedModBlocks.WISTERIA_LOG);
	public static final DeferredItem<Item> WISTERIA_LEAVES = block(SurvivalReimaginedModBlocks.WISTERIA_LEAVES);
	public static final DeferredItem<Item> FLOWING_WISTERIA_LEAVES = block(SurvivalReimaginedModBlocks.FLOWING_WISTERIA_LEAVES);
	public static final DeferredItem<Item> WISTERIA_SPIDER_LILY = block(SurvivalReimaginedModBlocks.WISTERIA_SPIDER_LILY);
	public static final DeferredItem<Item> WISTERIA_SAPLING = block(SurvivalReimaginedModBlocks.WISTERIA_SAPLING);
	public static final DeferredItem<Item> WISTERIA_LEAF_LITTER = block(SurvivalReimaginedModBlocks.WISTERIA_LEAF_LITTER);
	public static final DeferredItem<Item> WISTERIA_FLOWER_UPPER = block(SurvivalReimaginedModBlocks.WISTERIA_FLOWER_UPPER);
	public static final DeferredItem<Item> WISTERIA_FLOWER_LOWER = block(SurvivalReimaginedModBlocks.WISTERIA_FLOWER_LOWER);
	public static final DeferredItem<Item> DEEPSLATE_TIN_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_TIN_ORE);
	public static final DeferredItem<Item> SILVER_AMBER_RUNE = REGISTRY.register("silver_amber_rune", SilverAmberRuneItem::new);
	public static final DeferredItem<Item> GOLD_AMBER_RUNE = REGISTRY.register("gold_amber_rune", GoldAmberRuneItem::new);
	public static final DeferredItem<Item> GOLD_DIAMOND_RUNE = REGISTRY.register("gold_diamond_rune", GoldDiamondRuneItem::new);
	public static final DeferredItem<Item> SILVER_DIAMOND_RUNE = REGISTRY.register("silver_diamond_rune", SilverDiamondRuneItem::new);
	public static final DeferredItem<Item> SILVER_EMERALD_RUNE = REGISTRY.register("silver_emerald_rune", SilverEmeraldRuneItem::new);
	public static final DeferredItem<Item> GOLD_EMERALD_RUNE = REGISTRY.register("gold_emerald_rune", GoldEmeraldRuneItem::new);
	public static final DeferredItem<Item> SILVER_RUBY_RUNE = REGISTRY.register("silver_ruby_rune", SilverRubyRuneItem::new);
	public static final DeferredItem<Item> GOLD_RUBY_RUNE = REGISTRY.register("gold_ruby_rune", GoldRubyRuneItem::new);
	public static final DeferredItem<Item> GOLD_LAPIS_RUNE = REGISTRY.register("gold_lapis_rune", GoldLapisRuneItem::new);
	public static final DeferredItem<Item> SILVER_LAPIS_RUNE = REGISTRY.register("silver_lapis_rune", SilverLapisRuneItem::new);
	public static final DeferredItem<Item> OBSIDIAN_ROCK = block(SurvivalReimaginedModBlocks.OBSIDIAN_ROCK);
	public static final DeferredItem<Item> HEMATITE_ORE = block(SurvivalReimaginedModBlocks.HEMATITE_ORE);
	public static final DeferredItem<Item> DEEPSLATE_HEMATITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_HEMATITE_ORE);
	public static final DeferredItem<Item> BASALT_HEMATITE_ORE = block(SurvivalReimaginedModBlocks.BASALT_HEMATITE_ORE);
	public static final DeferredItem<Item> HEMATITE_BLOCK = block(SurvivalReimaginedModBlocks.HEMATITE_BLOCK);
	public static final DeferredItem<Item> MAGNETITE_ORE = block(SurvivalReimaginedModBlocks.MAGNETITE_ORE);
	public static final DeferredItem<Item> DEEPSLATE_MAGNETITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_MAGNETITE_ORE);
	public static final DeferredItem<Item> BASALT_MAGNETITE_ORE = block(SurvivalReimaginedModBlocks.BASALT_MAGNETITE_ORE);
	public static final DeferredItem<Item> MAGNETITE_BLOCK = block(SurvivalReimaginedModBlocks.MAGNETITE_BLOCK);
	public static final DeferredItem<Item> MAGNETITE_CHUNK = REGISTRY.register("magnetite_chunk", MagnetiteChunkItem::new);
	public static final DeferredItem<Item> HEMATITE_CHUNK = REGISTRY.register("hematite_chunk", HematiteChunkItem::new);
	public static final DeferredItem<Item> MAGNETITE_NUGGET = REGISTRY.register("magnetite_nugget", MagnetiteNuggetItem::new);
	public static final DeferredItem<Item> HEMATITE_NUGGET = REGISTRY.register("hematite_nugget", HematiteNuggetItem::new);
	public static final DeferredItem<Item> MALACHITE_ORE = block(SurvivalReimaginedModBlocks.MALACHITE_ORE);
	public static final DeferredItem<Item> DEEPSLATE_MALACHITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_MALACHITE_ORE);
	public static final DeferredItem<Item> MALACHITE = REGISTRY.register("malachite", MalachiteItem::new);
	public static final DeferredItem<Item> MALACHITE_NUGGET = REGISTRY.register("malachite_nugget", MalachiteNuggetItem::new);
	public static final DeferredItem<Item> RAW_MALACHITE_BLOCK = block(SurvivalReimaginedModBlocks.RAW_MALACHITE_BLOCK);
	public static final DeferredItem<Item> AZURITE_ORE = block(SurvivalReimaginedModBlocks.AZURITE_ORE);
	public static final DeferredItem<Item> DEEPSLATE_AZURITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_AZURITE_ORE);
	public static final DeferredItem<Item> AZURITE = REGISTRY.register("azurite", AzuriteItem::new);
	public static final DeferredItem<Item> AZURITE_NUGGET = REGISTRY.register("azurite_nugget", AzuriteNuggetItem::new);
	public static final DeferredItem<Item> RAW_AZURITE_BLOCK = block(SurvivalReimaginedModBlocks.RAW_AZURITE_BLOCK);
	public static final DeferredItem<Item> CASSITERITE_ORE = block(SurvivalReimaginedModBlocks.CASSITERITE_ORE);
	public static final DeferredItem<Item> DEEPSLATE_CASSITERITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_CASSITERITE_ORE);
	public static final DeferredItem<Item> RAW_CASSITERITE_BLOCK = block(SurvivalReimaginedModBlocks.RAW_CASSITERITE_BLOCK);
	public static final DeferredItem<Item> CASSITERITE = REGISTRY.register("cassiterite", CassiteriteItem::new);
	public static final DeferredItem<Item> CASSITERITE_NUGGET = REGISTRY.register("cassiterite_nugget", CassiteriteNuggetItem::new);
	public static final DeferredItem<Item> DEEPSLATE_SILVER_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_SILVER_ORE);
	public static final DeferredItem<Item> ARGENTITE_ORE = block(SurvivalReimaginedModBlocks.ARGENTITE_ORE);
	public static final DeferredItem<Item> DEEPSLATE_ARGENTITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_ARGENTITE_ORE);
	public static final DeferredItem<Item> BASALT_ARGENTITE_ORE = block(SurvivalReimaginedModBlocks.BASALT_ARGENTITE_ORE);
	public static final DeferredItem<Item> ARGENTITE = REGISTRY.register("argentite", ArgentiteItem::new);
	public static final DeferredItem<Item> ARGENTITE_NUGGET = REGISTRY.register("argentite_nugget", ArgentiteNuggetItem::new);
	public static final DeferredItem<Item> ARGENTITE_BLOCK = block(SurvivalReimaginedModBlocks.ARGENTITE_BLOCK);
	public static final DeferredItem<Item> BASALT_URANINITE_ORE = block(SurvivalReimaginedModBlocks.BASALT_URANINITE_ORE);
	public static final DeferredItem<Item> CALAVERITE_ORE = block(SurvivalReimaginedModBlocks.CALAVERITE_ORE);
	public static final DeferredItem<Item> DEEPSLATE_CALAVERITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_CALAVERITE_ORE);
	public static final DeferredItem<Item> BASALT_CALAVERITE_ORE = block(SurvivalReimaginedModBlocks.BASALT_CALAVERITE_ORE);
	public static final DeferredItem<Item> CALAVERITE = REGISTRY.register("calaverite", CalaveriteItem::new);
	public static final DeferredItem<Item> CALAVERITE_NUGGET = REGISTRY.register("calaverite_nugget", CalaveriteNuggetItem::new);
	public static final DeferredItem<Item> CALAVERITE_BLOCK = block(SurvivalReimaginedModBlocks.CALAVERITE_BLOCK);
	public static final DeferredItem<Item> MANGANITE_ORE = block(SurvivalReimaginedModBlocks.MANGANITE_ORE);
	public static final DeferredItem<Item> DEEPSLATE_MANGANITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_MANGANITE_ORE);
	public static final DeferredItem<Item> BASALT_MANGANITE_ORE = block(SurvivalReimaginedModBlocks.BASALT_MANGANITE_ORE);
	public static final DeferredItem<Item> MANGANITE_BLOCK = block(SurvivalReimaginedModBlocks.MANGANITE_BLOCK);
	public static final DeferredItem<Item> MANGANITE = REGISTRY.register("manganite", ManganiteItem::new);
	public static final DeferredItem<Item> MANGANITE_NUGGET = REGISTRY.register("manganite_nugget", ManganiteNuggetItem::new);
	public static final DeferredItem<Item> PYROLUSITE_ORE = block(SurvivalReimaginedModBlocks.PYROLUSITE_ORE);
	public static final DeferredItem<Item> PYROLUSITE_BLOCK = block(SurvivalReimaginedModBlocks.PYROLUSITE_BLOCK);
	public static final DeferredItem<Item> PYROLUSITE = REGISTRY.register("pyrolusite", PyrolusiteItem::new);
	public static final DeferredItem<Item> PYROLUSITE_NUGGET = REGISTRY.register("pyrolusite_nugget", PyrolusiteNuggetItem::new);
	public static final DeferredItem<Item> DEEPSLATE_PYROLUSITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_PYROLUSITE_ORE);
	public static final DeferredItem<Item> URANOPHANE_ORE = block(SurvivalReimaginedModBlocks.URANOPHANE_ORE);
	public static final DeferredItem<Item> DEEPSLATE_URANOPHANE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_URANOPHANE_ORE);
	public static final DeferredItem<Item> BASALT_URANOPHANE_ORE = block(SurvivalReimaginedModBlocks.BASALT_URANOPHANE_ORE);
	public static final DeferredItem<Item> SHALE_URANOPHANE_ORE = block(SurvivalReimaginedModBlocks.SHALE_URANOPHANE_ORE);
	public static final DeferredItem<Item> URANOPHANE_BLOCK = block(SurvivalReimaginedModBlocks.URANOPHANE_BLOCK);
	public static final DeferredItem<Item> URANOPHANE = REGISTRY.register("uranophane", UranophaneItem::new);
	public static final DeferredItem<Item> URANOPHANE_NUGGET = REGISTRY.register("uranophane_nugget", UranophaneNuggetItem::new);
	public static final DeferredItem<Item> ILMENITE_ORE = block(SurvivalReimaginedModBlocks.ILMENITE_ORE);
	public static final DeferredItem<Item> DEEPSLATE_ILMENITE_ORE = block(SurvivalReimaginedModBlocks.DEEPSLATE_ILMENITE_ORE);
	public static final DeferredItem<Item> BASALT_ILMENITE_ORE = block(SurvivalReimaginedModBlocks.BASALT_ILMENITE_ORE);
	public static final DeferredItem<Item> ILMENITE = REGISTRY.register("ilmenite", IlmeniteItem::new);
	public static final DeferredItem<Item> ILMENITE_NUGGET = REGISTRY.register("ilmenite_nugget", IlmeniteNuggetItem::new);
	public static final DeferredItem<Item> ILMENITE_BLOCK = block(SurvivalReimaginedModBlocks.ILMENITE_BLOCK);
	public static final DeferredItem<Item> KIMBERLITE_ROCK = block(SurvivalReimaginedModBlocks.KIMBERLITE_ROCK);
	public static final DeferredItem<Item> KIMBERLITE = block(SurvivalReimaginedModBlocks.KIMBERLITE);
	public static final DeferredItem<Item> KIMBERLITE_STALAGMITE_TOP = block(SurvivalReimaginedModBlocks.KIMBERLITE_STALAGMITE_TOP);
	public static final DeferredItem<Item> KIMBERLITE_STALAGMITE_MIDDLE = block(SurvivalReimaginedModBlocks.KIMBERLITE_STALAGMITE_MIDDLE);
	public static final DeferredItem<Item> KIMBERLITE_STALAGMITE_BASE = block(SurvivalReimaginedModBlocks.KIMBERLITE_STALAGMITE_BASE);
	public static final DeferredItem<Item> KIMBERLITE_STALAGTITE_TIP = block(SurvivalReimaginedModBlocks.KIMBERLITE_STALAGTITE_TIP);
	public static final DeferredItem<Item> KIMBERLITE_STALAGTITE_MIDDLE = block(SurvivalReimaginedModBlocks.KIMBERLITE_STALAGTITE_MIDDLE);
	public static final DeferredItem<Item> KIMBERLITE_STALAGTITE_BASE = block(SurvivalReimaginedModBlocks.KIMBERLITE_STALAGTITE_BASE);
	public static final DeferredItem<Item> DEEPSLATE_STALAGMITE_TOP = block(SurvivalReimaginedModBlocks.DEEPSLATE_STALAGMITE_TOP);
	public static final DeferredItem<Item> DEEPSLATE_STALAGMITE_MIDDLE = block(SurvivalReimaginedModBlocks.DEEPSLATE_STALAGMITE_MIDDLE);
	public static final DeferredItem<Item> DEEPSLATE_STALAGMITE_BASE = block(SurvivalReimaginedModBlocks.DEEPSLATE_STALAGMITE_BASE);
	public static final DeferredItem<Item> DEEPSLATE_STALAGTITE_TIP = block(SurvivalReimaginedModBlocks.DEEPSLATE_STALAGTITE_TIP);
	public static final DeferredItem<Item> DEEPSLATE_STALAGTITE_MIDDLE = block(SurvivalReimaginedModBlocks.DEEPSLATE_STALAGTITE_MIDDLE);
	public static final DeferredItem<Item> DEEPSLATE_STALAGTITE_BASE = block(SurvivalReimaginedModBlocks.DEEPSLATE_STALAGTITE_BASE);
	public static final DeferredItem<Item> STONE_STALAGMITE_TOP = block(SurvivalReimaginedModBlocks.STONE_STALAGMITE_TOP);
	public static final DeferredItem<Item> STONE_STALAGMITE_MIDDLE = block(SurvivalReimaginedModBlocks.STONE_STALAGMITE_MIDDLE);
	public static final DeferredItem<Item> STONE_STALAGMITE_BASE = block(SurvivalReimaginedModBlocks.STONE_STALAGMITE_BASE);
	public static final DeferredItem<Item> STONE_STALAGTITE_TIP = block(SurvivalReimaginedModBlocks.STONE_STALAGTITE_TIP);
	public static final DeferredItem<Item> STONE_STALAGTITE_MIDDLE = block(SurvivalReimaginedModBlocks.STONE_STALAGTITE_MIDDLE);
	public static final DeferredItem<Item> STONE_STALAGTITE_BASE = block(SurvivalReimaginedModBlocks.STONE_STALAGTITE_BASE);
	public static final DeferredItem<Item> BASALT_STALAGMITE_TOP = block(SurvivalReimaginedModBlocks.BASALT_STALAGMITE_TOP);
	public static final DeferredItem<Item> BASALT_STALAGMITE_MIDDLE = block(SurvivalReimaginedModBlocks.BASALT_STALAGMITE_MIDDLE);
	public static final DeferredItem<Item> BASALT_STALAGMITE_BASE = block(SurvivalReimaginedModBlocks.BASALT_STALAGMITE_BASE);
	public static final DeferredItem<Item> BASALT_STALAGTITE_TIP = block(SurvivalReimaginedModBlocks.BASALT_STALAGTITE_TIP);
	public static final DeferredItem<Item> BASALT_STALAGTITE_MIDDLE = block(SurvivalReimaginedModBlocks.BASALT_STALAGTITE_MIDDLE);
	public static final DeferredItem<Item> BASALT_STALAGTITE_BASE = block(SurvivalReimaginedModBlocks.BASALT_STALAGTITE_BASE);
	public static final DeferredItem<Item> ROUGH_SAPPHIRE = REGISTRY.register("rough_sapphire", RoughSapphireItem::new);
	public static final DeferredItem<Item> BASALT_SAPPHIRE_ORE = block(SurvivalReimaginedModBlocks.BASALT_SAPPHIRE_ORE);
	public static final DeferredItem<Item> KIMBERLITE_SAPPHIRE_ORE = block(SurvivalReimaginedModBlocks.KIMBERLITE_SAPPHIRE_ORE);
	public static final DeferredItem<Item> BASALT_DIAMOND_ORE = block(SurvivalReimaginedModBlocks.BASALT_DIAMOND_ORE);
	public static final DeferredItem<Item> KIMBERLITE_DIAMOND_ORE = block(SurvivalReimaginedModBlocks.KIMBERLITE_DIAMOND_ORE);
	public static final DeferredItem<Item> ROUGH_DIAMOND = REGISTRY.register("rough_diamond", RoughDiamondItem::new);
	public static final DeferredItem<Item> BASALT_EMERALD_ORE = block(SurvivalReimaginedModBlocks.BASALT_EMERALD_ORE);
	public static final DeferredItem<Item> KIMBERLITE_EMERALD_ORE = block(SurvivalReimaginedModBlocks.KIMBERLITE_EMERALD_ORE);
	public static final DeferredItem<Item> ROUGH_EMERALD = REGISTRY.register("rough_emerald", RoughEmeraldItem::new);
	public static final DeferredItem<Item> BASALT_RUBY_ORE = block(SurvivalReimaginedModBlocks.BASALT_RUBY_ORE);
	public static final DeferredItem<Item> KIMBERLITE_RUBY_ORE = block(SurvivalReimaginedModBlocks.KIMBERLITE_RUBY_ORE);
	public static final DeferredItem<Item> ROUGH_RUBY = REGISTRY.register("rough_ruby", RoughRubyItem::new);
	public static final DeferredItem<Item> BASALT_LAPIS_ORE = block(SurvivalReimaginedModBlocks.BASALT_LAPIS_ORE);
	public static final DeferredItem<Item> KIMBERLITE_LAPIS_ORE = block(SurvivalReimaginedModBlocks.KIMBERLITE_LAPIS_ORE);
	public static final DeferredItem<Item> BASALT_AMBER_ORE = block(SurvivalReimaginedModBlocks.BASALT_AMBER_ORE);
	public static final DeferredItem<Item> KIMBERLITE_AMBER_ORE = block(SurvivalReimaginedModBlocks.KIMBERLITE_AMBER_ORE);
	public static final DeferredItem<Item> ROUGH_AMBER = REGISTRY.register("rough_amber", RoughAmberItem::new);
	public static final DeferredItem<Item> SULFUR_ORE = block(SurvivalReimaginedModBlocks.SULFUR_ORE);
	public static final DeferredItem<Item> NITRE_POWDER = block(SurvivalReimaginedModBlocks.NITRE_POWDER);
	public static final DeferredItem<Item> RUBY_HEART_SHARD = REGISTRY.register("ruby_heart_shard", RubyHeartShardItem::new);
	public static final DeferredItem<Item> RUBY_HEART = REGISTRY.register("ruby_heart", RubyHeartItem::new);
	public static final DeferredItem<Item> GOLD_HEART = REGISTRY.register("gold_heart", GoldHeartItem::new);
	public static final DeferredItem<Item> STRIPPED_WISTERIA_LOG = block(SurvivalReimaginedModBlocks.STRIPPED_WISTERIA_LOG);
	public static final DeferredItem<Item> WISTERIA_WOOD = block(SurvivalReimaginedModBlocks.WISTERIA_WOOD);
	public static final DeferredItem<Item> WISTERIA_PLANKS = block(SurvivalReimaginedModBlocks.WISTERIA_PLANKS);
	public static final DeferredItem<Item> WISTERIA_STAIRS = block(SurvivalReimaginedModBlocks.WISTERIA_STAIRS);
	public static final DeferredItem<Item> WISTERIA_SLAB = block(SurvivalReimaginedModBlocks.WISTERIA_SLAB);
	public static final DeferredItem<Item> WISTERIA_FENCE = block(SurvivalReimaginedModBlocks.WISTERIA_FENCE);
	public static final DeferredItem<Item> WISTERIA_FENCE_GATE = block(SurvivalReimaginedModBlocks.WISTERIA_FENCE_GATE);
	public static final DeferredItem<Item> WISTERIA_DOOR = doubleBlock(SurvivalReimaginedModBlocks.WISTERIA_DOOR);
	public static final DeferredItem<Item> WISTERIA_TRAPDOOR = block(SurvivalReimaginedModBlocks.WISTERIA_TRAPDOOR);
	public static final DeferredItem<Item> WISTERIA_PLANK = REGISTRY.register("wisteria_plank", WisteriaPlankItem::new);
	public static final DeferredItem<Item> WISTERIA_BUTTON = block(SurvivalReimaginedModBlocks.WISTERIA_BUTTON);
	public static final DeferredItem<Item> WISTERIA_PRESSURE_PLATE = block(SurvivalReimaginedModBlocks.WISTERIA_PRESSURE_PLATE);
	public static final DeferredItem<Item> WISTERIA_BARK = REGISTRY.register("wisteria_bark", WisteriaBarkItem::new);
	public static final DeferredItem<Item> ZOMBIE_FACE = REGISTRY.register("zombie_face", ZombieFaceItem::new);
	public static final DeferredItem<Item> PARANOIA_EYE = REGISTRY.register("paranoia_eye", ParanoiaEyeItem::new);
	public static final DeferredItem<Item> FEAR_EYE = REGISTRY.register("fear_eye", FearEyeItem::new);
	public static final DeferredItem<Item> EYE_CLOSED = REGISTRY.register("eye_closed", EyeClosedItem::new);
	public static final DeferredItem<Item> PINE_BARK_RU = REGISTRY.register("pine_bark_ru", PineBarkRUItem::new);
	public static final DeferredItem<Item> WILLOW_BARK_RU = REGISTRY.register("willow_bark_ru", WillowBarkRUItem::new);
	public static final DeferredItem<Item> REDWOOD_BARK_RU = REGISTRY.register("redwood_bark_ru", RedwoodBarkRUItem::new);
	public static final DeferredItem<Item> MAGNOILA_BARK = REGISTRY.register("magnoila_bark", MagnoilaBarkItem::new);
	public static final DeferredItem<Item> KAPOK_BARK = REGISTRY.register("kapok_bark", KapokBarkItem::new);
	public static final DeferredItem<Item> LARCH_BARK = REGISTRY.register("larch_bark", LarchBarkItem::new);
	public static final DeferredItem<Item> EUCALYPTUS_BARK = REGISTRY.register("eucalyptus_bark", EucalyptusBarkItem::new);
	public static final DeferredItem<Item> CYPRESS_BARK = REGISTRY.register("cypress_bark", CypressBarkItem::new);
	public static final DeferredItem<Item> SOCOTRA_BARK = REGISTRY.register("socotra_bark", SocotraBarkItem::new);
	public static final DeferredItem<Item> MAUVE_BARK = REGISTRY.register("mauve_bark", MauveBarkItem::new);
	public static final DeferredItem<Item> MAPLE_BARK_RU = REGISTRY.register("maple_bark_ru", MapleBarkRUItem::new);
	public static final DeferredItem<Item> DEAD_BARK_RU = REGISTRY.register("dead_bark_ru", DeadBarkRUItem::new);
	public static final DeferredItem<Item> COBALT_BARK = REGISTRY.register("cobalt_bark", CobaltBarkItem::new);
	public static final DeferredItem<Item> BRIMWOOD_BARK = REGISTRY.register("brimwood_bark", BrimwoodBarkItem::new);
	public static final DeferredItem<Item> BAOBAB_BARK = REGISTRY.register("baobab_bark", BaobabBarkItem::new);
	public static final DeferredItem<Item> SILVER_BIRCH_BARK = REGISTRY.register("silver_birch_bark", SilverBirchBarkItem::new);
	public static final DeferredItem<Item> ASHEN_BARK = REGISTRY.register("ashen_bark", AshenBarkItem::new);
	public static final DeferredItem<Item> JOSHUA_BARK = REGISTRY.register("joshua_bark", JoshuaBarkItem::new);
	public static final DeferredItem<Item> ALPHA_OAK_BARK = REGISTRY.register("alpha_oak_bark", AlphaOakBarkItem::new);
	public static final DeferredItem<Item> BLACKWOOD_BARK = REGISTRY.register("blackwood_bark", BlackwoodBarkItem::new);
	public static final DeferredItem<Item> PALM_BARK_RU = REGISTRY.register("palm_bark_ru", PalmBarkRUItem::new);
	public static final DeferredItem<Item> ARGILLITE_ROCK = REGISTRY.register("argillite_rock", ArgilliteRockItem::new);
	public static final DeferredItem<Item> VOLCANIC_ASH_PILE = REGISTRY.register("volcanic_ash_pile", VolcanicAshPileItem::new);
	public static final DeferredItem<Item> ASH_PILE = REGISTRY.register("ash_pile", AshPileItem::new);
	public static final DeferredItem<Item> SILT_MUD_PILE = REGISTRY.register("silt_mud_pile", SiltMudPileItem::new);
	public static final DeferredItem<Item> SILT_COARSE_DIRT_PILE = REGISTRY.register("silt_coarse_dirt_pile", SiltCoarseDirtPileItem::new);
	public static final DeferredItem<Item> SILT_DIRT_PILE = REGISTRY.register("silt_dirt_pile", SiltDirtPileItem::new);
	public static final DeferredItem<Item> PEAT_PILE = REGISTRY.register("peat_pile", PeatPileItem::new);
	public static final DeferredItem<Item> PEAT_COARSE_DIRT_PILE = REGISTRY.register("peat_coarse_dirt_pile", PeatCoarseDirtPileItem::new);
	public static final DeferredItem<Item> PEAT_MUD_PILE = REGISTRY.register("peat_mud_pile", PeatMudPileItem::new);
	public static final DeferredItem<Item> ASHEN_DIRT_PILE = REGISTRY.register("ashen_dirt_pile", AshenDirtPileItem::new);

	// Start of user code block custom items
	// End of user code block custom items
	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new BackpackInventoryCapability(stack), BACKPACK.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new AAFScriptureInventoryCapability(stack), AAF_SCRIPTURE.get());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
